### ISSUE TITLE
can't start threebot: misconfigured redis when starting

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1014]
while starting threebot using `threebot start --local`

### systemd status

```
➜  info_gridmanual git:(development) systemctl status redis
● redis-server.service - Advanced key-value store
     Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
     Active: deactivating (stop-sigterm) since Sun 2020-09-06 15:38:26 EET; 5min ago
       Docs: http://redis.io/documentation,
             man:redis-server(1)
    Process: 1981 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=0/SUCCESS)
   Main PID: 2112 (redis-server)
      Tasks: 4 (limit: 18983)
     Memory: 11.9M
     CGroup: /system.slice/redis-server.service
             └─2112 /usr/bin/redis-server 127.0.0.1:6379

Sep 06 15:38:26 xmonader-ThinkPad-E580 systemd[1]: Stopping Advanced key-value store...
Warning: journal has been rotated since unit was started, output may be incomplete.
➜  info_gridmanual git:(development) systemctl status nginx
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Sun 2020-09-06 15:38:17 EET; 5min ago
       Docs: man:nginx(8)
    Process: 1977 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
    Process: 2021 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
    Process: 252390 ExecStop=/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile /run/nginx.pid (code=exited>
   Main PID: 2023 (code=exited, status=0/SUCCESS)

Sep 06 15:38:17 xmonader-ThinkPad-E580 systemd[1]: Stopping A high performance web server and a reverse proxy server...
Sep 06 15:38:17 xmonader-ThinkPad-E580 systemd[1]: nginx.service: Succeeded.
Sep 06 15:38:17 xmonader-ThinkPad-E580 systemd[1]: Stopped A high performance web server and a reverse proxy server.
Warning: journal has been rotated since unit was started, output may be incomplete.

```

### trace
```
➜  js-sdk git:(development) ✗ poetry run threebot start --local
2020-09-06 15:40:00.501 | INFO     | jumpscale.entry_points.threebot:check_for_bins:34 - ✅ binaries nginx,redis-server,tmux,git required are installed.
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(microseconds=9942), 'exception': None, 'extra': {'appname': 'init', 'category': '', 'data': None}, 'file': 'threebot.py', 'function': 'check_for_bins', 'level': 'INFO', 'line': 34, 'message': '✅ binaries nginx,redis-server,tmux,git required are installed.', 'module': 'threebot', 'name': 'jumpscale.entry_points.threebot', 'process': '252919', 'thread': '139649314928576', 'time': datetime(2020, 9, 6, 15, 40, 0, 501949, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200), 'EET'))}
Traceback (most recent call last):
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/loguru/_handler.py", line 144, in emit
    self._writer(str_record)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/core/logging/logging.py", line 166, in _handle
    if not self._db.is_running():
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/clients/redis/redis.py", line 51, in is_running
    return self.redis_client.ping()
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/client.py", line 1378, in ping
    return self.execute_command('PING')
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
--- End of logging error ---
2020-09-06 15:40:00.583 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2020-09-06 15:40:00.584 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: the configuration file /home/xmonader/wspace/js/js-sdk/tmp98kpjc57 syntax is ok
2020-09-06 15:40:00.584 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - 2020/09/06 15:40:00 [emerg] 252946#252946: bind() to 0.0.0.0:80 failed (13: Permission denied)
2020-09-06 15:40:00.584 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: configuration file /home/xmonader/wspace/js/js-sdk/tmp98kpjc57 test failed
2020-09-06 15:40:04.366 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
Traceback (most recent call last):
> File "<string>", line 1, in <module>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f02a2d0b550>
           └ <Group cli>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f02a3f90eb0>
         │    └ <function MultiCommand.invoke at 0x7f02a2d0c310>
         └ <Group cli>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f02a3ee6220>
           │               │       │       └ <function Command.invoke at 0x7f02a2d0bee0>
           │               │       └ <Command start>
           │               └ <click.core.Context object at 0x7f02a3ee6220>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f02a3f81280>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'local': True, 'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False}
           │   │      │    │           └ <click.core.Context object at 0x7f02a3ee6220>
           │   │      │    └ <function start at 0x7f02a069a0d0>
           │   │      └ <Command start>
           │   └ <function Context.invoke at 0x7f02a2d0b040>
           └ <click.core.Context object at 0x7f02a3ee6220>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'local': True, 'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False}
           │         └ ()
           └ <function start at 0x7f02a069a0d0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/entry_points/threebot.py", line 156, in start
    j.servers.threebot.start_default(wait=True, local=local, domain=domain, email=email)
    │ │                                         │     │      │      │       │     └ None
    │ │                                         │     │      │      │       └ None
    │ │                                         │     │      │      └ None
    │ │                                         │     │      └ None
    │ │                                         │     └ True
    │ │                                         └ True
    │ └ <property object at 0x7f02a2d12590>
    └ <jumpscale.loader.J object at 0x7f02a2d10370>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/servers/threebot/__init__.py", line 31, in start_default
    server.start(wait=wait)
    │      │     │    └ True
    │      │     └ True
    │      └ <function ThreebotServer.start at 0x7f029f937040>
    └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/servers/threebot/threebot.py", line 639, in start
    self.rack.start()
    │    └ <property object at 0x7f029f935360>
    └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/servers/rack/rack.py", line 60, in start
    self._start(server_name)
    │    │      └ 'gedis'
    │    └ <function ServerRack._start at 0x7f029f937e50>
    └ ServerRack(_Base__instance_name=None, _Base__parent=None, _factories={}, _running_event=<gevent._event.Event object at 0x7f02...
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/servers/rack/rack.py", line 15, in _start
    self._servers[server_name].start()
    │    │        └ 'gedis'
    │    └ {'gedis': GedisServer(_Base__instance_name='threebot', _Base__parent=None, ___actors={}, __enable_system_actor=True, __host='...
    └ ServerRack(_Base__instance_name=None, _Base__parent=None, _factories={}, _running_event=<gevent._event.Event object at 0x7f02...
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/servers/gedis/server.py", line 192, in start
    j.application.start("gedis")
    │ └ <property object at 0x7f02a2d12220>
    └ <jumpscale.loader.J object at 0x7f02a2d10370>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/core/application/application.py", line 20, in start
    if j.core.db.is_running():
       │ └ <property object at 0x7f02a2d126d0>
       └ <jumpscale.loader.J object at 0x7f02a2d10370>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/clients/redis/redis.py", line 51, in is_running
    return self.redis_client.ping()
           │    └ <property object at 0x7f02a0534a90>
           └ RedisClient(_Base__instance_name='main', _Base__parent=None, _RedisClient__client=Redis<ConnectionPool<Connection<host=localh...
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/client.py", line 1378, in ping
    return self.execute_command('PING')
           │    └ <function Redis.execute_command at 0x7f02a10ab670>
           └ Redis<ConnectionPool<Connection<host=localhost,port=6379,db=0>>>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
           │    │              │     │               └ {}
           │    │              │     └ 'PING'
           │    │              └ Connection<host=localhost,port=6379,db=0>
           │    └ <function Redis.parse_response at 0x7f02a10ab700>
           └ Redis<ConnectionPool<Connection<host=localhost,port=6379,db=0>>>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
               │          └ <function Connection.read_response at 0x7f02a109ec10>
               └ Connection<host=localhost,port=6379,db=0>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
          └ ResponseError('MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands t...

redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=3, microseconds=874657), 'exception': ExceptionRecattr(type=<class 'redis.exceptions.ResponseError'>, value=ResponseError('MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.'), traceback=<traceback object at 0x7f029f7fd180>), 'extra': {'appname': 'gedis', 'category': '', 'data': None}, 'file': 'errorhandler.py', 'function': '_handle_exception', 'level': 'ERROR', 'line': 55, 'message': 'redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.', 'module': 'errorhandler', 'name': 'jumpscale.tools.errorhandler.errorhandler', 'process': '252919', 'thread': '139649314928576', 'time': datetime(2020, 9, 6, 15, 40, 4, 366664, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200), 'EET'))}
Traceback (most recent call last):
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/loguru/_handler.py", line 144, in emit
    self._writer(str_record)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/core/logging/logging.py", line 166, in _handle
    if not self._db.is_running():
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/clients/redis/redis.py", line 51, in is_running
    return self.redis_client.ping()
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/client.py", line 1378, in ping
    return self.execute_command('PING')
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
--- End of logging error ---
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/clients/redis/redis.py", line 51, in is_running
    return self.redis_client.ping()
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/client.py", line 1378, in ping
    return self.execute_command('PING')
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/xmonader/wspace/js/js-sdk/jumpscale/entry_points/threebot.py", line 156, in start
    j.servers.threebot.start_default(wait=True, local=local, domain=domain, email=email)
  File "/home/xmonader/wspace/js/js-sdk/jumpscale/servers/threebot/__init__.py", line 31, in start_default
    server.start(wait=wait)
  File "/home/xmonader/wspace/js/js-sdk/jumpscale/servers/threebot/threebot.py", line 639, in start
    self.rack.start()
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/servers/rack/rack.py", line 60, in start
    self._start(server_name)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/servers/rack/rack.py", line 15, in _start
    self._servers[server_name].start()
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/servers/gedis/server.py", line 192, in start
    j.application.start("gedis")
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/core/application/application.py", line 20, in start
    if j.core.db.is_running():
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/clients/redis/redis.py", line 51, in is_running
    return self.redis_client.ping()
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/client.py", line 1378, in ping
    return self.execute_command('PING')
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```

## versions

- js-sdk b4e797edde034886342740b966857951faeb6afb
- os: linux ubuntu 20.04

**Comment by xmonader** [comment]
fixed using 
```
config set stop-writes-on-bgsave-error no
```
