### ISSUE TITLE
when starting threebot: cannot find static dir /home/ahmed/sandbox/code/github/jumpscaleX_weblibs/static

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#103]
```

Traceback (most recent call last):
> File "/home/ahmed/.cache/pypoetry/virtualenvs/js-sdk--OGPzDz5-py3.6/bin/jsng", line 33, in <module>
    sys.exit(load_entry_point('js-ng', 'console_scripts', 'jsng')())
    │   │    └ <function importlib_load_entry_point at 0x7f2209b78e18>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "/home/ahmed/.cache/pypoetry/virtualenvs/js-sdk--OGPzDz5-py3.6/src/js-ng/jumpscale/entry_points/jsng.py", line 24, in run
    sys.exit(print(eval(sys.argv[1])))
    │   │               │   └ ['/home/ahmed/.cache/pypoetry/virtualenvs/js-sdk--OGPzDz5-py3.6/bin/jsng', 'j.servers.threebot.start_default(wait=True)']
    │   │               └ <module 'sys' (built-in)>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "<string>", line 1, in <module>

  File "/home/ahmed/wspace/js/js-sdk/jumpscale/servers/threebot/__init__.py", line 14, in start_default
    server.start(wait=wait)
    │      │     │    └ True
    │      │     └ True
    │      └ <function ThreebotServer.start at 0x7f220116b0d0>
    └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/home/ahmed/wspace/js/js-sdk/jumpscale/servers/threebot/threebot.py", line 524, in start
    self.packages.install(package)
    │    │                └ <jumpscale.servers.threebot.threebot.Package object at 0x7f21faea3198>
    │    └ <property object at 0x7f2201167548>
    └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/home/ahmed/wspace/js/js-sdk/jumpscale/servers/threebot/threebot.py", line 373, in install
    raise j.exceptions.NotFound(f"Cannot find static dir {path}")
          │ └ <property object at 0x7f2203fa3318>
          └ <jumpscale.god.J object at 0x7f2204d96ac8>

jumpscale.core.exceptions.exceptions.NotFound: Cannot find static dir /home/ahmed/sandbox/code/github/jumpscaleX_weblibs/static


```

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
