### ISSUE TITLE
threebot start: size changed in during iteration

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1097]
# how

- clone tft_faucet git@github.com:threefoldfoundation/tft_faucet.git
- add it from admin panel with path

# traces
```
Threebot server Stopped
➜  js-sdk git:(development) poetry run threebot start

2020-09-09 20:55:55.877 | INFO     | jumpscale.entry_points.threebot:check_for_bins:34 - ✅ binaries nginx,redis-server,tmux,git required are installed.
2020-09-09 20:55:55.923 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2020-09-09 20:55:55.924 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: the configuration file /tmp/tmpu_ol39_g syntax is ok
2020-09-09 20:55:55.924 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: configuration file /tmp/tmpu_ol39_g test is successful
2020-09-09 20:55:59.402 | INFO     | jumpscale.core.application.application:start:23 - Application gedis is started, process id: 393606
2020-09-09 20:55:59.405 | INFO     | jumpscale.core.application.application:start:23 - Application threebot_default is started, process id: 393606
2020-09-09 20:55:59.407 | INFO     | jumpscale.servers.threebot.threebot:start:644 - Configuring package auth
2020-09-09 20:56:00.453 | INFO     | jumpscale.servers.threebot.threebot:start:644 - Configuring package chatflows
2020-09-09 20:56:01.044 | INFO     | jumpscale.servers.threebot.threebot:start:644 - Configuring package admin
2020-09-09 20:56:01.688 | INFO     | jumpscale.servers.threebot.threebot:start:644 - Configuring package weblibs
2020-09-09 20:56:02.013 | INFO     | jumpscale.servers.threebot.threebot:start:644 - Configuring package tfgrid_solutions
2020-09-09 20:56:02.506 | INFO     | jumpscale.servers.threebot.threebot:start:644 - Configuring package backup
2020-09-09 20:56:02.964 | INFO     | jumpscale.servers.threebot.threebot:_install_all:522 - Configuring package marketplace
127.0.0.1 - - [2020-09-09 20:56:05] "GET /authorized HTTP/1.0" 200 221 1.292479
127.0.0.1 - - [2020-09-09 20:56:05] "GET /authorized HTTP/1.0" 200 221 0.011758
127.0.0.1 - - [2020-09-09 20:56:05] "GET /authorized HTTP/1.0" 200 221 0.009293
127.0.0.1 - - [2020-09-09 20:56:05] "GET /api/allowed HTTP/1.0" 200 144 0.012760
127.0.0.1 - - [2020-09-09 20:56:05] "GET /authorized HTTP/1.0" 200 221 0.008504
127.0.0.1 - - [2020-09-09 20:56:05] "GET /authenticated HTTP/1.0" 200 221 0.005943
2020-09-09 20:56:06.002 | INFO     | jumpscale.servers.gedis.server:_on_connection:238 - New connection from ('127.0.0.1', 59000)
2020-09-09 20:56:06.004 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method list_actors from actor core to client ('127.0.0.1', 59000)
2020-09-09 20:56:06.011 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method info from actor core to client ('127.0.0.1', 59000)
2020-09-09 20:56:06.015 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method info from actor system to client ('127.0.0.1', 59000)
2020-09-09 20:56:06.019 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method info from actor chatflows_chatbot to client ('127.0.0.1', 59000)
2020-09-09 20:56:06.022 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method info from actor admin_alerts to client ('127.0.0.1', 59000)
2020-09-09 20:56:06.028 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method info from actor admin_logs to client ('127.0.0.1', 59000)
2020-09-09 20:56:06.031 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method info from actor admin_health to client ('127.0.0.1', 59000)
2020-09-09 20:56:06.035 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method info from actor admin_packages to client ('127.0.0.1', 59000)
2020-09-09 20:56:06.043 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method info from actor admin_identity to client ('127.0.0.1', 59000)
2020-09-09 20:56:06.046 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method info from actor admin_wallet to client ('127.0.0.1', 59000)
2020-09-09 20:56:06.050 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method info from actor admin_admin to client ('127.0.0.1', 59000)
2020-09-09 20:56:06.053 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method info from actor tfgrid_solutions_solutions to client ('127.0.0.1', 59000)
2020-09-09 20:56:06.060 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method info from actor backup_minio to client ('127.0.0.1', 59000)
2020-09-09 20:56:06.064 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method info from actor backup_marketplace to client ('127.0.0.1', 59000)
2020-09-09 20:56:06.066 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method info from actor backup_threebot_deployer to client ('127.0.0.1', 59000)
2020-09-09 20:56:06.069 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method get_identity from actor admin_identity to client ('127.0.0.1', 59000)
127.0.0.1 - - [2020-09-09 20:56:06] "GET /authorized HTTP/1.0" 200 221 0.009142
127.0.0.1 - - [2020-09-09 20:56:06] "GET /authorized HTTP/1.0" 200 221 0.010207
2020-09-09 20:56:06.543 | INFO     | jumpscale.servers.gedis.server:_on_connection:238 - New connection from ('127.0.0.1', 59010)
2020-09-09 20:56:06.545 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method get_memory_usage from actor admin_health to client ('127.0.0.1', 59010)
127.0.0.1 - - [2020-09-09 20:56:06] "GET /admin/health/get_memory_usage HTTP/1.0" 200 188 0.032117
127.0.0.1 - - [2020-09-09 20:56:06] "GET /authorized HTTP/1.0" 200 221 0.007148
2020-09-09 20:56:06.637 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method get_disk_space from actor admin_health to client ('127.0.0.1', 59010)
127.0.0.1 - - [2020-09-09 20:56:06] "GET /admin/health/get_disk_space HTTP/1.0" 200 221 0.005452
127.0.0.1 - - [2020-09-09 20:56:06] "GET /authorized HTTP/1.0" 200 221 0.005420
2020-09-09 20:56:06.753 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method list_pools from actor tfgrid_solutions_solutions to client ('127.0.0.1', 59010)
127.0.0.1 - - [2020-09-09 20:56:06] "GET /authorized HTTP/1.0" 200 221 0.007168
2020-09-09 20:56:06.941 | INFO     | jumpscale.servers.gedis.server:_on_connection:238 - New connection from ('127.0.0.1', 59030)
2020-09-09 20:56:06.942 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method get_health_checks from actor admin_health to client ('127.0.0.1', 59030)
127.0.0.1 - - [2020-09-09 20:56:06] "GET /authorized HTTP/1.0" 200 221 0.007631
2020-09-09 20:56:06.991 | INFO     | jumpscale.servers.gedis.server:_on_connection:238 - New connection from ('127.0.0.1', 59046)
2020-09-09 20:56:06.994 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method get_running_processes from actor admin_health to client ('127.0.0.1', 59046)
127.0.0.1 - - [2020-09-09 20:56:07] "GET /admin/health/get_running_processes HTTP/1.0" 200 5057 0.684754
127.0.0.1 - - [2020-09-09 20:56:07] "GET /admin/identity/get_identity HTTP/1.0" 200 237 1.999467
2020-09-09 20:56:09.167 | INFO     | jumpscale.clients.stellar.stellar:activate_through_friendbot:239 - account with address GCNJBVYBIMYLLBUM3YS6S7BCL5HGYZ24ESFXHTR4QXZUH7OUMEOKTWAY activated and  funded through friendbot
127.0.0.1 - - [2020-09-09 20:56:09] "GET /admin/health/get_health_checks HTTP/1.0" 200 268 2.850936
127.0.0.1 - - [2020-09-09 20:56:11] "POST /tfgrid_solutions/solutions/list_pools HTTP/1.0" 200 6116 4.731234
127.0.0.1 - - [2020-09-09 20:56:11] "GET /authorized HTTP/1.0" 200 221 0.003646
127.0.0.1 - - [2020-09-09 20:56:11] "GET /authorized HTTP/1.0" 200 221 0.007560
127.0.0.1 - - [2020-09-09 20:56:11] "GET /api/allowed HTTP/1.0" 200 144 0.012133
127.0.0.1 - - [2020-09-09 20:56:11] "GET /authorized HTTP/1.0" 200 221 0.010483
127.0.0.1 - - [2020-09-09 20:56:11] "GET /authorized HTTP/1.0" 200 221 0.016414
2020-09-09 20:56:11.985 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method list_packages from actor admin_packages to client ('127.0.0.1', 59010)
127.0.0.1 - - [2020-09-09 20:56:11] "GET /admin/packages/list_packages HTTP/1.0" 200 2546 0.013705
127.0.0.1 - - [2020-09-09 20:56:12] "GET /authorized HTTP/1.0" 200 221 0.007193
2020-09-09 20:56:15.391 | INFO     | jumpscale.clients.stellar.stellar:_change_trustline:342 - Transaction hash: d1b34c62f96c4e1a28a763ddc08122b26e547cf3f7afab87b7fb215742307b92
127.0.0.1 - - [2020-09-09 20:56:29] "GET /authorized HTTP/1.0" 200 221 0.006422
2020-09-09 20:56:29.511 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method add_package from actor admin_packages to client ('127.0.0.1', 59010)
2020-09-09 20:56:29.513 | ERROR    | jumpscale.sals.nginx.nginx:generate_certificates:186 - Generating certificate failed IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: demo.testnet.grid.tf
   Type:   unauthorized
   Detail: Invalid response from
   https://demo.testnet.grid.tf/auth/login?next_url=/.well-known/acme-challenge/Vi8yktCPpbrBIfI5sU9NiScmNQ0mWy7i4WGBzn4oWH8
   [67.205.165.244]: "<!DOCTYPE html>\n<html lang=\"\">\n\n<head>\n
   \n    <meta charset=\"utf-8\">\n    <meta
   http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

Saving debug log to /home/xmonader/sandbox/var/log/certbot/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for demo.testnet.grid.tf
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2020/09/09 20:56:21 [notice] 393958#393958: signal process started
Waiting for verification...
Challenge failed for domain demo.testnet.grid.tf
http-01 challenge for demo.testnet.grid.tf
Cleaning up challenges
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2020/09/09 20:56:28 [notice] 393966#393966: signal process started
Some challenges have failed.

2020-09-09 20:56:30.142 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
> File "<string>", line 1, in <module>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f47fa6983a0>
           └ <Group cli>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f47fb939df0>
         │    └ <function MultiCommand.invoke at 0x7f47fa699160>
         └ <Group cli>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f47fb890160>
           │               │       │       └ <function Command.invoke at 0x7f47fa698d30>
           │               │       └ <Command start>
           │               └ <click.core.Context object at 0x7f47fb890160>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f47fb92a280>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False, 'local': False}
           │   │      │    │           └ <click.core.Context object at 0x7f47fb890160>
           │   │      │    └ <function start at 0x7f47f80a80d0>
           │   │      └ <Command start>
           │   └ <function Context.invoke at 0x7f47fa697e50>
           └ <click.core.Context object at 0x7f47fb890160>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False, 'local': False}
           │         └ ()
           └ <function start at 0x7f47f80a80d0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/entry_points/threebot.py", line 156, in start
    j.servers.threebot.start_default(wait=True, local=local, domain=domain, email=email)
    │ │                                         │     │      │      │       │     └ None
    │ │                                         │     │      │      │       └ None
    │ │                                         │     │      │      └ None
    │ │                                         │     │      └ None
    │ │                                         │     └ False
    │ │                                         └ False
    │ └ <property object at 0x7f47fa69cc70>
    └ <jumpscale.loader.J object at 0x7f47fa693670>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/servers/threebot/__init__.py", line 31, in start_default
    server.start(wait=wait)
    │      │     │    └ True
    │      │     └ True
    │      └ <function ThreebotServer.start at 0x7f47f73bde50>
    └ ThreebotServer(
        instance_name='default',
        _package_manager=StoredFactory(PackageManager),
        domain=None,
        email=None
      )

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/servers/threebot/threebot.py", line 655, in start
    self.packages._install_all()
    │    └ <property object at 0x7f47f73b9b80>
    └ ThreebotServer(
        instance_name='default',
        _package_manager=StoredFactory(PackageManager),
        domain=None,
        email=None
      )

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/servers/threebot/threebot.py", line 520, in _install_all
    for package in self.list_all():
        │          │    └ <function PackageManager.list_all at 0x7f47f73bd310>
        │          └ PackageManager(
        │              instance_name='default',
        │              parent=ThreebotServer(instance_name_='default'),
        │              packages={'auth': {'path': '/...
        └ 'marketplace'

RuntimeError: dictionary changed size during iteration
127.0.0.1 - - [2020-09-09 20:56:30] "POST /admin/packages/add_package HTTP/1.0" 200 255 0.696622
➜  js-sdk git:(development) 
```

**Comment by xmonader** [comment]
also using ag to check the codebase showed
```
➜  js ag 'in .+\.list_all()' --py
js-sdk/jumpscale/sals/marketplace/chatflow.py
22:        if instance_name in user_factory.list_all():

js-sdk/jumpscale/sals/nginx/nginx.py
154:        for location in self.locations.list_all():

js-sdk/jumpscale/sals/reservation_chatflow/deployer.py
442:            if f"pool_{pool.pool_id}" in pool_factory.list_all():
1090:                if f"pool_{pool.pool_id}" in pool_factory.list_all():
1497:            if f"pool_{p}" in pool_factory.list_all():

js-sdk/jumpscale/sals/reservation_chatflow/reservation_chatflow.py
498:        for obj in self.solutions.list_all():
1085:        for name in self.solutions.list_all():
1118:        for name in self.solutions.list_all():

js-sdk/jumpscale/core/identity/__init__.py
177:                for identity in self.list_all():

js-sdk/jumpscale/packages/admin/actors/identity.py
39:        for label in j.core.identity.list_all():

js-sdk/jumpscale/packages/admin/actors/wallet.py
84:        if name in j.clients.stellar.list_all():

js-sdk/jumpscale/packages/admin/actors/admin.py
88:        if identity_instance_name in j.core.identity.list_all():

js-sdk/jumpscale/packages/backup/actors/minio.py
11:        return INSTANCE_NAME in j.tools.restic.list_all()
28:        if INSTANCE_NAME not in j.tools.restic.list_all():

js-sdk/jumpscale/packages/marketplace/package.py
32:        if "demos_wallet" not in j.clients.stellar.list_all():

js-sdk/jumpscale/packages/polls/bottle/polls_bottle.py
27:    for voter_name in all_users.list_all():
40:    for voter_name in all_users.list_all():

js-sdk/jumpscale/packages/polls/package.py
4:        if "polls_receive" not in j.clients.stellar.list_all():

js-sdk/jumpscale/packages/tfgrid_solutions/actors/solutions.py
68:            if f"pool_{pool.pool_id}" in pool_factory.list_all():
109:        if f"pool_{pool_id}" in pool_factory.list_all():
121:        if f"pool_{pool_id}" in pool_factory.list_all():
133:        if f"pool_{pool_id}" in pool_factory.list_all():

js-sdk/jumpscale/packages/threebot_deployer/actors/backup.py
38:            for solution_name in BACKUP_MODEL_FACTORY.list_all():

js-sdk/jumpscale/servers/threebot/threebot.py
666:        for package_name in self.packages.list_all():
ERR: Error opening directory ./js-sdk/apt-btrfs-snapshot-mp-e7s568wq: Permission denied

js-ng/jumpscale/core/base/factory.py
375:                for name in self.list_all():
508:        for name in self.store.list_all():

js-ng/jumpscale/servers/openresty/server.py
41:        for location_name in self.locations.list_all():

js-ng/tests/core/base/test_store_redis.py
52:        for instance in self.factory.list_all():

js-ng/tests/core/base/test_stored_factory.py
421:        for name in self.factory.list_all():
424:        for name in self.wallets_factory.list_all():

tfta-trader/tfta_sales/bottle/orders_history.py
22:    for order_name in order_model.list_all():
33:    for order_name in order_model.list_all():

tfta-trader/tfta_sales/chats/tfta_sales_bot.py
63:        for order_name in order_model.list_all():
103:        for order_name in order_model.list_all():
243:        for order_name in order_model.list_all():
```

**Comment by abom** [comment]
Now package names returned by `list_all` are returned as a copy, it's a different implementation that factories `list_all`.

For factories, I couldn't reproduce the same issue.

**Comment by Pishoy** [comment]
verified

![image](https://user-images.githubusercontent.com/21987477/93450411-3ab74300-f8d6-11ea-8996-b68ea31cc3a6.png)
```
(js-sdk-NQNSzBV5-py3.8) root@tfwallet-prod:/opt/js-sdk# jsng 
JS-NG>                                                                                                                                                                                                      
JS-NG> for package in j.servers.threebot.default.packages.list_all(): 
     2      j.servers.threebot.default.packages.add(path="jumpscale/packages/polls/")                                                                                                                       
2020-09-17 09:01:34.529 | INFO     | jumpscale.clients.stellar.stellar:activate_through_friendbot:239 - account with address GAZ4GEL4GGVXOXRVAZ3G6MPNI6HKKKKMWCGDHCM4PYG5YDFUCT4RBKXE activated and  funded through friendbot
JS-NG>                      

(js-sdk-NQNSzBV5-py3.8) root@tfwallet-prod:/opt/js-sdk# threebot restart
Threebot server Stopped
2020-09-17 09:04:47.806 | INFO     | jumpscale.entry_points.threebot:check_for_bins:34 - ✅ binaries nginx,redis-server,tmux,git required are installed.
2020-09-17 09:04:47.835 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: the configuration file /tmp/tmpv50j7vfe syntax is ok
2020-09-17 09:04:47.835 | DEBUG    | jumpscale.entry_points.three       
                                                                                                        2020-09-17 09:05:44.052 | INFO     | jumpscale.servers.threebot.threebot:start:662 - Reloading nginx
2020-09-17 09:05:44.089 | INFO     | jumpscale.servers.threebot.threebot:start:667 - Threebot is running at http://localhost:80 and https://localhost:443
127.0.0.1 - - [2020-09-17 09:06:56] "GET /authorized HTTP/1.0" 401 960 0.008724
                              
```
![image](https://user-images.githubusercontent.com/21987477/93450355-2b37fa00-f8d6-11ea-916a-512b0df1329e.png)
