### ISSUE TITLE
Unauthorized access: Signature failed for reservations/convert endpoint

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/js-sdk#1123]
To reproduce:
- visit solutions page in admin dashboard OR
- in jsng shell `j.sals.zos._explorer.conversion.initialize()` which calls the endpoint https://explorer.testnet.grid.tf/api/v1//reservations/convert

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/js-ng/js-sdk/jumpscale/clients/explorer/conversion.py", line 24, in initialize
    resp = self._session.get(url, auth=auth, headers=headers)
           │                 │         │             └ {'threebot-id': '413'}
           │                 │         └ <jumpscale.clients.explorer.auth.HTTPSignatureAuth object at 0x7fdd2148abe0>
           │                 └ 'https://explorer.testnet.grid.tf/api/v1//reservations/convert'
           └ <jumpscale.clients.explorer.conversion.Conversion object at 0x7fdd2148ae80>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-8MwJjzMr-py3.6/lib/python3.6/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
           │                   │      └ {'auth': <jumpscale.clients.explorer.auth.HTTPSignatureAuth object at 0x7fdd2148abe0>, 'headers': {'threebot-id': '413'}, 'allow...
           │                   └ 'https://explorer.testnet.grid.tf/api/v1//reservations/convert'
           └ <requests.sessions.Session object at 0x7fdd256ad470>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-8MwJjzMr-py3.6/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
           │         │       └ {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │         └ <PreparedRequest [GET]>
           └ <requests.sessions.Session object at 0x7fdd256ad470>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-8MwJjzMr-py3.6/lib/python3.6/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
    │   │                         │      │    └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
    │   │                         │      └ <Response [401]>
    │   │                         └ {'response': [<function raise_for_status at 0x7fdd230d0ea0>]}
    │   └ <function dispatch_hook at 0x7fdd24c93488>
    └ <Response [401]>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-8MwJjzMr-py3.6/lib/python3.6/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
                 │    │            └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
                 │    └ <Response [401]>
                 └ <function raise_for_status at 0x7fdd230d0ea0>
  File "/root/js-ng/js-sdk/jumpscale/clients/explorer/errors.py", line 23, in raise_for_status
    raise HTTPError(http_error_msg, response=resp)
          │         │                        └ <Response [401]>
          │         └ '401 Client Error: {"error":"unauthorized access: signature verification failed"}\n for url: https://explorer.testnet.grid.tf/ap...
          └ <class 'requests.exceptions.HTTPError'>
requests.exceptions.HTTPError: 401 Client Error: {"error":"unauthorized access: signature verification failed"}
 for url: https://explorer.testnet.grid.tf/api/v1//reservations/convert

401 Client Error: {"error":"unauthorized access: signature verification failed"}
 for url: https://explorer.testnet.grid.tf/api/v1//reservations/convert

```

**Comment by zaibon** [comment]
@ranatrk can you retry using the branch from PR #1124

**Comment by ranatrk** [comment]
> I cannot reproduce it myself.
> 
> Are you sure of the default identity configured in js-sdk ? Make sure you're not trying to reach testnet explorer with a mainnet identity

yes its on testnet



> @ranatrk can you retry using the branch from PR #1124

When switching to this branch:
- From the admin dashboard the error isn't shown
- From the shell when running the previous command it says already converted(Which means it converted successfully with no errors right?):
```
JS-NG> j.sals.zos._explorer.conversion.initialize()                                                 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/js-ng/js-sdk/jumpscale/clients/explorer/conversion.py", line 23, in initialize
    raise AlreadyConvertedError('convertion for user '' has already been done'e.tid} has already been done")
          │                                            └ Identity(
  instance_name='ranatarek_test',
  _tid=413,
  words='snake month once sure control again damp grocery essence future...
          └ <class 'jumpscale.clients.explorer.conversion.AlreadyConvertedError'>
jumpscale.clients.explorer.conversion.AlreadyConvertedError: convertion for user 413 has already been done

convertion for user 413 has already been done
```

**Comment by zaibon** [comment]
> Which means it converted successfully with no?

This is right. This is the expected output and seem thr authentication error is fixed.
Feel free to merge the PR and close this issue

**Comment by ranatrk** [comment]
thanks
