### ISSUE TITLE
Error on deleting a package (dict size changed during iteration)

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#1130]
### Steps to reproduce

- install farmmanagment package from ui
- try to delete it `j.servers.threebot.default.packages.delete("farmmanagement") `

### Traceback/Logs/Alerts

```
  File "/home/waleed/js-sdk/jumpscale/servers/threebot/threebot.py", line 435, in delete
    for actor in self.threebot.gedis._loaded_actors.keys():
        │        │    └ <property object at 0x7effb19a54f0>
        │        └ PackageManager(
        │            instance_name='default',
        │            parent=ThreebotServer(instance_name_='default'),
        │            packages={'auth': {'path': '/...
        └ 'farmmanagement_farm_management'

RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/waleed/js-sdk/jumpscale/servers/threebot/threebot.py", line 435, in delete
    for actor in self.threebot.gedis._loaded_actors.keys():
RuntimeError: dictionary changed size during iteration

dictionary changed size during iteration
```

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 5fe56fe06a4de4534e17128573a5e545ab5dbc97 , **Brnahc** development

![ff](https://user-images.githubusercontent.com/21218053/93015741-3203fb80-f5bc-11ea-86fc-d8414f64a28a.png)
![ff1](https://user-images.githubusercontent.com/21218053/93015745-33352880-f5bc-11ea-9fad-707725aa5f66.png)

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/93016410-44ccff00-f5c1-11ea-9859-9a16ea54b986.png)
