### ISSUE TITLE
js-ng in container setup , 3sdk shell does not start

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#115]
Following this guide for in-container setup [link](https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/container_installation.md)

After building the sdk binary and going to the ```dist``` repo , did ```./3sdk``` and got the following : 

```
(js-ng-Yg2_m37q-py3.6) root@sdk:~/sandbox/code/threefoldtech/js-ng/dist# ./3sdk
Traceback (most recent call last):
  File "jumpscale/entry_points/usershell.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/js-ng-Yg2_m37q-py3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "jumpscale/threesdk/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/js-ng-Yg2_m37q-py3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "jumpscale/threesdk/threebot.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/js-ng-Yg2_m37q-py3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "jumpscale/threesdk/identitymanager.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/js-ng-Yg2_m37q-py3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "jumpscale/god.py", line 228, in <module>
  File "jumpscale/god.py", line 217, in __getattr__
  File "jumpscale/god.py", line 117, in __getattr__
AttributeError: Can't find attr tools
[2666] Failed to execute script usershell
(js-ng-Yg2_m37q-py3.6) root@sdk:~/sandbox/code/threefoldtech/js-ng/dist#
```

![image](https://user-images.githubusercontent.com/25789724/85734133-d4bf8300-b70d-11ea-9acd-c73ec0fb3054.png)

OS : Ubuntu 18.04

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
