### ISSUE TITLE
failed to find resources for this reservation

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1249]
```
020-09-22 13:49:46.803 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method fetch from actor chatflows_chatbot to client ('127.0.0.1', 50970)
2020-09-22 13:49:50.451 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:149 - error
Traceback (most recent call last):

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/reservation_chatflow/reservation_chatflow.py", line 1426, in get_nodes
    node = random.choice(nodes)
           │      │      └ []
           │      └ <bound method Random.choice of <random.Random object at 0x1154260>>
           └ <module 'random' from '/usr/lib/python3.8/random.py'>

  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None

IndexError: Cannot choose from an empty sequence


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 185, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f02c19ecb80>
    └ <marketplace.chats.wiki.WikiDeploy object at 0x7f02b27369a0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 193, in _execute_current_step
    wrapper(step_name)
    │       └ 'configuration'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f02b2760ee0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 185, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f02c19ecb80>
    └ <marketplace.chats.wiki.WikiDeploy object at 0x7f02b27369a0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 193, in _execute_current_step
    wrapper(step_name)
    │       └ 'infrastructure_setup'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f02c0090310>

> File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 146, in wrapper
    getattr(self, step_name)()
            │     └ 'infrastructure_setup'
            └ <marketplace.chats.wiki.WikiDeploy object at 0x7f02b27369a0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 651, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<marketplace.chats.wiki.WikiDeploy object at 0x7f02b27369a0>,)
           └ <function MarketPlaceAppsChatflow.infrastructure_setup at 0x7f02c11a7af0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/marketplace/apps_chatflow.py", line 263, in infrastructure_setup
    self._get_pool()
    │    └ <function MarketPlaceAppsChatflow._get_pool at 0x7f02c11a7700>
    └ <marketplace.chats.wiki.WikiDeploy object at 0x7f02b27369a0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/marketplace/apps_chatflow.py", line 145, in _get_pool
    deployer.init_new_user_network(self, self.solution_metadata["owner"], self.pool_info.reservation_id)
    │        │                     │     │    │                           │    │         └ <property object at 0x7f02c370a7c0>
    │        │                     │     │    │                           │    └ PoolCreated(
    │        │                     │     │    │                           │        reservation_id=28,
    │        │                     │     │    │                           │        escrow_information=PoolEscrow(
    │        │                     │     │    │                           │        address='GCBFSUXSFE6F3PQZFLOD2ONETMJ7G5CLILNWAV7YTPDWDEI...
    │        │                     │     │    │                           └ <marketplace.chats.wiki.WikiDeploy object at 0x7f02b27369a0>
    │        │                     │     │    └ {'owner': 'ahmedthabet.3bot'}
    │        │                     │     └ <marketplace.chats.wiki.WikiDeploy object at 0x7f02b27369a0>
    │        │                     └ <marketplace.chats.wiki.WikiDeploy object at 0x7f02b27369a0>
    │        └ <function MarketPlaceDeployer.init_new_user_network at 0x7f02c11790d0>
    └ <jumpscale.sals.marketplace.deployer.MarketPlaceDeployer object at 0x7f02c1248cd0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/marketplace/deployer.py", line 345, in init_new_user_network
    access_node = j.sals.reservation_chatflow.reservation_chatflow.get_nodes(
                  │ └ <property object at 0x7f02c6bd4e00>
                  └ <jumpscale.loader.J object at 0x7f02c6bcb670>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/reservation_chatflow/reservation_chatflow.py", line 1430, in get_nodes
    raise StopChatFlow(
          └ <class 'jumpscale.sals.chatflows.chatflows.StopChatFlow'>

jumpscale.sals.chatflows.chatflows.StopChatFlow: (StopChatFlow(...), "Failed to find resources for this reservation. If you are using a low resources environment like testnet, please make sure to allow over provisioning from the settings tab in dashboard. For more info visit <a href='https://manual2.threefold.io/#/3bot_settings?id=developers-options'>our manual</a>")
127.0.0.1 - - [2020-09-22 13:49:50] "POST /chatflows/chatbot/fetch HTTP/1.0" 200 750 3.655666
127.0.0.1 - - [2020-09-22 13:49:50] "GET /authenticated HTTP/1.0" 200 222 0.114514

```

**Comment by xmonader** [comment]
also for peertube

```
o client ('127.0.0.1', 44796)
2020-09-22 13:57:49.538 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:149 - error
Traceback (most recent call last):

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/reservation_chatflow/reservation_chatflow.py", line 1426, in get_nodes
    node = random.choice(nodes)
           │      │      └ []
           │      └ <bound method Random.choice of <random.Random object at 0x2795260>>
           └ <module 'random' from '/usr/lib/python3.8/random.py'>

  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None

IndexError: Cannot choose from an empty sequence


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 185, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f3c8e8bad30>
    └ <marketplace.chats.peertube.Peertube object at 0x7f3c8dfdbfd0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 193, in _execute_current_step
    wrapper(step_name)
    │       └ 'volume_details'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f3c8e02b310>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 185, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f3c8e8bad30>
    └ <marketplace.chats.peertube.Peertube object at 0x7f3c8dfdbfd0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 193, in _execute_current_step
    wrapper(step_name)
    │       └ 'payment_currency'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f3c8d75ddc0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 185, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f3c8e8bad30>
    └ <marketplace.chats.peertube.Peertube object at 0x7f3c8dfdbfd0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 193, in _execute_current_step
    wrapper(step_name)
    │       └ 'infrastructure_setup'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f3c8d763700>

> File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 146, in wrapper
    getattr(self, step_name)()
            │     └ 'infrastructure_setup'
            └ <marketplace.chats.peertube.Peertube object at 0x7f3c8dfdbfd0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 651, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<marketplace.chats.peertube.Peertube object at 0x7f3c8dfdbfd0>,)
           └ <function MarketPlaceAppsChatflow.infrastructure_setup at 0x7f3c8e074ca0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/marketplace/apps_chatflow.py", line 263, in infrastructure_setup
    self._get_pool()
    │    └ <function MarketPlaceAppsChatflow._get_pool at 0x7f3c8e0748b0>
    └ <marketplace.chats.peertube.Peertube object at 0x7f3c8dfdbfd0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/marketplace/apps_chatflow.py", line 145, in _get_pool
    deployer.init_new_user_network(self, self.solution_metadata["owner"], self.pool_info.reservation_id)
    │        │                     │     │    │                           │    │         └ <property object at 0x7f3c945ff900>
    │        │                     │     │    │                           │    └ PoolCreated(
    │        │                     │     │    │                           │        reservation_id=30,
    │        │                     │     │    │                           │        escrow_information=PoolEscrow(
    │        │                     │     │    │                           │        address='GCBFSUXSFE6F3PQZFLOD2ONETMJ7G5CLILNWAV7YTPDWDEI...
    │        │                     │     │    │                           └ <marketplace.chats.peertube.Peertube object at 0x7f3c8dfdbfd0>
    │        │                     │     │    └ {'owner': 'ahmedthabet.3bot'}
    │        │                     │     └ <marketplace.chats.peertube.Peertube object at 0x7f3c8dfdbfd0>
    │        │                     └ <marketplace.chats.peertube.Peertube object at 0x7f3c8dfdbfd0>
    │        └ <function MarketPlaceDeployer.init_new_user_network at 0x7f3c8e0b1ca0>
    └ <jumpscale.sals.marketplace.deployer.MarketPlaceDeployer object at 0x7f3c8e106820>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/marketplace/deployer.py", line 345, in init_new_user_network
    access_node = j.sals.reservation_chatflow.reservation_chatflow.get_nodes(
                  │ └ <property object at 0x7f3c97ac0e00>
                  └ <jumpscale.loader.J object at 0x7f3c97ab8640>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/reservation_chatflow/reservation_chatflow.py", line 1430, in get_nodes
    raise StopChatFlow(
          └ <class 'jumpscale.sals.chatflows.chatflows.StopChatFlow'>

jumpscale.sals.chatflows.chatflows.StopChatFlow: (StopChatFlow(...), "Failed to find resources for this reservation. If you are using a low resources environment like testnet, please make sure to allow over provisioning from the settings tab in dashboard. For more info visit <a href='https://manual2.threefold.io/#/3bot_settings?id=developers-options'>our manual</a>")
127.0.0.1 - - [2020-09-22 13:57:49] "POST /chatflows/chatbot/fetch HTTP/1.0" 200 750 3.079738
127.0.0.1 - - [2020-09-22 13:57:49] "GET /authenticated HTTP/1.0" 200 222 0.154708
2020-09-22 13:57:49.717 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method fetch from actor chatflows_chatbot to client ('127.0.0.1', 44796)

```

**Comment by xmonader** [comment]
this one was resolved by compensating for the blocked nodes on the system when asking for extra nodes

**Comment by waleedhammam** [comment]
![Screenshot from 2020-09-27 13-40-17](https://user-images.githubusercontent.com/10658229/94365300-f561f500-00cf-11eb-98fd-7b0eb65ba38c.png)

it'll try another pool if not will create new one

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 40b40ba2abc7dfbd4e82fdfd9e498cc14cc446a1, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96469629-ba199880-122d-11eb-8bc3-37026f6b1c87.png)
