### ISSUE TITLE
error in j.servers.threebot.default.packages.install_all()

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#126]
```
S-NG> j.servers.threebot.default.packages.install_all()                                              
2020-06-28 20:27:19.247 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - AttributeError: 'NoneType' object has no attribute 'load'
Traceback (most recent call last):
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/bin/jsng", line 33, in <module>
    sys.exit(load_entry_point('js-ng', 'console_scripts', 'jsng')())
    │   │    └ <function importlib_load_entry_point at 0x7fc5f677c1f0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/src/js-ng/jumpscale/entry_points/jsng.py", line 22, in run
    sys.exit(embed(globals(), locals(), configure=ptconfig, history_filename=HISTORY_FILENAME))
    │   │    │                                    │                          └ '/home/waleed/.jsng/history.txt'
    │   │    │                                    └ <function ptconfig at 0x7fc5f50b73a0>
    │   │    └ <function embed at 0x7fc5f4f57f70>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 350, in embed
    repl.run()
    │    └ <function PythonRepl.run at 0x7fc5f4f57af0>
    └ <ptpython.repl.PythonRepl object at 0x7fc5f64507f0>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 74, in run
    self._process_text(text)
    │    │             └ 'j.servers.threebot.default.packages.install_all()'
    │    └ <function PythonRepl._process_text at 0x7fc5f4f57b80>
    └ <ptpython.repl.PythonRepl object at 0x7fc5f64507f0>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 88, in _process_text
    self._handle_exception(e)
    │    │                 └ AttributeError("'NoneType' object has no attribute 'load'")
    │    └ functools.partial(<function patched_handle_exception at 0x7fc5f5437e50>, <ptpython.repl.PythonRepl object at 0x7fc5f64507f0>)
    └ <ptpython.repl.PythonRepl object at 0x7fc5f64507f0>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 163, in _execute
    six.exec_(code, self.get_globals(), self.get_locals())
    │   │     │     │    │              │    └ <function embed.<locals>.get_locals at 0x7fc5f4f59040>
    │   │     │     │    │              └ <ptpython.repl.PythonRepl object at 0x7fc5f64507f0>
    │   │     │     │    └ <function embed.<locals>.get_globals at 0x7fc5f65deaf0>
    │   │     │     └ <ptpython.repl.PythonRepl object at 0x7fc5f64507f0>
    │   │     └ <code object <module> at 0x7fc5f10af450, file "<stdin>", line 1>
    │   └ <built-in function exec>
    └ <module 'six' from '/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/six.py'>
> File "<stdin>", line 1, in <module>

  File "/home/waleed/js-sdk/jumpscale/servers/threebot/threebot.py", line 405, in install_all
    self.install(self.get(package))
    │    │       │    │   └ 'polls'
    │    │       │    └ <function PackageManager.get at 0x7fc5f1e6cf70>
    │    │       └ PackageManager(_Base__instance_name='default', _Base__parent=ThreebotServer(_Base__instance_name='default', _Base__parent=Non...
    │    └ <function PackageManager.install at 0x7fc5f1e73280>
    └ PackageManager(_Base__instance_name='default', _Base__parent=ThreebotServer(_Base__instance_name='default', _Base__parent=Non...

  File "/home/waleed/js-sdk/jumpscale/servers/threebot/threebot.py", line 391, in install
    self.threebot.chatbot.load(package.chats_dir)
    │    │                     │       └ <property object at 0x7fc5f1e6aef0>
    │    │                     └ <jumpscale.servers.threebot.threebot.Package object at 0x7fc5f0a458b0>
    │    └ <property object at 0x7fc5f1e72130>
    └ PackageManager(_Base__instance_name='default', _Base__parent=ThreebotServer(_Base__instance_name='default', _Base__parent=Non...

AttributeError: 'NoneType' object has no attribute 'load'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/waleed/js-sdk/jumpscale/servers/threebot/threebot.py", line 405, in install_all
    self.install(self.get(package))
    │            │        └ 'polls'
    │            └ PackageManager(_Base__instance_name='default', _Base__parent=ThreebotServer(_Base__instance_name='default', _Base__parent=None, ...
    └ PackageManager(_Base__instance_name='default', _Base__parent=ThreebotServer(_Base__instance_name='default', _Base__parent=None, ...
  File "/home/waleed/js-sdk/jumpscale/servers/threebot/threebot.py", line 391, in install
    self.threebot.chatbot.load(package.chats_dir)
    │                          └ <jumpscale.servers.threebot.threebot.Package object at 0x7fc5f0a458b0>
    └ PackageManager(_Base__instance_name='default', _Base__parent=ThreebotServer(_Base__instance_name='default', _Base__parent=None, ...
AttributeError: 'NoneType' object has no attribute 'load'

'NoneType' object has no attribute 'load'
```

**Comment by RafyAmgadBenjamin** [comment]
After tracing this issue I have found that the error was raised because Gedis server was not set, I discussed this @ahelsayd  and we figured out that the issue depends on how do you start the Threebot server.
if you just typed
```
poetry shell
threebot start
```
It will start the Threebot server  then 
```
jsng
```
you will get into another shell where the objects including the Gedis server were set in the previous shell so they are no longer valid in this shell which causes install_all() method to crash 

But if we typed 
```
poetry shell
jsng
```
then inside this shell 
```
t = j.servers.threebot.default 
t.start()
```
In this case, the objects and Gedis server will be set correctly so if you called install_all() method it will not crash and it will work correctly.

#### It mainly depends on how do you start the Threebot server and memory context related to the shell to set the objects and Gedis server

### I recommend making this function as an internal method to prevent this from happening again

**Comment by RafyAmgadBenjamin** [comment]
I have discussed this Issue with @abom  and we decided to make this method not public, and we shall no longer call this method directly from the shell instead it shall be called from the code where Gedis server running

**Comment by siddiquagig** [comment]
Tested on latest code , method still exists :

![image](https://user-images.githubusercontent.com/25789724/86530022-257d6b80-bec6-11ea-80da-f64f93f6f1ba.png)

**Comment by abom** [comment]
@siddiquagig As you see the PR https://github.com/threefoldtech/js-sdk/pull/159, It's still on a branch and not merged yet.

**Comment by siddiquagig** [comment]
Verified on both the branches , since merged now

![image](https://user-images.githubusercontent.com/25789724/86531975-266ac900-bed7-11ea-8cd5-4182eda38c04.png)
