### ISSUE TITLE
Creating a new mail client gives an exception

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1310]
### Description
`j.clients.mail.new("testmail")` gives an exception
### Version information

* OS:osx
* project commit/version: 8c36ad9424affcee694202b55aeecae397c9013e/v11.06b

### Steps to reproduce
`j.clients.mail.new("testmail")`

### Traceback/Logs/Alerts
```
JS-NG> j.clients.mail.new("testmail")
2020-09-29 11:20:54.454 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - TypeError: __init__() got an unexpected keyword argument 'instance_name_'
Traceback (most recent call last):
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/bin/jsng", line 11, in <module>
    load_entry_point('js-ng', 'console_scripts', 'jsng')()
    └ <function load_entry_point at 0x10f136940>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x10f9b0160>
           └ <Command run>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x10f2380d0>
         │    └ <function Command.invoke at 0x10f9b0af0>
         └ <Command run>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'command': None}
           │   │      │    │           └ <click.core.Context object at 0x10f2380d0>
           │   │      │    └ <function run at 0x10fa55f70>
           │   │      └ <Command run>
           │   └ <function Context.invoke at 0x10f9acc10>
           └ <click.core.Context object at 0x10f2380d0>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'command': None}
           │         └ ()
           └ <function run at 0x10fa55f70>

  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/src/js-ng/jumpscale/entry_points/jsng.py", line 30, in run
    sys.exit(embed(globals(), locals(), configure=ptconfig, history_filename=HISTORY_FILENAME))
    │   │    │                                    │                          └ '/Users/rob/.jsng/history.txt'
    │   │    │                                    └ <function ptconfig at 0x10fea5280>
    │   │    └ <function embed at 0x110049e50>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 350, in embed
    repl.run()
    │    └ <function PythonRepl.run at 0x1100499d0>
    └ <ptpython.repl.PythonRepl object at 0x10fe8ef10>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 74, in run
    self._process_text(text)
    │    │             └ 'j.clients.mail.new("testmail")'
    │    └ <function PythonRepl._process_text at 0x110049a60>
    └ <ptpython.repl.PythonRepl object at 0x10fe8ef10>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 88, in _process_text
    self._handle_exception(e)
    │    │                 └ TypeError("__init__() got an unexpected keyword argument 'instance_name_'")
    │    └ functools.partial(<function patched_handle_exception at 0x10fb22940>, <ptpython.repl.PythonRepl object at 0x10fe8ef10>)
    └ <ptpython.repl.PythonRepl object at 0x10fe8ef10>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 163, in _execute
    six.exec_(code, self.get_globals(), self.get_locals())
    │   │     │     │    │              │    └ <function embed.<locals>.get_locals at 0x110049ee0>
    │   │     │     │    │              └ <ptpython.repl.PythonRepl object at 0x10fe8ef10>
    │   │     │     │    └ <function embed.<locals>.get_globals at 0x10fb22700>
    │   │     │     └ <ptpython.repl.PythonRepl object at 0x10fe8ef10>
    │   │     └ <code object <module> at 0x1171a42f0, file "<stdin>", line 1>
    │   └ <built-in function exec>
    └ <module 'six' from '/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/six.py'>
> File "<stdin>", line 1, in <module>

  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/src/js-ng/jumpscale/core/base/factory.py", line 469, in new
    instance = super().new(name, *args, **kwargs)
                           │      │       └ {}
                           │      └ ()
                           └ 'testmail'

  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/src/js-ng/jumpscale/core/base/factory.py", line 185, in new
    instance = self._create_instance(name, *args, **kwargs)
               │    │                │      │       └ {}
               │    │                │      └ ()
               │    │                └ 'testmail'
               │    └ <function Factory._create_instance at 0x111a50d30>
               └ <jumpscale.core.base.factory.jumpscaleclientsmailmailMailClient object at 0x11324ff40>

  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/src/js-ng/jumpscale/core/base/factory.py", line 161, in _create_instance
    instance = self.type(*args, **kwargs)
               │    │     │       └ {'instance_name_': 'testmail', 'parent_': None}
               │    │     └ ()
               │    └ <class 'jumpscale.clients.mail.mail.MailClient'>
               └ <jumpscale.core.base.factory.jumpscaleclientsmailmailMailClient object at 0x11324ff40>

TypeError: __init__() got an unexpected keyword argument 'instance_name_'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/src/js-ng/jumpscale/core/base/factory.py", line 469, in new
    instance = super().new(name, *args, **kwargs)
                           │      │       └ {}
                           │      └ ()
                           └ 'testmail'
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/src/js-ng/jumpscale/core/base/factory.py", line 185, in new
    instance = self._create_instance(name, *args, **kwargs)
               │                     │      │       └ {}
               │                     │      └ ()
               │                     └ 'testmail'
               └ <jumpscale.core.base.factory.jumpscaleclientsmailmailMailClient object at 0x11324ff40>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/src/js-ng/jumpscale/core/base/factory.py", line 161, in _create_instance
    instance = self.type(*args, **kwargs)
               │          │       └ {'instance_name_': 'testmail', 'parent_': None}
               │          └ ()
               └ <jumpscale.core.base.factory.jumpscaleclientsmailmailMailClient object at 0x11324ff40>
TypeError: __init__() got an unexpected keyword argument 'instance_name_'

```

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 3de2775b38c60cd448947c3cef10eb41eba58995, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/95990532-ef884580-0e2b-11eb-89e0-4d53894a8dba.png)
