### ISSUE TITLE
Create network example from manual does not work

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#1370]
This example: 
```
# Make sure to set a new port.
for i, node in enumerate(pool.node_ids):
 if zos.nodes_finder.filter_is_up(node):
  iprange = f"172.20.{i+10}.0/24"
  pool_id = 1
  zos.network.add_node(network, node.node_id , iprange, pool_id)
  print("Node number: ", i, node.node_id, ":", iprange)
 else:
  print("Node", node.node_id,"is not up")
```

On the manual: https://manual2.threefold.io/#/code_network

Does not work due to:

```
Traceback (most recent call last):
  File "/home/dylan/.cache/pypoetry/virtualenvs/js-sdk-GbuXkjbe-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 123, in _execute
    code = compile_with_flags(line, 'eval')
    │      │                  └ '# Make sure to set a new port.\nfor i, node in enumerate(pool.node_ids):\n if zos.nodes_finder.filter_is_up(node):\n  iprange =...
    │      └ <function PythonRepl._execute.<locals>.compile_with_flags at 0x7f61291843a0>
    └ <code object <module> at 0x7f612b1a52f0, file "<stdin>", line 2>
  File "/home/dylan/.cache/pypoetry/virtualenvs/js-sdk-GbuXkjbe-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 109, in compile_with_flags
    return compile(code, '<stdin>', mode,
File "<stdin>", line 2
    for i, node in enumerate(pool.node_ids):
    ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/dylan/Projects/js-sdk/jumpscale/sals/zos/node_finder.py", line 23, in filter_is_up
    return node.updated.timestamp() > ago
           │                          └ 1601983686
           └ '2CBouXMr24TfNxxTs2i4ZqHgbpEagV1c14BnnjrZYdr7'
AttributeError: 'str' object has no attribute 'updated'
Traceback (most recent call last):
  File "/home/dylan/.cache/pypoetry/virtualenvs/js-sdk-GbuXkjbe-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 123, in _execute
    code = compile_with_flags(line, 'eval')
    │      │                  └ '# Make sure to set a new port.\nfor i, node in enumerate(pool.node_ids):\n if zos.nodes_finder.filter_is_up(node):\n  iprange =...
    │      └ <function PythonRepl._execute.<locals>.compile_with_flags at 0x7f61291843a0>
    └ <code object <module> at 0x7f612b1a52f0, file "<stdin>", line 2>
  File "/home/dylan/.cache/pypoetry/virtualenvs/js-sdk-GbuXkjbe-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 109, in compile_with_flags
    return compile(code, '<stdin>', mode,
File "<stdin>", line 2
    for i, node in enumerate(pool.node_ids):
    ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/dylan/Projects/js-sdk/jumpscale/sals/zos/node_finder.py", line 23, in filter_is_up
    return node.updated.timestamp() > ago
           │                          └ 1601983686
           └ '2CBouXMr24TfNxxTs2i4ZqHgbpEagV1c14BnnjrZYdr7'
AttributeError: 'str' object has no attribute 'updated'

'str' object has no attribute 'updated'

```

**Comment by DylanVerstraete** [comment]
https://github.com/threefoldfoundation/info_gridmanual/pull/277/files
