### ISSUE TITLE
Threebot stop gives timeout and other errors

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#141]
I have the latest code on js-sdk repo .

When i try ```threebot stop``` , i get this error :

```
(js-sdk-vpmH-Z_5-py3.6) root@sdk:~/js-sdk# threebot stop
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/bin/threebot", line 11, in <module>
    load_entry_point('js-sdk', 'console_scripts', 'threebot')()
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/js-sdk/jumpscale/entry_points/threebot.py", line 89, in stop
    threebot_cmd.stop()
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/src/js-ng/jumpscale/tools/startupcmd/startupcmd.py", line 204, in stop
    self.wait_for_stop(die=die, timeout=timeout)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/src/js-ng/jumpscale/tools/startupcmd/startupcmd.py", line 253, in wait_for_stop
    self._wait(False, die, timeout)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/src/js-ng/jumpscale/tools/startupcmd/startupcmd.py", line 241, in _wait
    raise j.exceptions.Timeout(f"Wait operation exceeded timeout: {timeout}")
jumpscale.core.exceptions.exceptions.Timeout: Wait operation exceeded timeout: 60
```

```
(js-sdk-vpmH-Z_5-py3.6) root@sdk:~/js-sdk# git log -2
commit 863e736bbe480f6d15a327634e7925011a1816a8 (HEAD -> development, origin/development, origin/HEAD)
Merge: e42eaba 5870b31
Author: Jo De Boeck <deboeck.jo@gmail.com>
Date:   Tue Jun 30 11:56:25 2020 +0200

    Merge pull request #139 from threefoldtech/development_nginx

    Improvements in starting/stopping nginx for threebot

commit 5870b31fd8b357b21e317eb0e9cdd502b50daf4d
Author: Jo De Boeck <deboeck.jo@gmail.com>
Date:   Tue Jun 30 11:54:51 2020 +0200

    Improvements in starting/stopping nginx for threebot

    Signed-off-by: Jo De Boeck <deboeck.jo@gmail.com>
```

**Comment by grimpy** [comment]
@siddiquagig please attach result of
`ps -eaf | grep nginx`
after reproducing the error above


Also what are the "other errors" you are referring to in the title?

**Comment by siddiquagig** [comment]
Ok just the timeout error then

Result of ```ps -eaf | grep nginx```

![image](https://user-images.githubusercontent.com/25789724/86117443-1b332a00-bae0-11ea-948e-90a8bc4814cd.png)

**Comment by alichaddad** [comment]
Issue can't be reproduced `stop` command works as expected, can you please pull latest and try again @siddiquagig ?

**Comment by siddiquagig** [comment]
Works now

![image](https://user-images.githubusercontent.com/25789724/86593921-2d610c80-bfa7-11ea-90ad-0cfa252a9d01.png)
