### ISSUE TITLE
Can't create mainnet wallet from dashboard

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#1425]
When I create a new wallet with any name on locally hosted 3Bot while logged in with a mainnet identity, I get this error:
```
{ "type": "https://stellar.org/horizon-errors/not_found", "title": "Resource Missing", "status": 404, "detail": "The resource at the url requested was not found. This usually occurs for one of two reasons: The url requested is not valid, or no data in our database could be found with the parameters provided." }
```

**Comment by waleedhammam** [comment]
```
JS-NG> bb = j.clients.stellar.new("hamada")                                                                                                                                                                   
JS-NG> bb.activate_through_threefold_service()                                                                                                                                                                
JS-NG> bb.add_known_trustline("TFT")                                                                                                                                                                          
2020-10-13 23:29:27.266 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - stellar_sdk.exceptions.NotFoundError: {
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}
Traceback (most recent call last):
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/bin/jsng", line 8, in <module>
    sys.exit(run())
    │   │    └ <Command run>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fa929d2d820>
           └ <Command run>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fa92a2a6280>
         │    └ <function Command.invoke at 0x7fa929d2f1f0>
         └ <Command run>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'command': None}
           │   │      │    │           └ <click.core.Context object at 0x7fa92a2a6280>
           │   │      │    └ <function run at 0x7fa929d56820>
           │   │      └ <Command run>
           │   └ <function Context.invoke at 0x7fa929d2d310>
           └ <click.core.Context object at 0x7fa92a2a6280>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'command': None}
           │         └ ()
           └ <function run at 0x7fa929d56820>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/jumpscale/entry_points/jsng.py", line 30, in run
    sys.exit(embed(globals(), locals(), configure=ptconfig, history_filename=HISTORY_FILENAME))
    │   │    │                                    │                          └ '/home/waleed/.jsng/history.txt'
    │   │    │                                    └ <function ptconfig at 0x7fa9292453a0>
    │   │    └ <function embed at 0x7fa92907b160>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 350, in embed
    repl.run()
    │    └ <function PythonRepl.run at 0x7fa9290f8ca0>
    └ <ptpython.repl.PythonRepl object at 0x7fa929243880>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 74, in run
    self._process_text(text)
    │    │             └ 'bb.add_known_trustline("TFT")'
    │    └ <function PythonRepl._process_text at 0x7fa9290f8d30>
    └ <ptpython.repl.PythonRepl object at 0x7fa929243880>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 88, in _process_text
    self._handle_exception(e)
    │    │                 └ NotFoundError(<stellar_sdk.client.response.Response object at 0x7fa91bd52430>)
    │    └ functools.partial(<function patched_handle_exception at 0x7fa9295ca040>, <ptpython.repl.PythonRepl object at 0x7fa929243880>)
    └ <ptpython.repl.PythonRepl object at 0x7fa929243880>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 163, in _execute
    six.exec_(code, self.get_globals(), self.get_locals())
    │   │     │     │    │              │    └ <function embed.<locals>.get_locals at 0x7fa92907b1f0>
    │   │     │     │    │              └ <ptpython.repl.PythonRepl object at 0x7fa929243880>
    │   │     │     │    └ <function embed.<locals>.get_globals at 0x7fa929cd5e50>
    │   │     │     └ <ptpython.repl.PythonRepl object at 0x7fa929243880>
    │   │     └ <code object <module> at 0x7fa9092c2b30, file "<stdin>", line 1>
    │   └ <built-in function exec>
    └ <module 'six' from '/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/six.py'>
> File "<stdin>", line 1, in <module>

  File "/home/waleed/js-sdk/jumpscale/clients/stellar/stellar.py", line 296, in add_known_trustline
    self._change_trustline(asset_code, issuer)
    │    │                 │           └ 'GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47'
    │    │                 └ 'TFT'
    │    └ <function Stellar._change_trustline at 0x7fa9250c25e0>
    └ Stellar(
        instance_name='hamada',
        network=<Network.STD: 'STD'>,
        address='GD7FKBIJ5P5F2AE4RETHUUMD2UVVIHMPWQ64S6LLUXRKEKV...

  File "/home/waleed/js-sdk/jumpscale/clients/stellar/stellar.py", line 323, in _change_trustline
    source_account = server.load_account(source_public_key)
                     │      │            └ 'GD7FKBIJ5P5F2AE4RETHUUMD2UVVIHMPWQ64S6LLUXRKEKVQVVWPVLLS'
                     │      └ <function Server.load_account at 0x7fa925838ee0>
                     └ <jumpscale.clients.stellar.wrapped.Server object at 0x7fa91c0e3730>

  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/stellar_sdk/server.py", line 395, in load_account
    return self.__load_account_sync(account)
           │                        └ <stellar_sdk.muxed_account.MuxedAccount object at 0x7fa91ce0e490>
           └ <jumpscale.clients.stellar.wrapped.Server object at 0x7fa91c0e3730>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/stellar_sdk/server.py", line 411, in __load_account_sync
    resp = self.accounts().account_id(account_id=account_id.account_id).call()
           │    │                     │          │          └ 'GD7FKBIJ5P5F2AE4RETHUUMD2UVVIHMPWQ64S6LLUXRKEKVQVVWPVLLS'
           │    │                     │          └ <stellar_sdk.muxed_account.MuxedAccount object at 0x7fa91ce0e490>
           │    │                     └ <stellar_sdk.muxed_account.MuxedAccount object at 0x7fa91ce0e490>
           │    └ <function Server.accounts at 0x7fa9258385e0>
           └ <jumpscale.clients.stellar.wrapped.Server object at 0x7fa91c0e3730>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 58, in call
    return self.__call(url, self.params)
           │           │    │    └ {}
           │           │    └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7fa91bd84400>
           │           └ 'https://horizon.stellar.org/accounts/GD7FKBIJ5P5F2AE4RETHUUMD2UVVIHMPWQ64S6LLUXRKEKVQVVWPVLLS'
           └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7fa91bd84400>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 64, in __call
    return self.__call_sync(url, params)
           │                │    └ {}
           │                └ 'https://horizon.stellar.org/accounts/GD7FKBIJ5P5F2AE4RETHUUMD2UVVIHMPWQ64S6LLUXRKEKVQVVWPVLLS'
           └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7fa91bd84400>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 68, in __call_sync
    raise_request_exception(raw_resp)
    │                       └ <stellar_sdk.client.response.Response object at 0x7fa91bd52430>
    └ <function raise_request_exception at 0x7fa9259aedc0>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/stellar_sdk/exceptions.py", line 200, in raise_request_exception
    raise NotFoundError(response)
          │             └ <stellar_sdk.client.response.Response object at 0x7fa91bd52430>
          └ <class 'stellar_sdk.exceptions.NotFoundError'>

stellar_sdk.exceptions.NotFoundError: {
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/waleed/js-sdk/jumpscale/clients/stellar/stellar.py", line 296, in add_known_trustline
    self._change_trustline(asset_code, issuer)
    │                      │           └ 'GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47'
    │                      └ 'TFT'
    └ Stellar(
  instance_name='hamada',
  network=<Network.STD: 'STD'>,
  address='GD7FKBIJ5P5F2AE4RETHUUMD2UVVIHMPWQ64S6LLUXRKEKVQVV...
  File "/home/waleed/js-sdk/jumpscale/clients/stellar/stellar.py", line 323, in _change_trustline
    source_account = server.load_account(source_public_key)
                     │                   └ 'GD7FKBIJ5P5F2AE4RETHUUMD2UVVIHMPWQ64S6LLUXRKEKVQVVWPVLLS'
                     └ <jumpscale.clients.stellar.wrapped.Server object at 0x7fa91c0e3730>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/stellar_sdk/server.py", line 395, in load_account
    return self.__load_account_sync(account)
           │                        └ <stellar_sdk.muxed_account.MuxedAccount object at 0x7fa91ce0e490>
           └ <jumpscale.clients.stellar.wrapped.Server object at 0x7fa91c0e3730>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/stellar_sdk/server.py", line 411, in __load_account_sync
    resp = self.accounts().account_id(account_id=account_id.account_id).call()
           │                                     └ <stellar_sdk.muxed_account.MuxedAccount object at 0x7fa91ce0e490>
           └ <jumpscale.clients.stellar.wrapped.Server object at 0x7fa91c0e3730>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 58, in call
    return self.__call(url, self.params)
           │           │    └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7fa91bd84400>
           │           └ 'https://horizon.stellar.org/accounts/GD7FKBIJ5P5F2AE4RETHUUMD2UVVIHMPWQ64S6LLUXRKEKVQVVWPVLLS'
           └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7fa91bd84400>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 64, in __call
    return self.__call_sync(url, params)
           │                │    └ {}
           │                └ 'https://horizon.stellar.org/accounts/GD7FKBIJ5P5F2AE4RETHUUMD2UVVIHMPWQ64S6LLUXRKEKVQVVWPVLLS'
           └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7fa91bd84400>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 68, in __call_sync
    raise_request_exception(raw_resp)
    │                       └ <stellar_sdk.client.response.Response object at 0x7fa91bd52430>
    └ <function raise_request_exception at 0x7fa9259aedc0>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/stellar_sdk/exceptions.py", line 200, in raise_request_exception
    raise NotFoundError(response)
          │             └ <stellar_sdk.client.response.Response object at 0x7fa91bd52430>
          └ <class 'stellar_sdk.exceptions.NotFoundError'>
stellar_sdk.exceptions.NotFoundError: {
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}

{
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}
JS-NG>  
```

**Comment by waleedhammam** [comment]
@robvanmieghem any idea ?

**Comment by robvanmieghem** [comment]
https://github.com/threefoldfoundation/tft-stellar/issues/209

**Comment by robvanmieghem** [comment]
I wouldn't be a bad idea if `activate_through_threefold_service()` would already raise an exception

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 20f8b701e75a953b1c304d6afff79a1a92fa5d23, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96609804-3332f180-12fb-11eb-9d00-476108e10c98.png)

![ff](https://user-images.githubusercontent.com/21218053/96610344-d08e2580-12fb-11eb-9574-eb432cea8f50.png)

![ff1](https://user-images.githubusercontent.com/21218053/96610438-eb609a00-12fb-11eb-937d-42de21894c37.png)

![ff2](https://user-images.githubusercontent.com/21218053/96611198-b739a900-12fc-11eb-9f01-a78987cdb007.png)

**Comment by xmonader** [comment]
https://github.com/threefoldtech/js-sdk/issues/1511
