### ISSUE TITLE
error starting threebot in a local installation

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1502]
### Description

When starting a local threebot it fails to configure the backup package and can not start

### Version information
* OS: osx
* project commit/version: e.g. js-sdk 11.0-b9 ( current master branch)
### Steps to reproduce
j.servers.threebot.default.start()

### Traceback/Logs/Alerts
2020-10-23 09:23:11.659 | INFO     | jumpscale.servers.threebot.threebot:start:723 - Configuring package backup
2020-10-23 09:23:12.265 | INFO     | jumpscale.core.application.application:stop:26 - Application threebot_default is stopped
2020-10-23 09:23:12.968 | INFO     | jumpscale.servers.gedis.server:stop:217 - Shutting down...
2020-10-23 09:23:13.987 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - jumpscale.core.exceptions.exceptions.Runtime: Error happened during getting or installing backup package, the detailed error is 'NoneType' object has no attribute 'path'
Traceback (most recent call last):
```
  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/servers/threebot/threebot.py", line 726, in start
    self.packages.install(package)
    │    │                └ None
    │    └ <property object at 0x104d90630>
    └ ThreebotServer(
        instance_name='default',
        _package_manager=StoredFactory(PackageManager),
        domain=None,
        email=None
      )

  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/servers/threebot/threebot.py", line 504, in install
    sys.path.append(package.path + "/../")  # TODO to be changed
    │   │    │      └ None
    │   │    └ <method 'append' of 'list' objects>
    │   └ ['', '/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/bin', '/usr/local/Cellar/python@3.8/3.8.6/Framewor...
    └ <module 'sys' (built-in)>

AttributeError: 'NoneType' object has no attribute 'path'


The above exception was the direct cause of the following exception:


Traceback (most recent call last):
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/bin/jsng", line 8, in <module>
    sys.exit(run())
    │   │    └ <Command run>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x10317f700>
           └ <Command run>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x102ca2c40>
         │    └ <function Command.invoke at 0x1031800d0>
         └ <Command run>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'command': None}
           │   │      │    │           └ <click.core.Context object at 0x102ca2c40>
           │   │      │    └ <function run at 0x1032d4ca0>
           │   │      └ <Command run>
           │   └ <function Context.invoke at 0x10317f1f0>
           └ <click.core.Context object at 0x102ca2c40>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'command': None}
           │         └ ()
           └ <function run at 0x1032d4ca0>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/jumpscale/entry_points/jsng.py", line 30, in run
    sys.exit(embed(globals(), locals(), configure=ptconfig, history_filename=HISTORY_FILENAME))
    │   │    │                                    │                          └ '/Users/rob/.jsng/history.txt'
    │   │    │                                    └ <function ptconfig at 0x103677dc0>
    │   │    └ <function embed at 0x103836b80>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 350, in embed
    repl.run()
    │    └ <function PythonRepl.run at 0x103836700>
    └ <ptpython.repl.PythonRepl object at 0x103676a00>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 74, in run
    self._process_text(text)
    │    │             └ 'j.servers.threebot.start_default()'
    │    └ <function PythonRepl._process_text at 0x103836790>
    └ <ptpython.repl.PythonRepl object at 0x103676a00>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 88, in _process_text
    self._handle_exception(e)
    │    │                 └ Runtime("Error happened during getting or installing backup package, the detailed error is 'NoneType' object has no attribute...
    │    └ functools.partial(<function patched_handle_exception at 0x1032dc9d0>, <ptpython.repl.PythonRepl object at 0x103676a00>)
    └ <ptpython.repl.PythonRepl object at 0x103676a00>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 163, in _execute
    six.exec_(code, self.get_globals(), self.get_locals())
    │   │     │     │    │              │    └ <function embed.<locals>.get_locals at 0x103836c10>
    │   │     │     │    │              └ <ptpython.repl.PythonRepl object at 0x103676a00>
    │   │     │     │    └ <function embed.<locals>.get_globals at 0x1032dc820>
    │   │     │     └ <ptpython.repl.PythonRepl object at 0x103676a00>
    │   │     └ <code object <module> at 0x10737d710, file "<stdin>", line 1>
    │   └ <built-in function exec>
    └ <module 'six' from '/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/six.py'>
> File "<stdin>", line 1, in <module>

  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/servers/threebot/__init__.py", line 32, in start_default
    server.start(wait=wait)
    │      │     │    └ False
    │      │     └ False
    │      └ <function ThreebotServer.start at 0x104d92550>
    └ ThreebotServer(
        instance_name='default',
        _package_manager=StoredFactory(PackageManager),
        domain=None,
        email=None
      )

  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/servers/threebot/threebot.py", line 729, in start
    raise j.core.exceptions.Runtime(
          │ └ <property object at 0x10319cef0>
          └ <jumpscale.loader.J object at 0x10318b340>

jumpscale.core.exceptions.exceptions.Runtime: Error happened during getting or installing backup package, the detailed error is 'NoneType' object has no attribute 'path'
Traceback (most recent call last):
  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/servers/threebot/threebot.py", line 726, in start
    self.packages.install(package)
    │                     └ None
    └ ThreebotServer(
  instance_name='default',
  _package_manager=StoredFactory(PackageManager),
  domain=None,
  email=None
)
  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/servers/threebot/threebot.py", line 504, in install
    sys.path.append(package.path + "/../")  # TODO to be changed
    │               └ None
    └ <module 'sys' (built-in)>
AttributeError: 'NoneType' object has no attribute 'path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/servers/threebot/__init__.py", line 32, in start_default
    server.start(wait=wait)
    │                 └ False
    └ ThreebotServer(
  instance_name='default',
  _package_manager=StoredFactory(PackageManager),
  domain=None,
  email=None
)
  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/servers/threebot/threebot.py", line 729, in start
    raise j.core.exceptions.Runtime(
jumpscale.core.exceptions.exceptions.Runtime: Error happened during getting or installing backup package, the detailed error is 'NoneType' object has no attribute 'path'

Error happened during getting or installing backup package, the detailed error is 'NoneType' object has no attribute 'path'
```

**Comment by robvanmieghem** [comment]
I removed the 'default' threebot after which it succeeded. How are existing threebots updated?
