### ISSUE TITLE
AttributeError: 'JumpscaleServersRack' object has no attribute 'add' when starting 3bot server

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1555]
```

(.venv) ➜  js-sdk git:(development) poetry run threebot start --local
2020-10-28 23:13:03.204 | INFO     | jumpscale.entry_points.threebot:check_for_bins:34 - ✅ binaries nginx,redis-server,tmux,git required are installed.
2020-10-28 23:13:03.255 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2020-10-28 23:13:03.255 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: the configuration file /tmp/tmpjk0poix_ syntax is ok
2020-10-28 23:13:03.255 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: configuration file /tmp/tmpjk0poix_ test is successful
2020-10-28 23:13:03.359 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - AttributeError: 'JumpscaleServersRack' object has no attribute 'add'
Traceback (most recent call last):
> File "<string>", line 1, in <module>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fd282d37940>
           └ <Group cli>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fd28403fd00>
         │    └ <function MultiCommand.invoke at 0x7fd282d38700>
         └ <Group cli>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fd283f200a0>
           │               │       │       └ <function Command.invoke at 0x7fd282d38310>
           │               │       └ <Command start>
           │               └ <click.core.Context object at 0x7fd283f200a0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fd284030310>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'local': True, 'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False}
           │   │      │    │           └ <click.core.Context object at 0x7fd283f200a0>
           │   │      │    └ <function start at 0x7fd2806f3940>
           │   │      └ <Command start>
           │   └ <function Context.invoke at 0x7fd282d37430>
           └ <click.core.Context object at 0x7fd283f200a0>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'local': True, 'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False}
           │         └ ()
           └ <function start at 0x7fd2806f3940>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/entry_points/threebot.py", line 156, in start
    j.servers.threebot.start_default(wait=True, local=local, domain=domain, email=email)
    │ │                                         │     │      │      │       │     └ None
    │ │                                         │     │      │      │       └ None
    │ │                                         │     │      │      └ None
    │ │                                         │     │      └ None
    │ │                                         │     └ True
    │ │                                         └ True
    │ └ <property object at 0x7fd282d3d810>
    └ <jumpscale.loader.J object at 0x7fd282daeac0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/servers/threebot/__init__.py", line 27, in start_default
    server = self.get("default")
             │    └ <function ThreebotServerFactory.get at 0x7fd27fa3d940>
             └ ThreebotServerFactory(ThreebotServer)

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/servers/threebot/__init__.py", line 23, in get
    return super().get("default", *args, **kwargs)
                                   │       └ {}
                                   └ ()

  File "/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/core/base/factory.py", line 206, in get
    instance = self.find(name)
               │    │    └ 'default'
               │    └ <function StoredFactory.find at 0x7fd280d5d430>
               └ ThreebotServerFactory(ThreebotServer)

  File "/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/core/base/factory.py", line 448, in find
    instance = self._load_from_store(name)
    │          │    │                └ 'default'
    │          │    └ <function StoredFactory._load_from_store at 0x7fd280d5d3a0>
    │          └ ThreebotServerFactory(ThreebotServer)
    └ None

  File "/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/core/base/factory.py", line 422, in _load_from_store
    instance = self._get_object_from_config(name, instance_config)
               │    │                       │     └ {'domain': None, 'email': None}
               │    │                       └ 'default'
               │    └ <function StoredFactory._get_object_from_config at 0x7fd280d5d310>
               └ ThreebotServerFactory(ThreebotServer)

  File "/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/core/base/factory.py", line 404, in _get_object_from_config
    instance = self._create_instance(name, **data)
               │    │                │       └ {'domain': None, 'email': None}
               │    │                └ 'default'
               │    └ <function Factory._create_instance at 0x7fd280d58820>
               └ ThreebotServerFactory(ThreebotServer)

  File "/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/core/base/factory.py", line 161, in _create_instance
    instance = self.type(*args, **kwargs)
               │    │     │       └ {'domain': None, 'email': None, 'instance_name_': 'default', 'parent_': None}
               │    │     └ ()
               │    └ <class 'jumpscale.servers.threebot.threebot.ThreebotServer'>
               └ ThreebotServerFactory(ThreebotServer)

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/servers/threebot/threebot.py", line 644, in __init__
    self.rack.add(GEDIS, self.gedis)
    │    │        │      │    └ <property object at 0x7fd27fa08040>
    │    │        │      └ ThreebotServer(
    │    │        │          instance_name='default',
    │    │        │          _package_manager=StoredFactory(PackageManager),
    │    │        │          domain=None,
    │    │        │          email=None
    │    │        │        )
    │    │        └ 'gedis'
    │    └ <property object at 0x7fd27fa00f90>
    └ ThreebotServer(
        instance_name='default',
        _package_manager=StoredFactory(PackageManager),
        domain=None,
        email=None
      )

AttributeError: 'JumpscaleServersRack' object has no attribute 'add'
```

**Comment by xmonader** [comment]
Was because of left overs of branch development_ngmove
