### ISSUE TITLE
 Confirming new identity raised exception 

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#161]
```
JS-NG> j.core.identity.new("ayoub","ayoubm.3bot","dmahmouayoub@gmail.com","kingdom scrub volcano seat 
     1 fluid deal fix flag dial table exotic slush meat blade firm jeans bicycle modify half cost lone
...    ly cushion pupil pigeon")                                                                      
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mahmoud/Documents/js-next/js-sdk/jumpscale/core/identity/__init__.py", line 146, in new
    name, tname=tname, email=email, words=words, explorer_url=explorer_url, _tid=tid, admins=admins
    │     │     │      │     │      │     │      │            │                  │    │      └ None
    │     │     │      │     │      │     │      │            │                  │    └ None
    │     │     │      │     │      │     │      │            │                  └ -1
    │     │     │      │     │      │     │      │            └ None
    │     │     │      │     │      │     │      └ None
    │     │     │      │     │      │     └ 'kingdom scrub volcano seat fluid deal fix flag dial table exotic slush meat blade firm jeans bicycle modify half cost lonely cu...
    │     │     │      │     │      └ 'kingdom scrub volcano seat fluid deal fix flag dial table exotic slush meat blade firm jeans bicycle modify half cost lonely cu...
    │     │     │      │     └ 'dmahmouayoub@gmail.com'
    │     │     │      └ 'dmahmouayoub@gmail.com'
    │     │     └ 'ayoubm.3bot'
    │     └ 'ayoubm.3bot'
    └ 'ayoub'
  File "/home/mahmoud/.cache/pypoetry/virtualenvs/js-sdk-LPK7RVwh-py3.6/src/js-ng/jumpscale/core/base/factory.py", line 466, in new
    instance = super().new(name, *args, **kwargs)
                           │      │       └ {'tname': 'ayoubm.3bot', 'email': 'dmahmouayoub@gmail.com', 'words': 'kingdom scrub volcano seat fluid deal fix flag dial table ...
                           │      └ ()
                           └ 'ayoub'
  File "/home/mahmoud/.cache/pypoetry/virtualenvs/js-sdk-LPK7RVwh-py3.6/src/js-ng/jumpscale/core/base/factory.py", line 182, in new
    instance = self._create_instance(name, *args, **kwargs)
               │                     │      │       └ {'tname': 'ayoubm.3bot', 'email': 'dmahmouayoub@gmail.com', 'words': 'kingdom scrub volcano seat fluid deal fix flag dial table ...
               │                     │      └ ()
               │                     └ 'ayoub'
               └ <jumpscale.core.base.factory.jumpscalecoreidentityIdentity object at 0x7f8d7a50e6d8>
  File "/home/mahmoud/.cache/pypoetry/virtualenvs/js-sdk-LPK7RVwh-py3.6/src/js-ng/jumpscale/core/base/factory.py", line 158, in _create_instance
    instance = self.type(*args, **kwargs)
               │          │       └ {'tname': 'ayoubm.3bot', 'email': 'dmahmouayoub@gmail.com', 'words': 'kingdom scrub volcano seat fluid deal fix flag dial table ...
               │          └ ()
               └ <jumpscale.core.base.factory.jumpscalecoreidentityIdentity object at 0x7f8d7a50e6d8>
  File "/home/mahmoud/Documents/js-next/js-sdk/jumpscale/core/identity/__init__.py", line 42, in __init__
    tname=tname, email=email, words=words, explorer_url=explorer_url, _tid=_tid, admins=admins, *args, **kwargs
  File "/home/mahmoud/.cache/pypoetry/virtualenvs/js-sdk-LPK7RVwh-py3.6/src/js-ng/jumpscale/core/base/meta.py", line 257, in __init__
    self._set_data(values)
    │              └ {'tname': 'ayoubm.3bot', 'email': 'dmahmouayoub@gmail.com', 'words': 'kingdom scrub volcano seat fluid deal fix flag dial table ...
    └ Identity(_Base__instance_name='ayoub', _Base__parent=None, __email='dmahmouayoub@gmail.com', __explorer_url=None, __tname='ayoub...
  File "/home/mahmoud/.cache/pypoetry/virtualenvs/js-sdk-LPK7RVwh-py3.6/src/js-ng/jumpscale/core/base/meta.py", line 343, in _set_data
    setattr(self, name, value)
            │     │     └ None
            │     └ 'explorer_url'
            └ Identity(_Base__instance_name='ayoub', _Base__parent=None, __email='dmahmouayoub@gmail.com', __explorer_url=None, __tname='ayoub...
  File "/home/mahmoud/.cache/pypoetry/virtualenvs/js-sdk-LPK7RVwh-py3.6/src/js-ng/jumpscale/core/base/meta.py", line 160, in setter
    field.on_update(self, value)
    │               │     └ None
    │               └ Identity(_Base__instance_name='ayoub', _Base__parent=None, __email='dmahmouayoub@gmail.com', __explorer_url=None, __tname='ayoub...
    └ <jumpscale.core.base.fields.String object at 0x7f8d781ae828>
  File "/home/mahmoud/Documents/js-next/js-sdk/jumpscale/core/identity/__init__.py", line 15, in _explorer_url_update
    if self._explorer and self._explorer.url != value:
AttributeError: 'Identity' object has no attribute '_explorer'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mahmoud/Documents/js-next/js-sdk/jumpscale/core/identity/__init__.py", line 146, in new
    name, tname=tname, email=email, words=words, explorer_url=explorer_url, _tid=tid, admins=admins
    │     │     │      │     │      │     │      │            │                  │    │      └ None
    │     │     │      │     │      │     │      │            │                  │    └ None
    │     │     │      │     │      │     │      │            │                  └ -1
    │     │     │      │     │      │     │      │            └ None
    │     │     │      │     │      │     │      └ None
    │     │     │      │     │      │     └ 'kingdom scrub volcano seat fluid deal fix flag dial table exotic slush meat blade firm jeans bicycle modify half cost lonely cu...
    │     │     │      │     │      └ 'kingdom scrub volcano seat fluid deal fix flag dial table exotic slush meat blade firm jeans bicycle modify half cost lonely cu...
    │     │     │      │     └ 'dmahmouayoub@gmail.com'
    │     │     │      └ 'dmahmouayoub@gmail.com'
    │     │     └ 'ayoubm.3bot'
    │     └ 'ayoubm.3bot'
    └ 'ayoub'
  File "/home/mahmoud/.cache/pypoetry/virtualenvs/js-sdk-LPK7RVwh-py3.6/src/js-ng/jumpscale/core/base/factory.py", line 466, in new
    instance = super().new(name, *args, **kwargs)
                           │      │       └ {'tname': 'ayoubm.3bot', 'email': 'dmahmouayoub@gmail.com', 'words': 'kingdom scrub volcano seat fluid deal fix flag dial table ...
                           │      └ ()
                           └ 'ayoub'
  File "/home/mahmoud/.cache/pypoetry/virtualenvs/js-sdk-LPK7RVwh-py3.6/src/js-ng/jumpscale/core/base/factory.py", line 182, in new
    instance = self._create_instance(name, *args, **kwargs)
               │                     │      │       └ {'tname': 'ayoubm.3bot', 'email': 'dmahmouayoub@gmail.com', 'words': 'kingdom scrub volcano seat fluid deal fix flag dial table ...
               │                     │      └ ()
               │                     └ 'ayoub'
               └ <jumpscale.core.base.factory.jumpscalecoreidentityIdentity object at 0x7f8d7a50e6d8>
  File "/home/mahmoud/.cache/pypoetry/virtualenvs/js-sdk-LPK7RVwh-py3.6/src/js-ng/jumpscale/core/base/factory.py", line 158, in _create_instance
    instance = self.type(*args, **kwargs)
               │          │       └ {'tname': 'ayoubm.3bot', 'email': 'dmahmouayoub@gmail.com', 'words': 'kingdom scrub volcano seat fluid deal fix flag dial table ...
               │          └ ()
               └ <jumpscale.core.base.factory.jumpscalecoreidentityIdentity object at 0x7f8d7a50e6d8>
  File "/home/mahmoud/Documents/js-next/js-sdk/jumpscale/core/identity/__init__.py", line 42, in __init__
    tname=tname, email=email, words=words, explorer_url=explorer_url, _tid=_tid, admins=admins, *args, **kwargs
  File "/home/mahmoud/.cache/pypoetry/virtualenvs/js-sdk-LPK7RVwh-py3.6/src/js-ng/jumpscale/core/base/meta.py", line 257, in __init__
    self._set_data(values)
    │              └ {'tname': 'ayoubm.3bot', 'email': 'dmahmouayoub@gmail.com', 'words': 'kingdom scrub volcano seat fluid deal fix flag dial table ...
    └ Identity(_Base__instance_name='ayoub', _Base__parent=None, __email='dmahmouayoub@gmail.com', __explorer_url=None, __tname='ayoub...
  File "/home/mahmoud/.cache/pypoetry/virtualenvs/js-sdk-LPK7RVwh-py3.6/src/js-ng/jumpscale/core/base/meta.py", line 343, in _set_data
    setattr(self, name, value)
            │     │     └ None
            │     └ 'explorer_url'
            └ Identity(_Base__instance_name='ayoub', _Base__parent=None, __email='dmahmouayoub@gmail.com', __explorer_url=None, __tname='ayoub...
  File "/home/mahmoud/.cache/pypoetry/virtualenvs/js-sdk-LPK7RVwh-py3.6/src/js-ng/jumpscale/core/base/meta.py", line 160, in setter
    field.on_update(self, value)
    │               │     └ None
    │               └ Identity(_Base__instance_name='ayoub', _Base__parent=None, __email='dmahmouayoub@gmail.com', __explorer_url=None, __tname='ayoub...
    └ <jumpscale.core.base.fields.String object at 0x7f8d781ae828>
  File "/home/mahmoud/Documents/js-next/js-sdk/jumpscale/core/identity/__init__.py", line 15, in _explorer_url_update
    if self._explorer and self._explorer.url != value:
AttributeError: 'Identity' object has no attribute '_explorer'

'Identity' object has no attribute '_explorer'

```

added work around :
![image](https://user-images.githubusercontent.com/36021484/86270552-b35a0d80-bbcb-11ea-820b-536140dea624.png)

**Comment by abom** [comment]
I think this would be resolved by this fix https://github.com/threefoldtech/js-ng/pull/396.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
