### ISSUE TITLE
error saving a stellar client

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#168]
```
j.clients.stellar.new('my_wallet', network='TEST'
j.clients.stellar.my_wallet.save()
```
Operation not permitted

```
j.clients.stellar.new('my_wallet', network='TEST')
Stellar(_Base__instance_name='my_wallet', _Base__parent=None, __address='GAFR75KNHZUZ72GY6UHDEC76IRZQWIAJQ5HY4LE6NRTMW3AKXUA3G4PH', __network=<Network.TEST: 'TEST'>, __secret='SCFU3DXJZK5PXUNFDJGS7OH2ARJD6HEXCFZ67NQTPCJGK7K7UUAATLFD', _factories={}, save=functools.partial(<bound method StoredFactory._validate_and_save_instance of <jumpscale.core.base.factory.jumpscaleclientsstellarstellarStellar object at 0x10548ec90>>, Stellar(...)))

JS-NG> j.clients.stellar.my_wallet.save()
2020-07-02 17:11:40.407 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/bin/jsng", line 11, in <module>
    load_entry_point('js-ng', 'console_scripts', 'jsng')()
    └ <function load_entry_point at 0x101224290>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x101744680>
           └ <Command run>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x101376c90>
         │    └ <function Command.invoke at 0x1017b6050>
         └ <Command run>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'command': None}
           │   │      │    │           └ <click.core.Context object at 0x101376c90>
           │   │      │    └ <function run at 0x1017dd9e0>
           │   │      └ <Command run>
           │   └ <function Context.invoke at 0x101744170>
           └ <click.core.Context object at 0x101376c90>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'command': None}
           │         └ ()
           └ <function run at 0x1017dd9e0>

  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/src/js-ng/jumpscale/entry_points/jsng.py", line 30, in run
    sys.exit(embed(globals(), locals(), configure=ptconfig, history_filename=HISTORY_FILENAME))
    │   │    │                                    │                          └ '/Users/rob/.jsng/history.txt'
    │   │    │                                    └ <function ptconfig at 0x101d95830>
    │   │    └ <function embed at 0x101f83560>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/lib/python3.7/site-packages/ptpython/repl.py", line 350, in embed
    repl.run()
    │    └ <function PythonRepl.run at 0x101f830e0>
    └ <ptpython.repl.PythonRepl object at 0x101d9b250>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/lib/python3.7/site-packages/ptpython/repl.py", line 74, in run
    self._process_text(text)
    │    │             └ 'j.clients.stellar.my_wallet.save()'
    │    └ <function PythonRepl._process_text at 0x101f83170>
    └ <ptpython.repl.PythonRepl object at 0x101d9b250>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/lib/python3.7/site-packages/ptpython/repl.py", line 88, in _process_text
    self._handle_exception(e)
    │    │                 └ PermissionError(1, 'Operation not permitted')
    │    └ functools.partial(<function patched_handle_exception at 0x101857e60>, <ptpython.repl.PythonRepl object at 0x101d9b250>)
    └ <ptpython.repl.PythonRepl object at 0x101d9b250>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/lib/python3.7/site-packages/ptpython/repl.py", line 163, in _execute
    six.exec_(code, self.get_globals(), self.get_locals())
    │   │     │     │    │              │    └ <function embed.<locals>.get_locals at 0x101d9a440>
    │   │     │     │    │              └ <ptpython.repl.PythonRepl object at 0x101d9b250>
    │   │     │     │    └ <function embed.<locals>.get_globals at 0x1017e73b0>
    │   │     │     └ <ptpython.repl.PythonRepl object at 0x101d9b250>
    │   │     └ <code object <module> at 0x1033f29c0, file "<stdin>", line 1>
    │   └ <built-in function exec>
    └ <module 'six' from '/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/lib/python3.7/site-packages/six.py'>
> File "<stdin>", line 1, in <module>

  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/src/js-ng/jumpscale/core/base/factory.py", line 354, in _validate_and_save_instance
    self.store.save(instance.instance_name, instance._get_data())
    │    │          │        │              │        └ <function Base._get_data at 0x103384b00>
    │    │          │        │              └ Stellar(_Base__instance_name='my_wallet', _Base__parent=None, __address='GAFR75KNHZUZ72GY6UHDEC76IRZQWIAJQ5HY4LE6NRTMW3AKXUA3...
    │    │          │        └ <property object at 0x1032f8770>
    │    │          └ Stellar(_Base__instance_name='my_wallet', _Base__parent=None, __address='GAFR75KNHZUZ72GY6UHDEC76IRZQWIAJQ5HY4LE6NRTMW3AKXUA3...
    │    └ <property object at 0x103b03cb0>
    └ <jumpscale.core.base.factory.jumpscaleclientsstellarstellarStellar object at 0x10548ec90>

  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/src/js-ng/jumpscale/core/base/store/__init__.py", line 326, in save
    return self.write(instance_name, self.serializer.serialize(new_config))
           │    │     │              │    │          │         └ {'network': 'TEST', 'address': 'GAFR75KNHZUZ72GY6UHDEC76IRZQWIAJQ5HY4LE6NRTMW3AKXUA3G4PH', 'secret': 'SCFU3DXJZK5PXUNFDJGS7OH...
           │    │     │              │    │          └ <function JsonSerializer.serialize at 0x103092cb0>
           │    │     │              │    └ <jumpscale.core.base.store.serializers.JsonSerializer object at 0x10548e7d0>
           │    │     │              └ <jumpscale.core.base.store.filesystem.FileSystemStore object at 0x10208b190>
           │    │     └ 'my_wallet'
           │    └ <function FileSystemStore.write at 0x103287cb0>
           └ <jumpscale.core.base.store.filesystem.FileSystemStore object at 0x10208b190>

  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/src/js-ng/jumpscale/core/base/store/filesystem.py", line 102, in write
    make_path(path)
    │         └ '/Users/rob/.config/jumpscale/secureconfig/jumpscale/clients/stellar/stellar/Stellar/my_wallet/data'
    └ <function make_path at 0x1031350e0>

  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/src/js-ng/jumpscale/sals/fs/__init__.py", line 462, in make_path
    os.mknod(path)
    │  │     └ '/Users/rob/.config/jumpscale/secureconfig/jumpscale/clients/stellar/stellar/Stellar/my_wallet/data'
    │  └ <built-in function mknod>
    └ <module 'os' from '/usr/local/bin/../Cellar/python/3.7.5/bin/../Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py'>

PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/src/js-ng/jumpscale/core/base/factory.py", line 354, in _validate_and_save_instance
    self.store.save(instance.instance_name, instance._get_data())
    │               │                       └ Stellar(_Base__instance_name='my_wallet', _Base__parent=None, __address='GAFR75KNHZUZ72GY6UHDEC76IRZQWIAJQ5HY4LE6NRTMW3AKXUA3G4P...
    │               └ Stellar(_Base__instance_name='my_wallet', _Base__parent=None, __address='GAFR75KNHZUZ72GY6UHDEC76IRZQWIAJQ5HY4LE6NRTMW3AKXUA3G4P...
    └ <jumpscale.core.base.factory.jumpscaleclientsstellarstellarStellar object at 0x10548ec90>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/src/js-ng/jumpscale/core/base/store/__init__.py", line 326, in save
    return self.write(instance_name, self.serializer.serialize(new_config))
           │          │              │                         └ {'network': 'TEST', 'address': 'GAFR75KNHZUZ72GY6UHDEC76IRZQWIAJQ5HY4LE6NRTMW3AKXUA3G4PH', 'secret': 'SCFU3DXJZK5PXUNFDJGS7OH2AR...
           │          │              └ <jumpscale.core.base.store.filesystem.FileSystemStore object at 0x10208b190>
           │          └ 'my_wallet'
           └ <jumpscale.core.base.store.filesystem.FileSystemStore object at 0x10208b190>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/src/js-ng/jumpscale/core/base/store/filesystem.py", line 102, in write
    make_path(path)
    │         └ '/Users/rob/.config/jumpscale/secureconfig/jumpscale/clients/stellar/stellar/Stellar/my_wallet/data'
    └ <function make_path at 0x1031350e0>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/src/js-ng/jumpscale/sals/fs/__init__.py", line 462, in make_path
    os.mknod(path)
    │        └ '/Users/rob/.config/jumpscale/secureconfig/jumpscale/clients/stellar/stellar/Stellar/my_wallet/data'
    └ <module 'os' from '/usr/local/bin/../Cellar/python/3.7.5/bin/../Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py'>
PermissionError: [Errno 1] Operation not permitted

[Errno 1] Operation not permitted
```

**Comment by waleedhammam** [comment]
Can you try chown `/Users/rob/.config` maybe using `chown -R $USER:$USER /Users/rob/.config`
