### ISSUE TITLE
can not start threebot server

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/js-sdk#1686]
### Description

i have installed threebot server as per the steps on https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/installation.md

but when i try to start threebot it gives me below error 

```
(js-sdk-vpmH-Z_5-py3.8) root@app:~/js-sdk# threebot start
2020-11-16 09:26:08.307 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:93 - jumpscale.core.exceptions.exceptions.Value: No configured identity found
Traceback (most recent call last):
> File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/bin/threebot", line 5, in <module>
    cli()
    └ <Group cli>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f72c0684940>
           └ <Group cli>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f72c18a9e50>
         │    └ <function MultiCommand.invoke at 0x7f72c0685700>
         └ <Group cli>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f72c177f0a0>
           │               │       │       └ <function Command.invoke at 0x7f72c0685310>
           │               │       └ <Command start>
           │               └ <click.core.Context object at 0x7f72c177f0a0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f72bd728280>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False, 'local': False}
           │   │      │    │           └ <click.core.Context object at 0x7f72c177f0a0>
           │   │      │    └ <function start at 0x7f72bd6e0940>
           │   │      └ <Command start>
           │   └ <function Context.invoke at 0x7f72c0684430>
           └ <click.core.Context object at 0x7f72c177f0a0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False, 'local': False}
           │         └ ()
           └ <function start at 0x7f72bd6e0940>

  File "/root/js-sdk/jumpscale/entry_points/threebot.py", line 86, in start
    create_wallets_if_not_exists()
    └ <function create_wallets_if_not_exists at 0x7f72bd6e09d0>

  File "/root/js-sdk/jumpscale/entry_points/threebot.py", line 277, in create_wallets_if_not_exists
    if not test and "testnet" in j.core.identity.me.explorer_url:
           │                     │ └ <property object at 0x7f72c068a3b0>
           │                     └ <jumpscale.loader.J object at 0x7f72c067ca90>
           └ False

  File "/root/js-sdk/jumpscale/core/identity/__init__.py", line 208, in me
    raise Value("No configured identity found")
          └ <class 'jumpscale.core.exceptions.exceptions.Value'>

jumpscale.core.exceptions.exceptions.Value: No configured identity found
```

### Version information

```
(js-sdk-vpmH-Z_5-py3.8) root@app:~/js-sdk# git log -1
commit 4e9f2d4fbe6e3da089e48ac26297cfe7a87c0d7d (HEAD -> development, origin/development, origin/HEAD)
Author: Abdelrahman Ghanem <abom.jdev@gmail.com>
Date:   Mon Nov 16 07:47:09 2020 +0100

    bump js-ng version to 11.0b9 (#1685)
```

**Comment by xmonader** [comment]
quite old
