### ISSUE TITLE
packages: reloading a package fails

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-sdk#1688]
### Description

Reloading a package is broken, as it tries to re-add the service and it fails if the service is already running.

### Version information

* OS: e.g. Ubuntu 18.05
* Project commit/version: development (4e9f2d4fbe6e3da089e48ac26297cfe7a87c0d7d)
* Browser: e.g. chrome

### Installation method

Development installation via `poetry install`

### Steps to reproduce

Reload any package from packages UI.

### Traceback/Logs/Alerts

```
Traceback (most recent call last):                                                                                                                   
  File "/home/abom/projects/jumpscale/js-next/js-sdk/.venv/lib/python3.6/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_don$
    return handle(*args_tuple)                                                                                                                       
           │       └ (<gevent._socket3.socket object, fd=17, family=2, type=2049, proto=0>, ('127.0.0.1', 59030))                                    
           └ <bound method GedisServer._on_connection of GedisServer(                                                                                
               instance_name='threebot',                                                                                                             
               host='127.0.0.1',                                                                                                                     
               port=16000,
               enab...
  File "/home/abom/projects/jumpscale/js-next/js-sdk/.venv/lib/python3.6/site-packages/jumpscale/servers/gedis/server.py", line 279, in _on_connectio
n
    result = self._execute(method, args, kwargs)
             │    │        │       │     └ {'path': '/home/abom/projects/jumpscale/js-next/js-sdk/jumpscale/packages/tfgrid_solutions'}
             │    │        │       └ []
             │    │        └ <bound method Packages.add_package of <packages.Packages object at 0x7f9d7b3fbb00>>
             │    └ <function GedisServer._execute at 0x7f9d80326c80>
             └ GedisServer(
                 instance_name='threebot',
                 host='127.0.0.1',
                 port=16000,
                 enable_system_actor=True,
                 run_async=True,
                 _a...
> File "/home/abom/projects/jumpscale/js-next/js-sdk/.venv/lib/python3.6/site-packages/jumpscale/servers/gedis/server.py", line 228, in _execute
    response["result"] = method(*args, **kwargs)
    │                    │       │       └ {'path': '/home/abom/projects/jumpscale/js-next/js-sdk/jumpscale/packages/tfgrid_solutions'}
    │                    │       └ []
    │                    └ <bound method Packages.add_package of <packages.Packages object at 0x7f9d7b3fbb00>>
    └ {}
  File "/home/abom/projects/jumpscale/js-next/js-sdk/.venv/lib/python3.6/site-packages/jumpscale/servers/gedis/baseactor.py", line 25, in wrapper
    result = func(*bound.args, **bound.kwargs)
             │     │     │       │     └ <property object at 0x7f9d8afd4ea8>
             │     │     │       └ <BoundArguments (self=<packages.Packages object at 0x7f9d7b3fbb00>, path='/home/abom/projects/jumpscale/js-next/j$
-sdk/jumpsc...
             │     │     └ <property object at 0x7f9d8afd4e58>
            │     └ <BoundArguments (self=<packages.Packages object at 0x7f9d7b3fbb00>, path='/home/abom/projects/jumpscale/js-next/js-sdk/jumpsc...
             └ <function Packages.add_package at 0x7f9d7b3a9d90>

  File "/home/abom/projects/jumpscale/js-next/js-sdk/jumpscale/packages/admin/actors/packages.py", line 35, in add_package
    return j.data.serializers.json.dumps({"data": self.threebot.packages.add(path=path, giturl=giturl, **extras)})
           │ │                                    │    │                     │    │     │      │         └ {}
           │ │                                    │    │                     │    │     │      └ ''
           │ │                                    │    │                     │    │     └ ''
           │ │                                    │    │                     │    └ '/home/abom/projects/jumpscale/js-next/js-sdk/jumpscale/packages/
tfgrid_solutions'
           │ │                                    │    │                     └ '/home/abom/projects/jumpscale/js-next/js-sdk/jumpscale/packages/tfgri
d_solutions'
           │ │                                    │    └ <property object at 0x7f9d7b3ab188>
           │ │                                    └ <packages.Packages object at 0x7f9d7b3fbb00>
           │ └ <property object at 0x7f9d88990e58>
           └ <jumpscale.loader.J object at 0x7f9d88989208>

  File "/home/abom/projects/jumpscale/js-next/js-sdk/jumpscale/servers/threebot/threebot.py", line 459, in add
    self.install(package)
    │    │       └ <jumpscale.servers.threebot.threebot.Package object at 0x7f9d7930a550>
    │    └ <function PackageManager.install at 0x7f9d80393730>
    └ PackageManager(
        instance_name='default',
        parent=ThreebotServer(instance_name_='default'),
        packages={'auth': {'path': '/...

  File "/home/abom/projects/jumpscale/js-next/js-sdk/jumpscale/servers/threebot/threebot.py", line 551, in install
    self.threebot.services.add_service(service["path"])
    │    │                             └ {'name': 'tfgrid_solutions_auto_extend_pools', 'path': '/home/abom/projects/jumpscale/js-next/js-sdk/jumpsca
le/packages/tfgri...
    │    └ <property object at 0x7f9d803919a8>
    └ PackageManager(
        instance_name='default',
        parent=ThreebotServer(instance_name_='default'),
        packages={'auth': {'path': '/...

  File "/home/abom/projects/jumpscale/js-next/js-sdk/jumpscale/tools/servicemanager/servicemanager.py", line 128, in add_service
    raise j.exceptions.Value(f"Service with name {service.name} already exists")
          │ └ <property object at 0x7f9d88990a48>
          └ <jumpscale.loader.J object at 0x7f9d88989208>

jumpscale.core.exceptions.exceptions.Value: Service with name threebot_deployer_auto_extend_pools already exists
```

**Comment by RafyAmgadBenjamin** [comment]
on verification
