### ISSUE TITLE
No configured identity found when starting threebot server in fresh installation

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1802]
In a fresh container when trying to start threebot server.
```
(js-sdk-w2FClMcC-py3.8) root@be97b76e9238:/js-sdk# threebot start 
2020-12-09 12:28:18.126 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:93 - jumpscale.core.exceptions.exceptions.Value: No configured identity found
Traceback (most recent call last):
> File "/root/.cache/pypoetry/virtualenvs/js-sdk-w2FClMcC-py3.8/bin/threebot", line 5, in <module>
    cli()
    └ <Group cli>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-w2FClMcC-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f76310a9040>
           └ <Group cli>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-w2FClMcC-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f76323337c0>
         │    └ <function MultiCommand.invoke at 0x7f76310a9dc0>
         └ <Group cli>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-w2FClMcC-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f76321fa430>
           │               │       │       └ <function Command.invoke at 0x7f76310a99d0>
           │               │       └ <Command start>
           │               └ <click.core.Context object at 0x7f76321fa430>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f763236e1f0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-w2FClMcC-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False, 'local': False}
           │   │      │    │           └ <click.core.Context object at 0x7f76321fa430>
           │   │      │    └ <function start at 0x7f762e156940>
           │   │      └ <Command start>
           │   └ <function Context.invoke at 0x7f76310a8af0>
           └ <click.core.Context object at 0x7f76321fa430>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-w2FClMcC-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False, 'local': False}
           │         └ ()
           └ <function start at 0x7f762e156940>

  File "/js-sdk/jumpscale/entry_points/threebot.py", line 86, in start
    create_wallets_if_not_exists()
    └ <function create_wallets_if_not_exists at 0x7f762e1569d0>

  File "/js-sdk/jumpscale/entry_points/threebot.py", line 277, in create_wallets_if_not_exists
    if not test and "testnet" in j.core.identity.me.explorer_url:
           │                     │ └ <property object at 0x7f76315c99a0>
           │                     └ <jumpscale.loader.J object at 0x7f76315b84f0>
           └ False

  File "/js-sdk/jumpscale/core/identity/__init__.py", line 208, in me
    raise Value("No configured identity found")
          └ <class 'jumpscale.core.exceptions.exceptions.Value'>

jumpscale.core.exceptions.exceptions.Value: No configured identity found
```

**Comment by mhost39** [comment]
Verified 
branch: development
commit: 96965743b5c52e90facac66835b46d6f1c3b8c67
