### ISSUE TITLE
deleting a package fails if one of its services is not running

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#1815]
```
  File "/home/maged/Code/js-sdk/jumpscale/servers/threebot/threebot.py", line 504, in delete
    self.threebot.services.stop_service(service["name"])
    │    │                              └ {'name': 'vdc_provision_wallet_billing', 'path': '/home/maged/Code/js-sdk/jumpscale/packages/vdc/services/provision_wallet_bi...
    │    └ <property object at 0x7f0423326a98>
    └ PackageManager(
        instance_name='default',
        parent=ThreebotServer(instance_name_='default'),
        packages={'auth': {'path': '/...

  File "/home/maged/Code/js-sdk/jumpscale/tools/servicemanager/servicemanager.py", line 146, in stop_service
    raise j.exceptions.Value(f"Service {service_name} is not running")
          │ └ <property object at 0x7f042a28bf98>
          └ <jumpscale.loader.J object at 0x7f042a2ebf60>

jumpscale.core.exceptions.exceptions.Value: Service vdc_provision_wallet_billing is not running
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maged/Code/js-sdk/jumpscale/servers/threebot/threebot.py", line 504, in delete
    self.threebot.services.stop_service(service['name'])
    │                                   └ {'name': 'vdc_provision_wallet_billing', 'path': '/home/maged/Code/js-sdk/jumpscale/packages/vdc/services/provision_wallet_billi...
    └ PackageManager(
  instance_name='default',
  parent=ThreebotServer(instance_name_='default'),
  packages={'auth': {'path': '/hom...
  File "/home/maged/Code/js-sdk/jumpscale/tools/servicemanager/servicemanager.py", line 146, in stop_service
    raise j.exceptions.Value('Service '' is not running'e_name} is not running")
          │                             └ 'vdc_provision_wallet_billing'
          └ <jumpscale.loader.J object at 0x7f042a2ebf60>
jumpscale.core.exceptions.exceptions.Value: Service vdc_provision_wallet_billing is not running

Service vdc_provision_wallet_billing is not running
JS-NG> 
```

stopping a services that is not running should not raise an exception

**Comment by xmonader** [comment]
As discussed with @AhmedSa-mir, when starting the package always prepend the package name

**Comment by mhost39** [comment]
Verified 
branch: development

Steps:
1. add a package 
2. stop services 
3. try to delete this package 
package deleted
