### ISSUE TITLE
Vdc deployment crashes

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1850]
### Description
The vdc deployer crashes at the end  after deploying the workloads.
I chose a silver plan, it asked me to transfer 364 TFT

### Version information
Testnet

### Traceback/Logs/Alerts

In the alert on the vdc deployer 3bot:

message:`Wallet vdc_rob_rob_provision_wallet does not have enough funds to pay for 367.6311306 TFT:GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3`

stacktrace:
```
Traceback (most recent call last):
  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
  File "/root/js-sdk/jumpscale/packages/vdc/chats/new_vdc.py", line 120, in deploy
    self.deployer.renew_plan(14 - INITIAL_RESERVATION_DURATION / 24)
  File "/root/js-sdk/jumpscale/sals/vdc/deployer.py", line 755, in renew_plan
    self.pay(pool_info)
  File "/root/js-sdk/jumpscale/sals/vdc/deployer.py", line 769, in pay
    raise e
  File "/root/js-sdk/jumpscale/sals/vdc/deployer.py", line 766, in pay
    self.transaction_hashes += self.zos.billing.payout_farmers(self.wallet, pool_info)
  File "/root/js-sdk/jumpscale/sals/zos/billing.py", line 49, in payout_farmers
    raise InsufficientFunds(
jumpscale.sals.zos.billing.InsufficientFunds: Wallet vdc_rob_rob_provision_wallet does not have enough funds to pay for 367.6311306 TFT:GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3
```

**Comment by xmonader** [comment]
I think this is coming from 
```
    self.deployer.renew_plan(14 - INITIAL_RESERVATION_DURATION / 24)
```
for some reason, this calculation now is off by 4 TFT

**Comment by m-motawea** [comment]
we already have an issue open for quite some time to calculate the correct pricing which needs to be sorted out first
https://github.com/threefoldtech/vdc/issues/75
