### ISSUE TITLE
Failure of adding access to an exiting network

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#1857]
![image](https://user-images.githubusercontent.com/13766992/102218720-d79a7400-3ef7-11eb-9450-ccf85bfce1bc.png)

Content of the alert:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/response.py", line 436, in _error_catcher
    yield
  File "/usr/local/lib/python3.8/dist-packages/urllib3/response.py", line 766, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/response.py", line 719, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/usr/lib/python3.8/http/client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_ssl3.py", line 503, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_ssl3.py", line 327, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/response.py", line 792, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/tfgrid_solutions/chats/network.py", line 119, in network_reservation
    self.config = deployer.add_access(
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 747, in add_access
    network_view.dry_run(
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 84, in __exit__
    network_view = NetworkView(self.test_network_name, identity_name=self.identity_name)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 93, in __init__
    workloads = j.sals.zos.get(self.identity_name).workloads.list(identity_tid, NextAction.DEPLOY)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/zos/workloads.py", line 58, in list
    return self._workloads.list(customer_tid, next_action)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/workloads.py", line 127, in list
    workloads = list(self.iter(customer_tid, next_action))
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/workloads.py", line 167, in iter
    yield from filter(filter_next_action, get_all(self._session, Decoder, url, query))
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/pagination.py", line 15, in get_all
    iter, pages = get_page(session, 1, model, url, query, auth, headers)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/pagination.py", line 5, in get_page
    resp = session.get(url, params=query, auth=auth, headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 685, in send
    r.content
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 754, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by waleedhammam** [comment]
```
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/workloads.py", line 127, in list
    workloads = list(self.iter(customer_tid, next_action))
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/workloads.py", line 167, in iter
    yield from filter(filter_next_action, get_all(self._session, Decoder, url, query))
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/pagination.py", line 15, in get_all
    iter, pages = get_page(session, 1, model, url, query, auth, headers)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/pagination.py", line 5, in get_page
    resp = session.get(url, params=query, auth=auth, headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 685, in send
    r.content
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 754, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```
seems it fails to connect to the explorer, @muhamadazmy any idea ?

**Comment by waleedhammam** [comment]
Verified after merging TRC with 3Bot Flist
