### ISSUE TITLE
threebot stop raises psutil.AccessDenied

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#186]
```
(.venv) ➜  js-sdk git:(development) ✗ threebot stop        
^[[ATraceback (most recent call last):
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/psutil/__init__.py", line 1192, in _send_signal
    os.kill(self.pid, sig)
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xmonader/wspace/js/js-sdk/.venv/bin/threebot", line 11, in <module>
    load_entry_point('js-sdk', 'console_scripts', 'threebot')()
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/xmonader/wspace/js/js-sdk/jumpscale/entry_points/threebot.py", line 130, in stop
    threebot_cmd.stop()
  File "/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/tools/startupcmd/startupcmd.py", line 208, in stop
    self._hard_kill()
  File "/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/tools/startupcmd/startupcmd.py", line 185, in _hard_kill
    self._kill_processes_by_port_or_filter()
  File "/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/tools/startupcmd/startupcmd.py", line 145, in _kill_processes_by_port_or_filter
    self._kill_processes(processes)
  File "/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/tools/startupcmd/startupcmd.py", line 155, in _kill_processes
    process.kill()
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/psutil/__init__.py", line 292, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/psutil/__init__.py", line 1255, in kill
    self._send_signal(signal.SIGKILL)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/psutil/__init__.py", line 1202, in _send_signal
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=2434)

```

**Comment by waleedhammam** [comment]
fixed by find process by port
