### ISSUE TITLE
filter out invalid wallets from the dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1889]
example: wallets that got resetted after testnet reset give errors like

```
m actor admin_wallet to client ('127.0.0.1', 51618)
2020-12-20 18:41:21.756 | ERROR    | jumpscale.servers.gedis.server:_execute:231 - error while executing <bound method Wallet.get_wallet_info of <wallet.Wallet object at 0x7f6439028400>>
Traceback (most recent call last):
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
           │       └ (<gevent._socket3.socket object, fd=13, family=2, type=1, proto=0>, ('127.0.0.1', 51618))
           └ <bound method GedisServer._on_connection of GedisServer(
               instance_name='threebot',
               host='127.0.0.1',
               port=16000,
               enab...
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/servers/gedis/server.py", line 279, in _on_connection
    result = self._execute(method, args, kwargs)
    │        │    │        │       │     └ {'name': 'tfta_acceptance'}
    │        │    │        │       └ []
    │        │    │        └ <bound method Wallet.get_wallet_info of <wallet.Wallet object at 0x7f6439028400>>
    │        │    └ <function GedisServer._execute at 0x7f6439ed34c0>
    │        └ GedisServer(
    │            instance_name='threebot',
    │            host='127.0.0.1',
    │            port=16000,
    │            enable_system_actor=True,
    │            run_async=True,
    │            _a...
    └ {'result': '{"data": 0}'}
> File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/servers/gedis/server.py", line 228, in _execute
    response["result"] = method(*args, **kwargs)
    │                    │       │       └ {'name': 'tfta_acceptance'}
    │                    │       └ []
    │                    └ <bound method Wallet.get_wallet_info of <wallet.Wallet object at 0x7f6439028400>>
    └ {}
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/servers/gedis/baseactor.py", line 25, in wrapper
    result = func(*bound.args, **bound.kwargs)
             │     │     │       │     └ <property object at 0x7f643dd22680>
             │     │     │       └ <BoundArguments (self=<wallet.Wallet object at 0x7f6439028400>, name='tfta_acceptance')>
             │     │     └ <property object at 0x7f643dd22630>
             │     └ <BoundArguments (self=<wallet.Wallet object at 0x7f6439028400>, name='tfta_acceptance')>
             └ <function Wallet.get_wallet_info at 0x7f64390275e0>

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/packages/admin/actors/wallet.py", line 48, in get_wallet_info
    balances = wallet.get_balance()
               │      └ <function Stellar.get_balance at 0x7f643a3044c0>
               └ Stellar(
                   instance_name='tfta_acceptance',
                   network=<Network.TEST: 'TEST'>,
                   address='GCBL5NHEGES6IT4F7KJQBW47EUXMHHKFH2AD...

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/clients/stellar/stellar.py", line 136, in get_balance
    all_balances = self._get_free_balances(address)
                   │    │                  └ 'GCBL5NHEGES6IT4F7KJQBW47EUXMHHKFH2ADLHG4RMY7SUIBV5JJGRXS'
                   │    └ <function Stellar._get_free_balances at 0x7f643a2fcf70>
                   └ Stellar(
                       instance_name='tfta_acceptance',
                       network=<Network.TEST: 'TEST'>,
                       address='GCBL5NHEGES6IT4F7KJQBW47EUXMHHKFH2AD...

  File "/home/xmonader/wspace/js/js-sdk/jumpscale/clients/stellar/stellar.py", line 71, in _get_free_balances
    response = self._get_horizon_server().accounts().account_id(address).call()
               │    │                                           └ 'GCBL5NHEGES6IT4F7KJQBW47EUXMHHKFH2ADLHG4RMY7SUIBV5JJGRXS'
               │    └ <function Stellar._get_horizon_server at 0x7f643a2fcee0>
               └ Stellar(
                   instance_name='tfta_acceptance',
                   network=<Network.TEST: 'TEST'>,
                   address='GCBL5NHEGES6IT4F7KJQBW47EUXMHHKFH2AD...

  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 58, in call
    return self.__call(url, self.params)
           │           │    │    └ {}
           │           │    └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7f6432fd95e0>
           │           └ 'https://horizon-testnet.stellar.org/accounts/GCBL5NHEGES6IT4F7KJQBW47EUXMHHKFH2ADLHG4RMY7SUIBV5JJGRXS'
           └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7f6432fd95e0>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 64, in __call
    return self.__call_sync(url, params)
           │                │    └ {}
           │                └ 'https://horizon-testnet.stellar.org/accounts/GCBL5NHEGES6IT4F7KJQBW47EUXMHHKFH2ADLHG4RMY7SUIBV5JJGRXS'
           └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7f6432fd95e0>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 68, in __call_sync
    raise_request_exception(raw_resp)
    │                       └ <stellar_sdk.client.response.Response object at 0x7f6432f3e940>
    └ <function raise_request_exception at 0x7f643abd2ee0>
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/stellar_sdk/exceptions.py", line 200, in raise_request_exception
    raise NotFoundError(response)
          │             └ <stellar_sdk.client.response.Response object at 0x7f6432f3e940>
          └ <class 'stellar_sdk.exceptions.NotFoundError'>

stellar_sdk.exceptions.NotFoundError: {
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}

```

**Comment by xmonader** [comment]
shouldn't be a focus, 3bot user should have at max 1 stellar wallet
