### ISSUE TITLE
Cannot deploy ubuntu on production grid

### ISSUE THREAD

**Issue by nbabenko** [threefoldtech/js-sdk#2048]
3bot name: nick3bot
cannot deploy ubuntu server in 3bot admin panel, getting following exception during the deploy dialog:

Traceback (most recent call last):
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/tfgrid_solutions/chats/ubuntu.py", line 70, in select_pool
    cloud_units = j.sals.marketplace.deployer._calculate_cloud_units(**self.resources)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/marketplace/deployer.py", line 343, in _calculate_cloud_units
    cont1.capacity.cpu = resources["cru"]
KeyError: 'cru'

<img width="966" alt="Screenshot 2020-12-29 at 15 44 17" src="https://user-images.githubusercontent.com/4426772/103294705-0be35980-49fb-11eb-9795-c53c31f2acdb.png">

**Comment by waleedhammam** [comment]
fixed at: https://github.com/threefoldtech/js-sdk/commit/97ae57cdcab1ca3fcf24b71d902c3973027ba085

**Comment by ranatrk** [comment]
verified, ubuntu deployed successfully when deploying from admin dashboard
![Screenshot from 2021-01-13 19-03-11](https://user-images.githubusercontent.com/17128393/104484506-0a588a80-55d2-11eb-8232-a521cdc67e47.png)
