### ISSUE TITLE
Auto Extend Kubernetes Cluster

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#2123]
Automatically add k8s workers if utilization reaches a certain threshold

**Comment by m-motawea** [comment]
1- which farms to deploy new workers on
2- which size(s) to use for new workers
3- what is the extension limit

**Comment by m-motawea** [comment]
- [ ] add k8s cluster cpu and memory monitoring
- [ ] add extension service according the number of workers as per the vdc spec
- [ ] check for resources before marketplace solution deployment and extend if possible
- [ ] reduce the number of workers in initial deployment to 1 worker for all flavors

**Comment by waleedhammam** [comment]
I deployed a diamond plan. Didn't deploy solution.
- Tried to deploy taiga, got an error trying to extend

Cluster current worker is 8cores & 32gb ram should more than enough to deploy a single taiga and it has the master too

```
k3os-20851 [~]$ kubectl get nodes
NAME         STATUS   ROLES    AGE     VERSION
k3os-14052   Ready    <none>   8m41s   v1.19.4+k3s1
k3os-20851   Ready    master   10m     v1.19.4+k3s1
k3os-20851 [~]$ kubectl top nodes
NAME         CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
k3os-14052   94m          1%     232Mi           0%        
k3os-20851   217m         21%    703Mi           35%       
k3os-20851 [~]$ kubectl get nodes
NAME         STATUS   ROLES    AGE     VERSION
k3os-14052   Ready    <none>   9m30s   v1.19.4+k3s1
k3os-20851   Ready    master   11m     v1.19.4+k3s1
k3os-20851 [~]$ kubectl get pod -A
NAMESPACE     NAME                                         READY   STATUS    RESTARTS   AGE
k3os-system   system-upgrade-controller-6c9f84cb79-8p957   1/1     Running   0          10m
kube-system   coredns-66c464876b-sxpcg                     1/1     Running   0          10m
kube-system   local-path-provisioner-7ff9579c6-9cqff       1/1     Running   0          10m
kube-system   metrics-server-7b4f8b595-89znc               1/1     Running   0          10m
kube-system   svclb-traefik-sblfp                          2/2     Running   0          8m8s
kube-system   svclb-traefik-zlthb                          2/2     Running   0          8m8s
kube-system   traefik-9bd88df49-hbkzr                      1/1     Running   0          8m9s
```

and since the threeshould is 70% cpu and ram it shouldn't extend
```
2021-02-23 14:54:26.254 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:173 - error when executing step set_config. exception: not enough capacity in farm lochristi_dev_lab for 1 kubernetes nodes of flavor K8SNodeFlavor.BIG
Traceback (most recent call last):

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 202, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f123f2f21f0>
    └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f123c86dbe0>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 210, in _execute_current_step
    wrapper(step_name)
    │       └ 'create_subdomain'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f123c7a0670>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 202, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f123f2f21f0>
    └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f123c86dbe0>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 210, in _execute_current_step
    wrapper(step_name)
    │       └ 'set_config'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f123c79d550>

> File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
            │     └ 'set_config'
            └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f123c86dbe0>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f123c86dbe0>,)
           └ <function CryptpadDeploy.set_config at 0x7f123d2254c0>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/chats/cryptpad.py", line 21, in set_config
    self._choose_flavor()
    │    └ <function SolutionsChatflowDeploy._choose_flavor at 0x7f123d307c10>
    └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f123c86dbe0>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py", line 94, in _choose_flavor
    self._validate_resource_limits(cpu, memory, no_nodes)
    │    │                         │    │       └ 1
    │    │                         │    └ 1024
    │    │                         └ 1000
    │    └ <function SolutionsChatflowDeploy._validate_resource_limits at 0x7f123d259a60>
    └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f123c86dbe0>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py", line 102, in _validate_resource_limits
    wids = monitor.extend(bot=self)
           │       │          └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f123c86dbe0>
           │       └ <function KubernetesMonitor.extend at 0x7f123d305040>
           └ <jumpscale.sals.vdc.kubernetes_auto_extend.KubernetesMonitor object at 0x7f123c5b0190>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/vdc/kubernetes_auto_extend.py", line 179, in extend
    wids = deployer.add_k8s_nodes(flavor, farm_name, no_nodes=no_nodes, external=False)
           │        │             │       │          │        └ 1
           │        │             │       │          └ 1
           │        │             │       └ None
           │        │             └ <K8SNodeFlavor.BIG: 9>
           │        └ <function VDCDeployer.add_k8s_nodes at 0x7f123d2d79d0>
           └ <jumpscale.sals.vdc.deployer.VDCDeployer object at 0x7f123f742550>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/vdc/deployer.py", line 706, in add_k8s_nodes
    wids = self.kubernetes.extend_cluster(
           │    └ <property object at 0x7f123d2ec590>
           └ <jumpscale.sals.vdc.deployer.VDCDeployer object at 0x7f123f742550>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/vdc/kubernetes.py", line 98, in extend_cluster
    raise j.exceptions.Validation(
          │ └ <property object at 0x7f1243351a90>
          └ <jumpscale.loader.J object at 0x7f124388c820>

jumpscale.core.exceptions.exceptions.Validation: not enough capacity in farm lochristi_dev_lab for 1 kubernetes nodes of flavor K8SNodeFlavor.BIG
```

**Comment by m-motawea** [comment]
from the resources reserved on your cluster

```python
JS-NG> resv = mon.fetch_resource_reservations()
2021-02-23 15:20:32.716 | DEBUG    | jumpscale.sals.kubernetes.manager:_execute:45 - kubernetes manager: kubectl get pod -A -o json --kubeconfig /root/.kube/config
2021-02-23 15:20:33.068 | DEBUG    | jumpscale.sals.kubernetes.manager:_execute:45 - kubernetes manager: kubectl get pod -n k3os-system system-upgrade-controller-6c9f84cb79-8p957 -o json --kubeconfig /root/.kube/config
2021-02-23 15:20:33.388 | DEBUG    | jumpscale.sals.kubernetes.manager:_execute:45 - kubernetes manager: kubectl get pod -n kube-system coredns-66c464876b-sxpcg -o json --kubeconfig /root/.kube/config
2021-02-23 15:20:33.839 | DEBUG    | jumpscale.sals.kubernetes.manager:_execute:45 - kubernetes manager: kubectl get pod -n kube-system local-path-provisioner-7ff9579c6-9cqff -o json --kubeconfig /root/.kube/config
2021-02-23 15:20:34.147 | DEBUG    | jumpscale.sals.kubernetes.manager:_execute:45 - kubernetes manager: kubectl get pod -n kube-system metrics-server-7b4f8b595-89znc -o json --kubeconfig /root/.kube/config
2021-02-23 15:20:34.449 | DEBUG    | jumpscale.sals.kubernetes.manager:_execute:45 - kubernetes manager: kubectl get pod -n kube-system svclb-traefik-sblfp -o json --kubeconfig /root/.kube/config
2021-02-23 15:20:34.778 | DEBUG    | jumpscale.sals.kubernetes.manager:_execute:45 - kubernetes manager: kubectl get pod -n kube-system svclb-traefik-zlthb -o json --kubeconfig /root/.kube/config
2021-02-23 15:20:35.075 | DEBUG    | jumpscale.sals.kubernetes.manager:_execute:45 - kubernetes manager: kubectl get pod -n kube-system traefik-9bd88df49-hbkzr -o json --kubeconfig /root/.kube/config
2021-02-23 15:20:36.224 | DEBUG    | jumpscale.sals.kubernetes.manager:_execute:45 - kubernetes manager: kubectl top nodes  --no-headers=true --kubeconfig /root/.kube/config
2021-02-23 15:20:36.539 | DEBUG    | jumpscale.sals.kubernetes.manager:_execute:45 - kubernetes manager: kubectl get nodes -o wide -o json --kubeconfig /root/.kube/config
2021-02-23 15:20:36.744 | INFO     | jumpscale.sals.vdc.kubernetes_auto_extend:update_stats:102 - kubernetes stats: {'k3os-14052': {'cpu': {'used': 84.0, 'total': 8400.0}, 'memory': {'used': 237.0, 'total': 237.0}, 'wid': 31821}, 'k3os-20851': {'cpu': {'used': 169.0, 'total': 1056.25}, 'memory': {'used': 713.0, 'total': 2037.1428571428573}, 'wid': 31812}}
JS-NG> for res in resv:
     2     print(res.free_cpu, res.free_memory)
956.25 1967.1428571428573
8400.0 237.0
JS-NG> 
```

given that taiga uses 256 + whatever flavor you chose where the least is 1000m cpu and 1024Mi memory

it makes sense to fail

**Comment by waleedhammam** [comment]
```
k3os-20851 [~]$ kubectl get pod
NAME                                           READY   STATUS    RESTARTS   AGE
cryptpad-1614094333-744897b9b6-6dvcs           1/1     Running   0          3m
cryptpad-1614094340-b7484494b-7bhm9            1/1     Running   0          2m53s
cryptpad-1614094344-6959bc994b-8k4sm           1/1     Running   0          2m49s
mattermost-1614094414-57d95bfb5f-rsq8g         0/1     Running   0          98s
mattermost-1614094414-mysql-7fb76776f5-8f9sq   1/1     Running   0          98s
omar-0                                         1/1     Running   0          111s
taiga-1614094401-68d985cbc5-gwzgm              1/1     Running   0          111s
```

**Comment by waleedhammam** [comment]
extend works ok
but miscalculations, to be continued in https://github.com/threefoldtech/js-sdk/issues/2474
