### ISSUE TITLE
Cannot top-up existing capacity pool

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2147]
Depleated capacity pool needs to be topped up but get an error (after payment was successfull) on mainnet:
![image](https://user-images.githubusercontent.com/13766992/104083158-d427ad80-5255-11eb-899f-0cc12eaf3030.png)

Error reported in alerts:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_ssl3.py", line 503, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_ssl3.py", line 327, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_ssl3.py", line 503, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_ssl3.py", line 327, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/tfgrid_solutions/chats/flist.py", line 86, in select_pool
    self.pool_id = deployer.select_pool(self, cu=cloud_units.cu, su=cloud_units.su, **query)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 610, in select_pool
    available_pools = available_pools or self.list_pools(cu, su)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 570, in list_pools
    all_pools = [p for p in j.sals.zos.get().pools.list() if p.node_ids]
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/zos/pools.py", line 130, in list
    return self._pools.list(customer_tid=self._identity.tid)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/pools.py", line 55, in list
    reservations = list(self.iter(customer_tid))
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/pools.py", line 69, in iter
    yield from get_all(self._session, Pool, url)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/pagination.py", line 15, in get_all
    iter, pages = get_page(session, 1, model, url, query, auth, headers)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/pagination.py", line 5, in get_page
    resp = session.get(url, params=query, auth=auth, headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by xmonader** [comment]
are your resources increased on the pool?  because that's a direct payment from you to explorer escrow if paid you will get extended resources, if not you will get refunded

Anyhow, connection fixed https://github.com/threefoldtech/js-sdk/pull/1947 already on testnet 3 weeks ago, mainnet 3bot was never updated to use that (because it only happened on your 3bot). I did an upgrade to the mainnet 3bot

**Comment by xmonader** [comment]
tried it myself on a new 3bot

![image](https://user-images.githubusercontent.com/64129/104106240-0b7d7500-52bd-11eb-9a1a-596976f4439d.png)


before 
![image](https://user-images.githubusercontent.com/64129/104106243-10422900-52bd-11eb-985f-c939e2934eeb.png)

after
![image](https://user-images.githubusercontent.com/64129/104106246-1506dd00-52bd-11eb-9909-6007ac1efe87.png)

**Comment by weynandkuijpers** [comment]
I work with an online 3bot.  This3bot is existing for a couple of weeks and has some capacity pools with capacity.  I'd like to continue to use that - how do I "upgrade" my 3bot?  Stop and start it through the deployer interface?

**Comment by xmonader** [comment]
Restarting the 3bot is enough, you can always go to settings and copy the active identity information and it's words email and 3bot name to be able to recover manually if you want. Also take a look at the backup section to see when was the last snapshot, and force a new snapshot if u want to

**Comment by weynandkuijpers** [comment]
Thank you understood.  Unfortunately, stopping and then trying to start or relocate ended in this:
![image](https://user-images.githubusercontent.com/13766992/104118097-c8b0b100-533f-11eb-95cf-33e1ba273bc9.png)

**Comment by waleedhammam** [comment]
@weynandkuijpers Can you please add the alert details from the alerts pane ?

**Comment by weynandkuijpers** [comment]
This is the output from the deployer - there is no alerts pane....  I am trying to start the 3bot.

**Comment by weynandkuijpers** [comment]
my account is: weynandkuijpers.3bot and the 3bot online name is: "mainjetser"

**Comment by waleedhammam** [comment]
I checked the logs, found 2 errors related to payment, we will try to avoid it using retries will be introduced in here as stellar network has lots of glitches https://github.com/threefoldtech/js-sdk/issues/2152

and another one: `memory: value '2048.0' is not of type int`

**Comment by waleedhammam** [comment]
Payment fixes should reflect with the next release of ZOS when the payment endpoint update.
Memory fixes is made into here: https://github.com/threefoldtech/js-sdk/pull/2157

**Comment by waleedhammam** [comment]
Mainnet has been upgraded
If it ever happend again please open an issue with the workload ids
