### ISSUE TITLE
when creating a new 3bot getting 502 bad gateway or 500 couldn't setup capacity escrow

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2150]
alerts 216 and 217

## 216
502 Server Error: 502 Bad Gateway for url: https://explorer.grid.tf/api/v1/reservations/pools

```
Traceback (most recent call last):
  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
  File "/root/js-sdk/jumpscale/sals/marketplace/apps_chatflow.py", line 460, in infrastructure_setup
    self._get_pool()
  File "/root/js-sdk/jumpscale/packages/threebot_deployer/chats/threebot.py", line 129, in _get_pool
    self.pool_info = deployer.create_3bot_pool(
  File "/root/js-sdk/jumpscale/sals/marketplace/deployer.py", line 334, in create_3bot_pool
    pool_info = j.sals.zos.get(identity_name).pools.create(
  File "/root/js-sdk/jumpscale/sals/zos/pools.py", line 65, in create
    return self._reserve(pool)
  File "/root/js-sdk/jumpscale/sals/zos/pools.py", line 24, in _reserve
    return self._pools.create(pool)
  File "/root/js-sdk/jumpscale/clients/explorer/pools.py", line 38, in create
    resp = self._session.post(self._base_url, json=pool.to_dict())
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/root/js-sdk/jumpscale/clients/explorer/errors.py", line 23, in raise_for_status
    raise HTTPError(http_error_msg, response=resp)
requests.exceptions.HTTPError: 502 Server Error: 502 Bad Gateway
 for url: https://explorer.grid.tf/api/v1/reservations/pools
```

## 217

```
500 Server Error: could not set up capacity escrow: failed to get escrow address for customer: failed to create a new account for customer 1504: failed to activate escrow account GC4IB33NNYICLS3APIRDEY673KFIAN2XAPMCTTPJYPF4CBB6RL4BG2HW: horizon error: "Transaction Failed" - check horizon.Error.Problem for more information for url: https://explorer.grid.tf/api/v1/reservations/pools
```

```
Traceback (most recent call last):
  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
  File "/root/js-sdk/jumpscale/sals/marketplace/apps_chatflow.py", line 460, in infrastructure_setup
    self._get_pool()
  File "/root/js-sdk/jumpscale/packages/threebot_deployer/chats/threebot.py", line 129, in _get_pool
    self.pool_info = deployer.create_3bot_pool(
  File "/root/js-sdk/jumpscale/sals/marketplace/deployer.py", line 334, in create_3bot_pool
    pool_info = j.sals.zos.get(identity_name).pools.create(
  File "/root/js-sdk/jumpscale/sals/zos/pools.py", line 65, in create
    return self._reserve(pool)
  File "/root/js-sdk/jumpscale/sals/zos/pools.py", line 24, in _reserve
    return self._pools.create(pool)
  File "/root/js-sdk/jumpscale/clients/explorer/pools.py", line 38, in create
    resp = self._session.post(self._base_url, json=pool.to_dict())
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/root/js-sdk/jumpscale/clients/explorer/errors.py", line 23, in raise_for_status
    raise HTTPError(http_error_msg, response=resp)
requests.exceptions.HTTPError: 500 Server Error: could not set up capacity escrow: failed to get escrow address for customer: failed to create a new account for customer 1504: failed to activate escrow account GC4IB33NNYICLS3APIRDEY673KFIAN2XAPMCTTPJYPF4CBB6RL4BG2HW: horizon error: "Transaction Failed" - check horizon.Error.Problem for more information for url: https://explorer.grid.tf/api/v1/reservations/pools
```

**Comment by waleedhammam** [comment]
Happening on the explorer side: relates https://github.com/threefoldtech/tfexplorer/issues/272

**Comment by waleedhammam** [comment]
```
  File "/root/js-sdk/jumpscale/clients/explorer/errors.py", line 23, in raise_for_status
    raise HTTPError(http_error_msg, response=resp)
          │         │                        └ <Response [500]>
          │         └ '500 Server Error: could not set up capacity escrow: failed to get escrow address for customer: failed to create a new accoun...
          └ <class 'requests.exceptions.HTTPError'>

requests.exceptions.HTTPError: 500 Server Error: could not set up capacity escrow: failed to get escrow address for customer: failed to create a new account for customer 1517: failed to activate escrow account GAWOR7GLG2Z5ZGK5LXGYRJKIUSQHUI4ES7U5U7XXI2OLDSSN72DUATWO: horizon error: "Transaction Failed" - check horizon.Error.Problem for more information for url: https://explorer.grid.tf/api/v1/reservations/pools
```
just got it again

**Comment by muhamadazmy** [comment]
Mainnet does not run the code that retries yet. This code is running on devnet only (and now also testnet on 11th of Jan) once this is verified on testnet, we can update mainnet

**Comment by waleedhammam** [comment]
Mainnet is upgraded, payment api is there, can't see the error anymore

**Comment by waleedhammam** [comment]
Mainnet is upgraded, payment api is there, can't see the error anymore
