### ISSUE TITLE
Index out of range while deploying vdc on testnet

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#2267]
cancelling by uuid instead of cancelling single workload.

### Traceback/Logs/Alerts

```
Traceback (most recent call last):
  File "/root/js-sdk/jumpscale/packages/vdc/chats/new_vdc.py", line 129, in deploy
    self.config = self.deployer.deploy_vdc(minio_ak=None, minio_sk=None)
  File "/root/js-sdk/jumpscale/sals/vdc/deployer.py", line 538, in deploy_vdc
    master_ip = self.vdc_instance.kubernetes[0].public_ip
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
  File "/root/js-sdk/jumpscale/packages/vdc/chats/new_vdc.py", line 138, in deploy
    self.stop(str(err))
  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 657, in stop
    raise StopChatFlow(msg=msg, **kwargs)
jumpscale.sals.chatflows.chatflows.StopChatFlow: (StopChatFlow(...), 'list index out of range')
```

**Comment by waleedhammam** [comment]
fixed here https://github.com/threefoldtech/js-sdk/commit/548f7507f9e7e6b7311cb4b20b3ae289ba126cb6

**Comment by ranatrk** [comment]
successful deployment of vds using https://vdc.testnet.grid.tf/
