### ISSUE TITLE
VDC Marketplace solutions deploy fails on testnet

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/js-sdk#2283]
### Description

When deploying a solution from the vdc marketplace dashboard fails. 
![Screenshot from 2021-01-19 11-46-12](https://user-images.githubusercontent.com/17128393/105017330-51b89e00-5a4c-11eb-9f65-5f7bc2741dbc.png)

### Traceback/Logs/Alerts
When accessing the machine to debug the following error is thrown:
```
2021-01-19 09:37:25.075 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:173 - error
Traceback (most recent call last):

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 202, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f669b817f70>
    └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f66995fe250>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 210, in _execute_current_step
    wrapper(step_name)
    │       └ 'create_subdomain'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f6699833a60>

> File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
            │     └ 'create_subdomain'
            └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f66995fe250>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f66995fe250>,)
           └ <function SolutionsChatflowDeploy.create_subdomain at 0x7f669966f700>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py", line 287, in create_subdomain
    self._get_domain()
    │    └ <function SolutionsChatflowDeploy._get_domain at 0x7f669966f310>
    └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f66995fe250>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py", line 117, in _get_domain
    gateways = deployer.list_all_gateways(self.username, PREFERRED_FARM, identity_name=self.identity_name)
    │          │        │                 │    │         │                             │    └ 'vdc_ident_4308ae733aba4c48b6635f09be8dd924'
    │          │        │                 │    │         │                             └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f66995fe250>
    │          │        │                 │    │         └ 'csfarmer'
    │          │        │                 │    └ 'ranatarek'
    │          │        │                 └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f66995fe250>
    │          │        └ <function MarketPlaceDeployer.list_all_gateways at 0x7f669973e9d0>
    │          └ <jumpscale.sals.marketplace.deployer.MarketPlaceDeployer object at 0x7f66998acca0>
    └ {}

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/marketplace/deployer.py", line 185, in list_all_gateways
    gateways_pools = self._get_gateways_pools(farm_name, identity_name)  # Empty pools contains the gateways only
                     │    │                   │          └ 'vdc_ident_4308ae733aba4c48b6635f09be8dd924'
                     │    │                   └ 'csfarmer'
                     │    └ <function MarketPlaceDeployer._get_gateways_pools at 0x7f669973e940>
                     └ <jumpscale.sals.marketplace.deployer.MarketPlaceDeployer object at 0x7f66998acca0>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/marketplace/deployer.py", line 158, in _get_gateways_pools
    farms_names_with_gateways = set(

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/marketplace/deployer.py", line 159, in <lambda>
    map(lambda farm_id: deployer._explorer.farms.get(farm_id=farm_id).name, farms_ids_with_gateways)
               │        │        │                   │       └ 71
               │        │        │                   └ 71
               │        │        └ <property object at 0x7f669988ba90>
               │        └ <jumpscale.sals.marketplace.deployer.MarketPlaceDeployer object at 0x7f66998acca0>
               └ 71

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/farms.py", line 103, in get
    resp = self._session.get(f"{self._url}/{farm_id}")
           │    │        └ <function Session.get at 0x7f669e270af0>
           │    └ <requests.sessions.Session object at 0x7f66995f3670>
           └ <jumpscale.clients.explorer.farms.Farms object at 0x7f66995f3f70>

  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
           │    │              │      └ {'allow_redirects': True}
           │    │              └ 'https://explorer.testnet.grid.tf/api/v1/farms/71'
           │    └ <function Session.request at 0x7f669e270a60>
           └ <requests.sessions.Session object at 0x7f66995f3670>
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7f669e270ee0>
           └ <requests.sessions.Session object at 0x7f66995f3670>
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
    │   │                         │      │    └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
    │   │                         │      └ <Response [404]>
    │   │                         └ {'response': [<function log_request at 0x7f669bd7ea60>, <function raise_for_status at 0x7f669bef8700>]}
    │   └ <function dispatch_hook at 0x7f669e2cdca0>
    └ <Response [404]>
  File "/usr/local/lib/python3.8/dist-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
    │            │    │            └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
    │            │    └ <Response [404]>
    │            └ <function raise_for_status at 0x7f669bef8700>
    └ None

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/errors.py", line 23, in raise_for_status
    raise HTTPError(http_error_msg, response=resp)
          │         │                        └ <Response [404]>
          │         └ '404 Client Error: mongo: no documents in result for url: https://explorer.testnet.grid.tf/api/v1/farms/71'
          └ <class 'requests.exceptions.HTTPError'>

requests.exceptions.HTTPError: 404 Client Error: mongo: no documents in result for url: https://explorer.testnet.grid.tf/api/v1/farms/71

```

**Comment by ranatrk** [comment]
worked with rebasing development_vdc branch with development fix to include https://github.com/threefoldtech/js-sdk/commit/80d7f2a0e793efa38c0405fd3dd4b54b09b259d9
![Screenshot from 2021-01-19 12-07-13](https://user-images.githubusercontent.com/17128393/105019776-271c1480-5a4f-11eb-954d-b35823666abf.png)
