### ISSUE TITLE
starting a  threebot server  osx crashes

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#232]
```
poetry update
poetry install
poetry shell
threebot start
```
![image](https://user-images.githubusercontent.com/46320202/87299466-5be16900-c50c-11ea-97f4-bea0a9931b96.png)

full stack trace
```
2020-07-13 14:39:36.149 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - jumpscale.core.exceptions.exceptions.Runtime: Error happened during getting or installing auth package, the detailed error is string indices must be integers
Traceback (most recent call last):

  File "/Users/codescalers/Documents/js-sdk/jumpscale/servers/threebot/threebot.py", line 607, in start
    package = self.packages.get(package_name)
              │    │            └ 'auth'
              │    └ <property object at 0x108bc4c70>
              └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/Users/codescalers/Documents/js-sdk/jumpscale/servers/threebot/threebot.py", line 292, in get
    package_path = self.packages[package_name]["path"]
                   │    │        └ 'auth'
                   │    └ <property object at 0x108bc4950>
                   └ PackageManager(_Base__instance_name='default', _Base__parent=ThreebotServer(_Base__instance_name='default', _Base__parent=Non...

TypeError: string indices must be integers


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
> File "/Users/codescalers/Library/Caches/pypoetry/virtualenvs/js-sdk-psk1tOSq-py3.8/bin/threebot", line 11, in <module>
    load_entry_point('js-sdk', 'console_scripts', 'threebot')()
    └ <function load_entry_point at 0x1060a2700>
  File "/Users/codescalers/Library/Caches/pypoetry/virtualenvs/js-sdk-psk1tOSq-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x106aac1f0>
           └ <Group cli>
  File "/Users/codescalers/Library/Caches/pypoetry/virtualenvs/js-sdk-psk1tOSq-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x1063390a0>
         │    └ <function MultiCommand.invoke at 0x106aacf70>
         └ <Group cli>
  File "/Users/codescalers/Library/Caches/pypoetry/virtualenvs/js-sdk-psk1tOSq-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x105aa7b80>
           │               │       │       └ <function Command.invoke at 0x106aacb80>
           │               │       └ <Command start>
           │               └ <click.core.Context object at 0x105aa7b80>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x1060a25e0>
  File "/Users/codescalers/Library/Caches/pypoetry/virtualenvs/js-sdk-psk1tOSq-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'identity': None, 'background': False, 'local': False}
           │   │      │    │           └ <click.core.Context object at 0x105aa7b80>
           │   │      │    └ <function start at 0x108863dc0>
           │   │      └ <Command start>
           │   └ <function Context.invoke at 0x106aabca0>
           └ <click.core.Context object at 0x105aa7b80>
  File "/Users/codescalers/Library/Caches/pypoetry/virtualenvs/js-sdk-psk1tOSq-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'identity': None, 'background': False, 'local': False}
           │         └ ()
           └ <function start at 0x108863dc0>

  File "/Users/codescalers/Documents/js-sdk/jumpscale/entry_points/threebot.py", line 124, in start
    j.servers.threebot.start_default(wait=True, local=local)
    │ │                                         │     └ False
    │ │                                         └ False
    │ └ <property object at 0x106ab39f0>
    └ <jumpscale.loader.J object at 0x106aa7760>

  File "/Users/codescalers/Documents/js-sdk/jumpscale/servers/threebot/__init__.py", line 29, in start_default
    server.start(wait=wait)
    │      │     │    └ True
    │      │     └ True
    │      └ <function ThreebotServer.start at 0x108bcaa60>
    └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/Users/codescalers/Documents/js-sdk/jumpscale/servers/threebot/threebot.py", line 611, in start
    raise j.core.exceptions.Runtime(
          │ └ <property object at 0x106ab3860>
          └ <jumpscale.loader.J object at 0x106aa7760>

jumpscale.core.exceptions.exceptions.Runtime: Error happened during getting or installing auth package, the detailed error is string indices must be integers
```

**Comment by xmonader** [comment]
can you send more complete stack trace please, and in text.

**Comment by RafyAmgadBenjamin** [comment]
I have updated the issue with a full stack trace in text

**Comment by ashraffouda** [comment]
the macosx machine already has an old configuration for the "default" threebot server instance, deleting the default instance fixed it

**Comment by RafyAmgadBenjamin** [comment]
verified it is working now
![image](https://user-images.githubusercontent.com/46320202/87313766-a79f0d00-c522-11ea-88c2-e10b81424e70.png)
