### ISSUE TITLE
Error in mnemonic words

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#245]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-sEfpU_Ir-py3.6/src/js-ng/jumpscale/core/base/factory.py", line 206, in get
    instance = self.find(name)
               │         └ 'main'
               └ <jumpscale.core.base.factory.jumpscalecoreidentityIdentity object at 0x7f9bef44a780>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-sEfpU_Ir-py3.6/src/js-ng/jumpscale/core/base/factory.py", line 439, in find
    instance = super().find(name)
                            └ 'main'
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-sEfpU_Ir-py3.6/src/js-ng/jumpscale/core/base/factory.py", line 129, in find
    instance = getattr(self, name, None)
                       │     └ 'main'
                       └ <jumpscale.core.base.factory.jumpscalecoreidentityIdentity object at 0x7f9bef44a780>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-sEfpU_Ir-py3.6/src/js-ng/jumpscale/core/base/factory.py", line 492, in getter
    instance = self._get_object_from_config(name, factory.store.get(name))
               │                            │     │                 └ 'main'
               │                            │     └ <jumpscale.core.base.factory.jumpscalecoreidentityIdentity object at 0x7f9bef44a780>
               │                            └ 'main'
               └ <jumpscale.core.base.factory.jumpscalecoreidentityIdentity object at 0x7f9bef44a780>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-sEfpU_Ir-py3.6/src/js-ng/jumpscale/core/base/factory.py", line 404, in _get_object_from_config
    instance = self._create_instance(name, **data)
               │                     │       └ {'_tid': 195, 'words': 'panda foil grit addict snake dwarf quality swallow copper grunt swallow repair arm forward myself earl n...
               │                     └ 'main'
               └ <jumpscale.core.base.factory.jumpscalecoreidentityIdentity object at 0x7f9bef44a780>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-sEfpU_Ir-py3.6/src/js-ng/jumpscale/core/base/factory.py", line 161, in _create_instance
    instance = self.type(*args, **kwargs)
               │          │       └ {'_tid': 195, 'words': 'panda foil grit addict snake dwarf quality swallow copper grunt swallow repair arm forward myself earl n...
               │          └ ()
               └ <jumpscale.core.base.factory.jumpscalecoreidentityIdentity object at 0x7f9bef44a780>
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/core/identity/__init__.py", line 46, in __init__
    self.verify_configuration()
    └ Identity(_Base__instance_name='main', _Base__parent=None, ___tid=195, __admins=['play.3bot', 'waleedhammam.3bot', 'ranatarek.3bo...
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/core/identity/__init__.py", line 69, in verify_configuration
    if self.nacl.get_verify_key_hex() != user.pubkey:
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/core/identity/__init__.py", line 51, in nacl
    seed = mnemonic.mnemonic_to_key(self.words.strip())
           │                        └ Identity(_Base__instance_name='main', _Base__parent=None, ___tid=195, __admins=['play.3bot', 'waleedhammam.3bot', 'ranatarek.3bo...
           └ <module 'jumpscale.data.encryption.mnemonic' from '/root/.cache/pypoetry/virtualenvs/js-sdk-sEfpU_Ir-py3.6/src/js-ng/jumpscale/d...
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-sEfpU_Ir-py3.6/src/js-ng/jumpscale/data/encryption/mnemonic.py", line 60, in mnemonic_to_key
    raise exceptions.NotFound('Unable to find "%s" in word list.' % word)
          │                                                         └ 'earl'
          └ <module 'jumpscale.core.exceptions' from '/root/.cache/pypoetry/virtualenvs/js-sdk-sEfpU_Ir-py3.6/src/js-ng/jumpscale/core/excep...
jumpscale.core.exceptions.exceptions.NotFound: Unable to find "earl" in word list.
```

**Comment by waleedhammam** [comment]
special case for @ahelsayd identity 😁

**Comment by waleedhammam** [comment]
wrong input from user
