### ISSUE TITLE
VDC: Can't deploy solution after adding and deleting a node

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2492]
### Steps

1- Deploy a vdc
2- Add kubernetes node
3- Delete the node has been added.
4- Try to install any solution from the marketplace.

### Result

![image](https://user-images.githubusercontent.com/41957921/107254063-9cbc4480-6a3f-11eb-9afe-028d4adcc3ec.png)

### Error

```
2021-02-08 18:25:16 | Traceback (most recent call last):\n
-- | --
  |   | 2021-02-08 18:25:16 | \n
  |   | 2021-02-08 18:25:16 | File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 202, in wrapper\n
  |   | 2021-02-08 18:25:16 | self._execute_current_step(spawn=False)\n
  |   | 2021-02-08 18:25:16 | │    └ <function GedisChatBot._execute_current_step at 0x7f9581374940>\n
  |   | 2021-02-08 18:25:16 | └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f9580962610>\n
  |   | 2021-02-08 18:25:16 | \n
  |   | 2021-02-08 18:25:16 | File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 210, in _execute_current_step\n
  |   | 2021-02-08 18:25:16 | wrapper(step_name)\n
  |   | 2021-02-08 18:25:16 | │       └ 'create_subdomain'\n
  |   | 2021-02-08 18:25:16 | └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f95807d3790>\n
  |   | 2021-02-08 18:25:16 | \n
  |   | 2021-02-08 18:25:16 | File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 202, in wrapper\n
  |   | 2021-02-08 18:25:16 | self._execute_current_step(spawn=False)\n
  |   | 2021-02-08 18:25:16 | │    └ <function GedisChatBot._execute_current_step at 0x7f9581374940>\n
  |   | 2021-02-08 18:25:16 | └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f9580962610>\n
  |   | 2021-02-08 18:25:16 | \n
  |   | 2021-02-08 18:25:16 | File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 210, in _execute_current_step\n
  |   | 2021-02-08 18:25:16 | wrapper(step_name)\n
  |   | 2021-02-08 18:25:16 | │       └ 'set_config'\n
  |   | 2021-02-08 18:25:16 | └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f9580645700>\n
  |   | 2021-02-08 18:25:16 | \n
  |   | 2021-02-08 18:25:16 | > File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper\n
  |   | 2021-02-08 18:25:16 | getattr(self, step_name)()\n
  |   | 2021-02-08 18:25:16 | │     └ 'set_config'\n
  |   | 2021-02-08 18:25:16 | └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f9580962610>\n
  |   | 2021-02-08 18:25:16 | \n
  |   | 2021-02-08 18:25:16 | File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper\n
  |   | 2021-02-08 18:25:16 | return func(*args, **kwargs)\n
  |   | 2021-02-08 18:25:16 | │     │       └ {}\n
  |   | 2021-02-08 18:25:16 | │     └ (<vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f9580962610>,)\n
  |   | 2021-02-08 18:25:16 | └ <function CryptpadDeploy.set_config at 0x7f9580a1a0d0>\n
  |   | 2021-02-08 18:25:16 | \n
  |   | 2021-02-08 18:25:16 | File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/chats/cryptpad.py", line 14, in set_config\n
  |   | 2021-02-08 18:25:16 | self._choose_flavor()\n
  |   | 2021-02-08 18:25:16 | │    └ <function SolutionsChatflowDeploy._choose_flavor at 0x7f9580a10dc0>\n
  |   | 2021-02-08 18:25:16 | └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f9580962610>\n
  |   | 2021-02-08 18:25:16 | \n
  |   | 2021-02-08 18:25:16 | File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py", line 84, in _choose_flavor\n
  |   | 2021-02-08 18:25:16 | self._validate_resource_limits(cpu, memory, no_nodes)\n
  |   | 2021-02-08 18:25:16 | │    │                         │    │       └ 1\n
  |   | 2021-02-08 18:25:16 | │    │                         │    └ 1024\n
  |   | 2021-02-08 18:25:16 | │    │                         └ 1000\n
  |   | 2021-02-08 18:25:16 | │    └ <function SolutionsChatflowDeploy._validate_resource_limits at 0x7f9580a10e50>\n
  |   | 2021-02-08 18:25:16 | └ <vdc_dashboard.chats.cryptpad.CryptpadDeploy object at 0x7f9580962610>\n
  |   | 2021-02-08 18:25:16 | \n
  |   | 2021-02-08 18:25:16 | File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py", line 91, in _validate_resource_limits\n
  |   | 2021-02-08 18:25:16 | if not monitor.check_deployment_resources(queries):\n
  |   | 2021-02-08 18:25:16 | │       │                          └ [{'cpu': 1000, 'memory': 1024}]\n
  |   | 2021-02-08 18:25:16 | │       └ <function KubernetesMonitor.check_deployment_resources at 0x7f9580ab39d0>\n
  |   | 2021-02-08 18:25:16 | └ <jumpscale.sals.vdc.kubernetes_auto_extend.KubernetesMonitor object at 0x7f9580637d60>\n
  |   | 2021-02-08 18:25:16 | \n
  |   | 2021-02-08 18:25:16 | File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/vdc/kubernetes_auto_extend.py", line 230, in check_deployment_resources\n
  |   | 2021-02-08 18:25:16 | node_reservations = self.fetch_resource_reservations()\n
  |   | 2021-02-08 18:25:16 | │    └ <function KubernetesMonitor.fetch_resource_reservations at 0x7f9580ab3a60>\n
  |   | 2021-02-08 18:25:16 | └ <jumpscale.sals.vdc.kubernetes_auto_extend.KubernetesMonitor object at 0x7f9580637d60>\n
  |   | 2021-02-08 18:25:16 | \n
  |   | 2021-02-08 18:25:16 | File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/vdc/kubernetes_auto_extend.py", line 217, in fetch_resource_reservations\n
  |   | 2021-02-08 18:25:16 | total_cpu=resv["total_cpu"],\n
  |   | 2021-02-08 18:25:16 | └ {'cpu': 0.0, 'memory': 0.0}\n
  |   | 2021-02-08 18:25:16 | \n
  |   | 2021-02-08 18:25:16 | KeyError: 'total_cpu'\n
```

**Comment by AhmedHanafy725** [comment]
**Verified**
on the same vdc after updating it with the lastest code

![image](https://user-images.githubusercontent.com/41957921/107338955-cbc8c980-6ac4-11eb-8400-9e33cafe30cf.png)
