### ISSUE TITLE
3BOT: Type something and remove it in required box in chatflows, becomes not required

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2504]
### Steps
1- Create a pool from admin dashboard
2- Set all units except ipv4u
3- Click next

![image](https://user-images.githubusercontent.com/41957921/107505991-21c16e00-6ba6-11eb-8c33-46bdbea030f7.png)

### Result

![image](https://user-images.githubusercontent.com/41957921/107506057-39005b80-6ba6-11eb-96ff-bd05e85da65a.png)

### Logs

```bash
Traceback (most recent call last):

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 202, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f1ebd5a4940>
    └ <tfgrid_solutions.chats.pools.PoolReservation object at 0x7f1ebd5c9ca0>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 210, in _execute_current_step
    wrapper(step_name)
    │       └ 'reserve_pool'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f1ebd5dcaf0>

> File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
            │     └ 'reserve_pool'
            └ <tfgrid_solutions.chats.pools.PoolReservation object at 0x7f1ebd5c9ca0>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<tfgrid_solutions.chats.pools.PoolReservation object at 0x7f1ebd5c9ca0>,)
           └ <function PoolReservation.reserve_pool at 0x7f1ebd3b93a0>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/tfgrid_solutions/chats/pools.py", line 36, in reserve_pool
    self.pool_data = deployer.create_pool(self)
    │                │        │           └ <tfgrid_solutions.chats.pools.PoolReservation object at 0x7f1ebd5c9ca0>
    │                │        └ <function ChatflowDeployer.create_pool at 0x7f1e7ce051f0>
    │                └ <jumpscale.sals.reservation_chatflow.deployer.ChatflowDeployer object at 0x7f1e7cdfdc40>
    └ <tfgrid_solutions.chats.pools.PoolReservation object at 0x7f1ebd5c9ca0>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 412, in create_pool
    cu, su, ipv4u, currencies = self._pool_form(bot)
                                │    │          └ <tfgrid_solutions.chats.pools.PoolReservation object at 0x7f1ebd5c9ca0>
                                │    └ <function ChatflowDeployer._pool_form at 0x7f1e7ce05160>
                                └ <jumpscale.sals.reservation_chatflow.deployer.ChatflowDeployer object at 0x7f1e7cdfdc40>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 378, in _pool_form
    form.ask(
    │    └ <function Form.ask at 0x7f1ebd5a1f70>
    └ <jumpscale.sals.chatflows.chatflows.Form object at 0x7f1ebc27d0d0>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 41, in ask
    resobject.value = result
    │         │       └ ''
    │         └ <property object at 0x7f1ebd372860>
    └ <jumpscale.sals.chatflows.chatflows.Result object at 0x7f1e7ccf2220>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 26, in value
    self._value = self._loader(value)
    │    │        │    │       └ ''
    │    │        │    └ <class 'int'>
    │    │        └ <jumpscale.sals.chatflows.chatflows.Result object at 0x7f1e7ccf2220>
    │    └ None
    └ <jumpscale.sals.chatflows.chatflows.Result object at 0x7f1e7ccf2220>

ValueError: invalid literal for int() with base 10: ''
```

**Comment by AhmedHanafy725** [comment]
After another try, I found that the ipv4u is required, but anything typed in any box and removed, becomes not required

**Comment by MElborolossy** [comment]
Verified
commit d0eea8f1482459bd507ba0bfcca889be09023f6a
![check_required](https://user-images.githubusercontent.com/11272864/108965022-f0a46b80-7684-11eb-9ee6-ecc61b524b2a.gif)
