### ISSUE TITLE
can't deploy VDC from local server

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#2572]
### Description
I have difficulties deploying a VDC from a local VDC server.

the first problem, trying to deploy one, the server complains that the system doesn't have activation_wallet configured

![Screenshot from 2021-02-18 11-04-50](https://user-images.githubusercontent.com/42457449/108334180-58b50680-71da-11eb-8257-a76dc240379e.png)

I tried to manually import our wallet with required wallet names, vdc_init, and grace_period

![Screenshot from 2021-02-18 11-18-35](https://user-images.githubusercontent.com/42457449/108335251-674fed80-71db-11eb-82a9-bfceca90e2c2.png)

then the server will start the chat-flow asking about the VDC information.

![Screenshot from 2021-02-18 11-17-55](https://user-images.githubusercontent.com/42457449/108335293-733baf80-71db-11eb-8f49-b232b8b0a784.png)

filling the form and preceding, it asks me to scan the QR using the threefold connect mobile application, doing so, the transaction will succeed (from the wallet side), and the TFT deducted from the wallet, but from the server-side, it will keep waiting for the payment and eventually timeout.

![Screenshot from 2021-02-18 11-25-35](https://user-images.githubusercontent.com/42457449/108336166-6cfa0300-71dc-11eb-9fea-1ec08aa422a2.png)

thought the deployment fail, TFT didn't refund.

### Version information

* OS: Ubuntu 20.04
* Branch: development_vdc
* Browser: e.g. chrome 88

### Traceback/Logs/Alerts

Traceback/Logs/Alerts if available
------------------
**activation_wallet**
------------------

2021-02-18 11:04:09.474 | INFO     | vdc.chats.new_vdc:_init:34 - this system doesn't have activation_wallet configured
2021-02-18 11:04:10.285 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:150 - chatflow stopped in step vdc_info. exception: (StopChatFlow(...), "couldn't get the balance for vdc_init wallet")
Traceback (most recent call last):

  File "/home/sameh/projects/js-sdk/jumpscale/packages/vdc/chats/new_vdc.py", line 40, in _init
    if w.get_balance_by_asset() < 50:
       │ └ <function Stellar.get_balance_by_asset at 0x7f050281ce18>
       └ Stellar(
           instance_name='vdc_init',
           network=<Network.STD: 'STD'>,
           address='GANTD6YCDADMIDFNRJW4FNDSWXZGNV4CGQXHBTSMJPYW2...

  File "/home/sameh/projects/js-sdk/jumpscale/clients/stellar/stellar.py", line 1122, in get_balance_by_asset
    balances = self.get_balance()
               │    └ <function Stellar.get_balance at 0x7f0502818ae8>
               └ Stellar(
                   instance_name='vdc_init',
                   network=<Network.STD: 'STD'>,
                   address='GANTD6YCDADMIDFNRJW4FNDSWXZGNV4CGQXHBTSMJPYW2...

  File "/home/sameh/projects/js-sdk/jumpscale/clients/stellar/stellar.py", line 154, in get_balance
    all_balances = self._get_free_balances(address)
                   │    │                  └ 'GANTD6YCDADMIDFNRJW4FNDSWXZGNV4CGQXHBTSMJPYW2P3JG35VT2M4'
                   │    └ <function Stellar._get_free_balances at 0x7f0502818620>
                   └ Stellar(
                       instance_name='vdc_init',
                       network=<Network.STD: 'STD'>,
                       address='GANTD6YCDADMIDFNRJW4FNDSWXZGNV4CGQXHBTSMJPYW2...

  File "/home/sameh/projects/js-sdk/jumpscale/clients/stellar/stellar.py", line 90, in _get_free_balances
    response = self._get_horizon_server().accounts().account_id(address).call()
               │    │                                           └ 'GANTD6YCDADMIDFNRJW4FNDSWXZGNV4CGQXHBTSMJPYW2P3JG35VT2M4'
               │    └ <function Stellar._get_horizon_server at 0x7f0502818598>
               └ Stellar(
                   instance_name='vdc_init',
                   network=<Network.STD: 'STD'>,
                   address='GANTD6YCDADMIDFNRJW4FNDSWXZGNV4CGQXHBTSMJPYW2...

  File "/home/sameh/projects/js-sdk/.venv/lib/python3.6/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 58, in call
    return self.__call(url, self.params)
           │           │    │    └ {}
           │           │    └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7f0503a86198>
           │           └ 'https://horizon.stellar.org/accounts/GANTD6YCDADMIDFNRJW4FNDSWXZGNV4CGQXHBTSMJPYW2P3JG35VT2M4'
           └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7f0503a86198>
  File "/home/sameh/projects/js-sdk/.venv/lib/python3.6/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 64, in __call
    return self.__call_sync(url, params)
           │                │    └ {}
           │                └ 'https://horizon.stellar.org/accounts/GANTD6YCDADMIDFNRJW4FNDSWXZGNV4CGQXHBTSMJPYW2P3JG35VT2M4'
           └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7f0503a86198>
  File "/home/sameh/projects/js-sdk/.venv/lib/python3.6/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 68, in __call_sync
    raise_request_exception(raw_resp)
    │                       └ <stellar_sdk.client.response.Response object at 0x7f05027ef908>
    └ <function raise_request_exception at 0x7f0503c34d90>
  File "/home/sameh/projects/js-sdk/.venv/lib/python3.6/site-packages/stellar_sdk/exceptions.py", line 207, in raise_request_exception
    raise NotFoundError(response)
          │             └ <stellar_sdk.client.response.Response object at 0x7f05027ef908>
          └ <class 'stellar_sdk.exceptions.NotFoundError'>

stellar_sdk.exceptions.NotFoundError: {
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

> File "/home/sameh/projects/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
            │     └ 'vdc_info'
            └ <vdc.chats.new_vdc.VDCDeploy object at 0x7f04fb4e0518>

  File "/home/sameh/projects/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<vdc.chats.new_vdc.VDCDeploy object at 0x7f04fb4e0518>,)
           └ <function VDCDeploy.vdc_info at 0x7f04fb48a1e0>

  File "/home/sameh/projects/js-sdk/jumpscale/packages/vdc/chats/new_vdc.py", line 143, in vdc_info
    self._init()
    │    └ <function VDCDeploy._init at 0x7f04fb47de18>
    └ <vdc.chats.new_vdc.VDCDeploy object at 0x7f04fb4e0518>

  File "/home/sameh/projects/js-sdk/jumpscale/packages/vdc/chats/new_vdc.py", line 43, in _init
    raise StopChatFlow(f"couldn't get the balance for {wname} wallet")
          └ <class 'jumpscale.sals.chatflows.chatflows.StopChatFlow'>

jumpscale.sals.chatflows.chatflows.StopChatFlow: (StopChatFlow(...), "couldn't get the balance for vdc_init wallet")

--------------------
**payment timeout**
--------------------

2021-02-18 11:23:41.955 | INFO     | jumpscale.sals.billing.billing:wait_payment:57 - payment: 90cecaf823c84a43aba00032096981c5 result False
2021-02-18 11:23:43.329 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:150 - chatflow stopped in step deploy. exception: (StopChatFlow(...), 'payment timedout')
Traceback (most recent call last):

  File "/home/sameh/projects/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 202, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f0500159268>
    └ <vdc.chats.new_vdc.VDCDeploy object at 0x7f05000eabe0>

  File "/home/sameh/projects/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 210, in _execute_current_step
    wrapper(step_name)
    │       └ 'deploy'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f04fb4b59d8>

> File "/home/sameh/projects/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
            │     └ 'deploy'
            └ <vdc.chats.new_vdc.VDCDeploy object at 0x7f05000eabe0>

  File "/home/sameh/projects/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<vdc.chats.new_vdc.VDCDeploy object at 0x7f05000eabe0>,)
           └ <function VDCDeploy.deploy at 0x7f04fb48a2f0>

  File "/home/sameh/projects/js-sdk/jumpscale/packages/vdc/chats/new_vdc.py", line 195, in deploy
    self.stop(f"payment timedout")
    │    └ <function GedisChatBot.stop at 0x7f050015ab70>
    └ <vdc.chats.new_vdc.VDCDeploy object at 0x7f05000eabe0>

  File "/home/sameh/projects/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 657, in stop
    raise StopChatFlow(msg=msg, **kwargs)
          │            │   │      └ {}
          │            │   └ 'payment timedout'
          │            └ 'payment timedout'
          └ <class 'jumpscale.sals.chatflows.chatflows.StopChatFlow'>

jumpscale.sals.chatflows.chatflows.StopChatFlow: (StopChatFlow(...), 'payment timedout')

**Comment by m-motawea** [comment]
is the billing service running or the billing package installed?

**Comment by xmonader** [comment]
I'll close this issue as @sameh-farouk now is going to be documenting that experience too
