### ISSUE TITLE
Browser not refresh after delete a release

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/js-sdk#2594]
### Description

After deleting any release, the browser doesn't refresh the page 

### Version information

* Browser: 
  - Chrome 88
  - Firefox 85 

### Traceback/Logs/Alerts

https://user-images.githubusercontent.com/11272864/108677822-e5213b00-74f2-11eb-82a0-dce5b41cf488.mp4

**Comment by waleedhammam** [comment]
@MElborolossy that happend with me when my vdc wasn't update, can you check the logs in console/shell you'll find it ;)

**Comment by MElborolossy** [comment]
@waleedhammam I have updated my VDC and the same issue
Here are more logs

```
  | 127.0.0.1 - - [2021-02-22 10:36:41] "POST /api/deployments/cancel/ HTTP/1.0" 500 936 32.355588\n
  | KeyError: 'solution_id'\n
  | j.sals.marketplace.solutions.cancel_solution_by_uuid(data["solution_id"])\n
  | File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/bottle/deployments.py", line 177, in cancel_deployment\n
  | return func(*args, **kwargs)\n
  | File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/auth/bottle/auth.py", line 370, in decorator\n
  | rv = callback(*a, **ka)\n
  | File "/usr/local/bin/bottle.py", line 1748, in wrapper\n
  | return route.call(**args)\n
  | File "/usr/local/bin/bottle.py", line 868, in _handle\n
  | Traceback (most recent call last):\n
```

**Comment by waleedhammam** [comment]
Verified on development_vdc
