### ISSUE TITLE
Cannot deploy container on node due to Alert 9 (invalid IPNetwork can't be retrieved)

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#2596]
I was trying to deploy a ubuntu container on the node 21dttvqfcRH6Bu3XyXPp3CqBs3soaVXCSkdhdQN6gstj on testnet , but got this error :

Steps to reproduce:
- All basic except do not allow IPv6 to be provisioned on workload , Select No

![image](https://user-images.githubusercontent.com/25789724/108694644-bddd6480-7518-11eb-9ca9-57192d8a49fa.png)

![image](https://user-images.githubusercontent.com/25789724/108694668-c6359f80-7518-11eb-8e1f-b25c21166795.png)

from the trace : 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netaddr/strategy/ipv4.py", line 125, in str_to_int
    return _struct.unpack('>I', _inet_pton(AF_INET, addr))[0]
OSError: illegal IP address string passed to inet_pton

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netaddr/ip/__init__.py", line 311, in __init__
    self._value = self._module.str_to_int(addr, flags)
  File "/usr/local/lib/python3.8/dist-packages/netaddr/strategy/ipv4.py", line 129, in str_to_int
    raise AddrFormatError('%r is not a valid IPv4 address string!' % (addr,))
netaddr.core.AddrFormatError: "can't be retrieved" is not a valid IPv4 address string!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netaddr/ip/__init__.py", line 791, in parse_ip_network
    ip = IPAddress(val1, module.version, flags=INET_PTON)
  File "/usr/local/lib/python3.8/dist-packages/netaddr/ip/__init__.py", line 313, in __init__
    raise AddrFormatError('base address %r is not IPv%d'
netaddr.core.AddrFormatError: base address "can't be retrieved" is not IPv4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netaddr/strategy/ipv4.py", line 265, in expand_partial_address
    tokens = ['%d' % int(addr)]
ValueError: invalid literal for int() with base 10: "can't be retrieved"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netaddr/ip/__init__.py", line 927, in __init__
    value, prefixlen = parse_ip_network(module, addr,
  File "/usr/local/lib/python3.8/dist-packages/netaddr/ip/__init__.py", line 795, in parse_ip_network
    expanded_addr = _ipv4.expand_partial_address(val1)
  File "/usr/local/lib/python3.8/dist-packages/netaddr/strategy/ipv4.py", line 267, in expand_partial_address
    raise error
netaddr.core.AddrFormatError: invalid partial IPv4 address: "can't be retrieved"!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/tfgrid_solutions/chats/ubuntu.py", line 119, in container_ip
    result = deployer.add_network_node(
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 940, in add_network_node
    network = network_view.add_node(node, pool_id)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 139, in add_node
    network_range = netaddr.IPNetwork(self.iprange)
  File "/usr/local/lib/python3.8/dist-packages/netaddr/ip/__init__.py", line 938, in __init__
    raise AddrFormatError('invalid IPNetwork %s' % (addr,))
netaddr.core.AddrFormatError: invalid IPNetwork can't be retrieved
```

This node is reachable on IPv6 also

**Comment by waleedhammam** [comment]
I've tested deployment on this node and worked ok, can you add the network workloads/deploy a new network and try again, perhaps the network became invalid
![Screenshot from 2021-02-24 17-46-57](https://user-images.githubusercontent.com/10658229/109026378-59f99e00-76c8-11eb-9b09-9b93a84c3d3e.png)

**Comment by xmonader** [comment]
couldn't reproduce, please reopen if it happens again.
