### ISSUE TITLE
Error happened during getting or installing auth package, the detailed error is string indices must be integers

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#274]
```
  js-sdk--OGPzDz5-py3.6   …/js-sdk     development   threebot start --local
2020-07-21 13:46:15.863 | INFO     | jumpscale.entry_points.threebot:check_for_bins:30 - ✅ binaries nginx,redis-server,tmux,git required are installed.
2020-07-21 13:46:15.907 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:53 - nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2020-07-21 13:46:15.907 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:53 - nginx: the configuration file /tmp/tmpr9ukebg1 syntax is ok
2020-07-21 13:46:15.907 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:53 - nginx: configuration file /tmp/tmpr9ukebg1 test is successful
Threebot server is running already or ports nginx:8999
are being held by your system
Please use threebot stop to stop your threebot server or free the ports to be able to start the threebot server
  js-sdk--OGPzDz5-py3.6   …/js-sdk     development   threbot stop     zsh: command not found: threbot
  js-sdk--OGPzDz5-py3.6   …/js-sdk     development   threebot stop    Threebot server Stopped
  js-sdk--OGPzDz5-py3.6   …/js-sdk     development   threebot start --local
2020-07-21 13:46:34.512 | INFO     | jumpscale.entry_points.threebot:check_for_bins:30 - ✅ binaries nginx,redis-server,tmux,git required are installed.
2020-07-21 13:46:34.551 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:53 - nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2020-07-21 13:46:34.551 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:53 - nginx: the configuration file /tmp/tmpmq38669o syntax is ok
2020-07-21 13:46:34.551 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:53 - nginx: configuration file /tmp/tmpmq38669o test is successful
2020-07-21 13:46:38.941 | INFO     | jumpscale.core.application.application:start:23 - Application gedis is started, process id: 21247
2020-07-21 13:46:38.943 | INFO     | jumpscale.core.application.application:start:23 - Application threebot_default is started, process id: 21247
2020-07-21 13:46:38.947 | INFO     | jumpscale.servers.threebot.threebot:start:618 - Configuring package auth
2020-07-21 13:46:39.640 | INFO     | jumpscale.core.application.application:stop:26 - Application threebot_default is stopped
2020-07-21 13:46:40.701 | INFO     | jumpscale.servers.gedis.server:stop:209 - Shutting down...
2020-07-21 13:46:40.794 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - jumpscale.core.exceptions.exceptions.Runtime: Error happened during getting or installing auth package, the detailed error is string indices must be integers
Traceback (most recent call last):

  File "/home/ahmed/wspace/js/js-sdk/jumpscale/servers/threebot/threebot.py", line 620, in start
    package = self.packages.get(package_name)
              │    │            └ 'auth'
              │    └ <property object at 0x7fcd2cd37bd8>
              └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/home/ahmed/wspace/js/js-sdk/jumpscale/servers/threebot/threebot.py", line 305, in get
    package_path = self.packages[package_name]["path"]
                   │    │        └ 'auth'
                   │    └ <property object at 0x7fcd2cd378b8>
                   └ PackageManager(_Base__instance_name='default', _Base__parent=ThreebotServer(_Base__instance_name='default', _Base__parent=Non...

TypeError: string indices must be integers


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
> File "/home/ahmed/.cache/pypoetry/virtualenvs/js-sdk--OGPzDz5-py3.6/bin/threebot", line 33, in <module>
    sys.exit(load_entry_point('js-sdk', 'console_scripts', 'threebot')())
    │   │    └ <function importlib_load_entry_point at 0x7fcd38827e18>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/ahmed/.cache/pypoetry/virtualenvs/js-sdk--OGPzDz5-py3.6/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fcd331d7510>
           └ <Group cli>
  File "/home/ahmed/.cache/pypoetry/virtualenvs/js-sdk--OGPzDz5-py3.6/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fcd35db4390>
         │    └ <function MultiCommand.invoke at 0x7fcd331d9268>
         └ <Group cli>
  File "/home/ahmed/.cache/pypoetry/virtualenvs/js-sdk--OGPzDz5-py3.6/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fcd370fe4a8>
           │               │       │       └ <function Command.invoke at 0x7fcd331d7e18>
           │               │       └ <Command start>
           │               └ <click.core.Context object at 0x7fcd370fe4a8>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fcd370fbb70>
  File "/home/ahmed/.cache/pypoetry/virtualenvs/js-sdk--OGPzDz5-py3.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'local': True, 'identity': None, 'background': False}
           │   │      │    │           └ <click.core.Context object at 0x7fcd370fe4a8>
           │   │      │    └ <function start at 0x7fcd2ef52268>
           │   │      └ <Command start>
           │   └ <function Context.invoke at 0x7fcd331d7048>
           └ <click.core.Context object at 0x7fcd370fe4a8>
  File "/home/ahmed/.cache/pypoetry/virtualenvs/js-sdk--OGPzDz5-py3.6/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'local': True, 'identity': None, 'background': False}
           │         └ ()
           └ <function start at 0x7fcd2ef52268>

  File "/home/ahmed/wspace/js/js-sdk/jumpscale/entry_points/threebot.py", line 140, in start
    j.servers.threebot.start_default(wait=True, local=local)
    │ │                                         │     └ True
    │ │                                         └ True
    │ └ <property object at 0x7fcd331e00e8>
    └ <jumpscale.loader.J object at 0x7fcd33211cf8>

  File "/home/ahmed/wspace/js/js-sdk/jumpscale/servers/threebot/__init__.py", line 29, in start_default
    server.start(wait=wait)
    │      │     │    └ True
    │      │     └ True
    │      └ <function ThreebotServer.start at 0x7fcd2cd3b730>
    └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/home/ahmed/wspace/js/js-sdk/jumpscale/servers/threebot/threebot.py", line 625, in start
    f"Error happened during getting or installing {package_name} package, the detailed error is {str(e)}"

jumpscale.core.exceptions.exceptions.Runtime: Error happened during getting or installing auth package, the detailed error is string indices must be integers
```

```
ipdb> print(package_name)                                                                                     
auth
ipdb> print(self.packages)                                                                                    
PackageManager(_Base__instance_name='default', _Base__parent=ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscaleserversthreebotthreebotThreebotServerdefault_package_managerjumpscaleserversthreebotthreebotPackageManager object at 0x7fe1f00bfcf8>, __domain=None, __email=None, _db=None, _factories={'_package_manager': <jumpscale.core.base.factory.jumpscaleserversthreebotthreebotThreebotServerdefault_package_managerjumpscaleserversthreebotthreebotPackageManager object at 0x7fe1f00bfcf8>}, _gedis=GedisServer(_Base__instance_name='threebot', _Base__parent=None, ___actors={}, __enable_system_actor=True, __host='127.0.0.1', __port=16000, __run_async=True, _core_actor=<jumpscale.servers.gedis.systemactor.CoreActor object at 0x7fe1f00e7c50>, _factories={}, _loaded_actors={'core': <jumpscale.servers.gedis.systemactor.CoreActor object at 0x7fe1f00e7c50>, 'system': <jumpscale.servers.gedis.systemactor.SystemActor object at 0x7fe1f00e7940>}, _server=<StreamServer at 0x7fe1eb650e48 fileno=8 address=127.0.0.1:16000 handle=<bound method GedisServer._on_connection of GedisServer(...)>>, _system_actor=<jumpscale.servers.gedis.systemactor.SystemActor object at 0x7fe1f00e7940>, save=functools.partial(<bound method StoredFactory._validate_and_save_instance of <jumpscale.core.base.factory.jumpscaleserversgedisserverGedisServer object at 0x7fe1f00bf860>>, GedisServer(...))), _gedis_http=GedisHTTPServer(_Base__instance_name='threebot', _Base__parent=None, __host='127.0.0.1', __port=8000, _app=<bottle.Bottle object at 0x7fe1f00b8668>, _client=None, _factories={}, save=functools.partial(<bound method StoredFactory._validate_and_save_instance of <jumpscale.core.base.factory.jumpscaleserversgedis_httpGedisHTTPServer object at 0x7fe1f00e79b0>>, GedisHTTPServer(...))), _nginx=NginxServer(_Base__instance_name='default', _Base__parent=None, __name='main', _factories={}, config_path='/home/ahmed/sandbox/cfg/nginx/main/nginx.conf', save=functools.partial(<bound method StoredFactory._validate_and_save_instance of <jumpscale.core.base.factory.jumpscaletoolsnginxnginxserverNginxServer object at 0x7fe1f00766a0>>, NginxServer(...))), _packages=PackageManager(...), _rack=ServerRack(_Base__instance_name=None, _Base__parent=None, _factories={}, _running_event=<gevent._event.Event object at 0x7fe1f01342e8>, _servers={'gedis': GedisServer(_Base__instance_name='threebot', _Base__parent=None, ___actors={}, __enable_system_actor=True, __host='127.0.0.1', __port=16000, __run_async=True, _core_actor=<jumpscale.servers.gedis.systemactor.CoreActor object at 0x7fe1f00e7c50>, _factories={}, _loaded_actors={'core': <jumpscale.servers.gedis.systemactor.CoreActor object at 0x7fe1f00e7c50>, 'system': <jumpscale.servers.gedis.systemactor.SystemActor object at 0x7fe1f00e7940>}, _server=<StreamServer at 0x7fe1eb650e48 fileno=8 address=127.0.0.1:16000 handle=<bound method GedisServer._on_connection of GedisServer(...)>>, _system_actor=<jumpscale.servers.gedis.systemactor.SystemActor object at 0x7fe1f00e7940>, save=functools.partial(<bound method StoredFactory._validate_and_save_instance of <jumpscale.core.base.factory.jumpscaleserversgedisserverGedisServer object at 0x7fe1f00bf860>>, GedisServer(...))), 'gedis_http': <WSGIServer at 0x7fe1f009b080 fileno=9 address=127.0.0.1:8000>}, _started={'gedis_http', 'gedis'}), _redis=RedisServer(_Base__instance_name='default', _Base__parent=None, __host='127.0.0.1', __port=6379, _cmd=StartupCmd(_Base__instance_name='redis_default', _Base__parent=None, _StartupCmd__tmux_window=None, __check_cmd=None, __ports=[6379], __process_strings=[], __process_strings_regex=[], __start_cmd='redis-server --bind 127.0.0.1 --port 6379', _cmd_path=None, _factories={}, _pid=None, _process=None, save=functools.partial(<bound method StoredFactory._validate_and_save_instance of <jumpscale.core.base.factory.jumpscaletoolsstartupcmdstartupcmdStartupCmd object at 0x7fe1f00bf550>>, StartupCmd(...))), _factories={}, save=functools.partial(<bound method StoredFactory._validate_and_save_instance of <jumpscale.core.base.factory.jumpscaletoolsredisredisRedisServer object at 0x7fe1eb627c50>>, RedisServer(...))), _started=False, save=functools.partial(<bound method StoredFactory._validate_and_save_instance of <jumpscale.core.base.factory.jumpscaleserversthreebotthreebotThreebotServer object at 0x7fe1f0164a20>>, ThreebotServer(...))), __packages={'auth': '/home/ahmed/wspace/js/js-sdk/jumpscale/packages/auth', 'chatflows': '/home/ahmed/wspace/js/js-sdk/jumpscale/packages/chatflows', 'admin': '/home/ahmed/wspace/js/js-sdk/jumpscale/packages/admin', 'admin_old': '/home/ahmed/wspace/js/js-sdk/jumpscale/packages/admin_old', 'weblibs': '/home/ahmed/wspace/js/js-sdk/jumpscale/packages/weblibs', 'tfgrid_solutions': '/home/ahmed/wspace/js/js-sdk/jumpscale/packages/tfgrid_solutions', 'tfta_sales': '/home/ahmed/wspace/js/tfta-trader/tfta_sales', 'polls': '/home/ahmed/wspace/js/js-sdk/jumpscale/packages/polls'}, _factories={}, _threebot=None, save=functools.partial(<bound method StoredFactory._validate_and_save_instance of <jumpscale.core.base.factory.jumpscaleserversthreebotthreebotThreebotServerdefault_package_managerjumpscaleserversthreebotthreebotPackageManager object at 0x7fe1f00bfcf8>>, PackageManager(...)))
ipdb> print(self.packages.list_all())                                                                         
dict_keys(['auth', 'chatflows', 'admin', 'admin_old', 'weblibs', 'tfgrid_solutions', 'tfta_sales', 'polls'])
ipdb> print(self.packages.get('auth'))                                                                        
*** TypeError: string indices must be integers
ipdb> print(self.packages.get('admin'))                                                                       
*** TypeError: string indices must be integers



ipdb> print(self.packages)                                                                                    
{'auth': '/home/ahmed/wspace/js/js-sdk/jumpscale/packages/auth', 'chatflows': '/home/ahmed/wspace/js/js-sdk/jumpscale/packages/chatflows', 'admin': '/home/ahmed/wspace/js/js-sdk/jumpscale/packages/admin', 'admin_old': '/home/ahmed/wspace/js/js-sdk/jumpscale/packages/admin_old', 'weblibs': '/home/ahmed/wspace/js/js-sdk/jumpscale/packages/weblibs', 'tfgrid_solutions': '/home/ahmed/wspace/js/js-sdk/jumpscale/packages/tfgrid_solutions', 'tfta_sales': '/home/ahmed/wspace/js/tfta-trader/tfta_sales', 'polls': '/home/ahmed/wspace/js/js-sdk/jumpscale/packages/polls'}
ipdb> n                                                                                                       
> /home/ahmed/wspace/js/js-sdk/jumpscale/servers/threebot/threebot.py(304)get()
    303     def get(self, package_name):
--> 304         if package_name in self.packages:
    305             package_path = self.packages[package_name]["path"]

ipdb> print(self.packages['auth'])                                                                            
/home/ahmed/wspace/js/js-sdk/jumpscale/packages/auth
```

**Comment by xmonader** [comment]
```
> cat ~/.config/jumpscale/secureconfig/jumpscale/servers/threebot/threebot/ThreebotServer/default/_package_manager/jumpscale/servers/threebot/threebot/PackageManager/default/data
{"packages": {"auth": "/home/ahmed/wspace/js/js-sdk/jumpscale/packages/auth", "chatflows": "/home/ahmed/wspace/js/js-sdk/jumpscale/packages/chatflows", "admin": "/home/ahmed/wspace/js/js-sdk/jumpscale/packages/admin", "admin_old": "/home/ahmed/wspace/js/js-sdk/jumpscale/packages/admin_old", "weblibs": "/home/ahmed/wspace/js/js-sdk/jumpscale/packages/weblibs", "tfgrid_solutions": "/home/ahmed/wspace/js/js-sdk/jumpscale/packages/tfgrid_solutions", "tfta_sales": "/home/ahmed/wspace/js/tfta-trader/tfta_sales", "polls": "/home/ahmed/wspace/js/js-sdk/jumpscale/packages/polls"}}%    
```
