### ISSUE TITLE
Release name can be repeated and fail in deployment

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/js-sdk#2740]
### Description

After using namespace, list deployed releases not working in the same way, this lead to allow duplicate release name which will fail the deployment after that.

![image](https://user-images.githubusercontent.com/41957921/110670215-d2d31c80-81d5-11eb-9d74-96392a516826.png)

### Traceback
```python
Traceback (most recent call last):
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py", line 399, in install_chart
    self.k8s_client.install_chart(
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/kubernetes/manager.py", line 25, in wrapper
    return method(self, *args, **kwargs)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/kubernetes/manager.py", line 123, in install_chart
    raise j.exceptions.Runtime(f"Failed to deploy chart {chart_name}, error was {err}")
jumpscale.core.exceptions.exceptions.Runtime: Failed to deploy chart /sandbox/code/github/threefoldtech/vdc-solutions-charts/charts/mattermost, error was WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/ahmed/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/ahmed/.kube/config
Error: cannot re-use a name that is still in use
```

### Steps to reproduce

- Deploy vdc
- Deploy any solution
- Deploy another one from the same solution

**Comment by weynandkuijpers** [comment]
Same / similar issue: https://github.com/threefoldtech/js-sdk/issues/2738

Tested double deployment with mattermost.

Two deployments on one cluster withough issues.

![screenshot_20210315_142532](https://user-images.githubusercontent.com/13766992/111139563-b7339180-859a-11eb-84f5-aba8c236d358.png)

Closed as issue no longer exists.
