### ISSUE TITLE
Error 500 in the vdc controller console log

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#2923]
- Needs a bit hardening 

### Traceback/Logs/Alerts

```

2021-04-14 11:55:13 | Traceback (most recent call last):\n
-- | --
  |   | 2021-04-14 11:55:13 | File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/bottle/deployments.py", line 319, in check_update\n
  |   | 2021-04-14 11:55:13 | latest_remote_tag = json_response[0]["tag_name"]\n
  |   | 2021-04-14 11:55:13 | KeyError: 0\n
  |   | 2021-04-14 11:55:13 | \n
  |   | 2021-04-14 11:55:13 | During handling of the above exception, another exception occurred:\n
  |   | 2021-04-14 11:55:13 | \n
  |   | 2021-04-14 11:55:13 | Traceback (most recent call last):\n
  |   | 2021-04-14 11:55:13 | File "/usr/local/bin/bottle.py", line 868, in _handle\n
  |   | 2021-04-14 11:55:13 | return route.call(**args)\n
  |   | 2021-04-14 11:55:14 | File "/usr/local/bin/bottle.py", line 1748, in wrapper\n
  |   | 2021-04-14 11:55:14 | rv = callback(*a, **ka)\n
  |   | 2021-04-14 11:55:14 | File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/auth/bottle/auth.py", line 349, in wrapper\n
  |   | 2021-04-14 11:55:14 | return function(*args, **kwargs)\n
  |   | 2021-04-14 11:55:14 | File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/bottle/deployments.py", line 321, in check_update\n
  |   | 2021-04-14 11:55:14 | raise j.exceptions.Runtime(f"Failed to fetch remote releases. {str(e)}")\n
  |   | 2021-04-14 11:55:14 | jumpscale.core.exceptions.exceptions.Runtime: Failed to fetch remote releases. 0\n


```

**Comment by dmahmouali** [comment]
the issue is API rate limit exceeded,

https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
```
## Rate limiting
For API requests using Basic Authentication or OAuth, 
you can make up to 5,000 requests per hour.
```

**Comment by waleedhammam** [comment]
@dmahmouali I think maybe we can harden it a bit, maybe we use .get instead of direct indexer. Also try except can be a fallback :D

**Comment by xmonader** [comment]
> the issue is API rate limit exceeded,
> 
> https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
> 
> ```
> ## Rate limiting
> For API requests using Basic Authentication or OAuth, 
> you can make up to 5,000 requests per hour.
> ```

But how, I don't think we ever reach 5000 request/hour?

**Comment by MElborolossy** [comment]
Verified
Branch: development
commit: 651486a10b2d2b1eeb64dfe580e8104989604ca8
Return 200 and empty response as no new release found
![image](https://user-images.githubusercontent.com/11272864/118971286-85122780-b96f-11eb-891f-e7cb69beda26.png)
