### ISSUE TITLE
'K8SNodeFlavor' object has no attribute 'upper'

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#2963]
### Description

stumbled upon this error while deploying Tiga

Looks like ’_check_added_worker_capacity’ method expects string but got Enum object

### Traceback/Logs/Alerts

```
[-] start: 2021-04-18 11:43:37.233 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:174 - error when executing step choose_flavor. exception: 'K8SNodeFlavor' object has no attribute 'upper'
[-] start: Traceback (most recent call last):
[-] start: 
[-] start:   File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 210, in wrapper
[-] start:     self._execute_current_step(spawn=False)
[-] start:     │    └ <function GedisChatBot._execute_current_step at 0x7f42882790d0>
[-] start:     └ <vdc_dashboard.chats.taiga.TaigaDeploy object at 0x7f42880c1d00>
[-] start: 
[-] start:   File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 218, in _execute_current_step
[-] start:     wrapper(step_name)
[-] start:     │       └ 'get_release_name'
[-] start:     └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f4283fb0a60>
[-] start: 
[-] start:   File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 210, in wrapper
[-] start:     self._execute_current_step(spawn=False)
[-] start:     │    └ <function GedisChatBot._execute_current_step at 0x7f42882790d0>
[-] start:     └ <vdc_dashboard.chats.taiga.TaigaDeploy object at 0x7f42880c1d00>
[-] start: 
[-] start:   File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 218, in _execute_current_step
[-] start:     wrapper(step_name)
[-] start:     │       └ 'choose_flavor'
[-] start:     └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f4283fbd310>
[-] start: 
[-] start: > File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 148, in wrapper
[-] start:     getattr(self, step_name)()
[-] start:             │     └ 'choose_flavor'
[-] start:             └ <vdc_dashboard.chats.taiga.TaigaDeploy object at 0x7f42880c1d00>
[-] start: 
[-] start:   File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 676, in wrapper
[-] start:     return func(*args, **kwargs)
[-] start:            │     │       └ {}
[-] start:            │     └ (<vdc_dashboard.chats.taiga.TaigaDeploy object at 0x7f42880c1d00>,)
[-] start:            └ <function SolutionsChatflowDeploy.choose_flavor at 0x7f428809ce50>
[-] start: 
[-] start:   File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py", line 396, in choose_flavor
[-] start:     self._validate_resource_limits(cpu, memory, no_nodes)
[-] start:     │    │                         │    │       └ 1
[-] start:     │    │                         │    └ 3024
[-] start:     │    │                         └ 3000
[-] start:     │    └ <function SolutionsChatflowDeploy._validate_resource_limits at 0x7f428809c5e0>
[-] start:     └ <vdc_dashboard.chats.taiga.TaigaDeploy object at 0x7f42880c1d00>
[-] start: 
[-] start:   File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py", line 106, in _validate_resource_limits
[-] start:     wids = monitor.extend(bot=self)
[-] start:            │       │          └ <vdc_dashboard.chats.taiga.TaigaDeploy object at 0x7f42880c1d00>
[-] start:            │       └ <function KubernetesMonitor.extend at 0x7f42881ea040>
[-] start:            └ <jumpscale.sals.vdc.kubernetes_auto_extend.KubernetesMonitor object at 0x7f4283ec8df0>
[-] start: 
[-] start:   File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/vdc/kubernetes_auto_extend.py", line 179, in extend
[-] start:     farm_name, capacity_check = deployer.find_worker_farm(flavor, farm_name)
[-] start:     │                           │        │                │       └ None
[-] start:     │                           │        │                └ <K8SNodeFlavor.MEDIUM: 17>
[-] start:     │                           │        └ <function VDCDeployer.find_worker_farm at 0x7f4288190790>
[-] start:     │                           └ <jumpscale.sals.vdc.deployer.VDCDeployer object at 0x7f4283ee7b80>
[-] start:     └ None
[-] start: 
[-] start:   File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/vdc/deployer.py", line 561, in find_worker_farm
[-] start:     return farm_name, self._check_added_worker_capacity(flavor, farm_name)
[-] start:            │          │    │                            │       └ 'lochristi_dev_lab'
[-] start:            │          │    │                            └ <K8SNodeFlavor.MEDIUM: 17>
[-] start:            │          │    └ <function VDCDeployer._check_added_worker_capacity at 0x7f4288190670>
[-] start:            │          └ <jumpscale.sals.vdc.deployer.VDCDeployer object at 0x7f4283ee7b80>
[-] start:            └ 'lochristi_dev_lab'
[-] start: 
[-] start:   File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/vdc/deployer.py", line 569, in _check_added_worker_capacity
[-] start:     node_flavor_size = VDC_SIZE.K8SNodeFlavor[flavor.upper()]
[-] start:                        │        │             └ <K8SNodeFlavor.MEDIUM: 17>
[-] start:                        │        └ <property object at 0x7f42881894f0>
[-] start:                        └ <jumpscale.sals.vdc.size.VDCSize object at 0x7f428815d880>
[-] start: 
[-] start: AttributeError: 'K8SNodeFlavor' object has no attribute 'upper'
```

**Comment by sameh-farouk** [comment]
#### fixed
#### Branch
`development_auto_extend_fix`
#### PR
https://github.com/threefoldtech/js-sdk/pull/2967
