### ISSUE TITLE
VDC : Less resources error despite having enough and all resources free

### ISSUE THREAD

**Issue by abdulgig** [threefoldtech/js-sdk#3040]
### Description

We deployed a new silver VDC and extended the cluster by adding a BIG worker node to it. However, whenever we try to deploy the Digibyte node, it gives the error ```There are not enough resources to deploy```. All resources are free and the nodes within the cluster are "Ready"

### VDC Info

VDC Name = rudy8
3bot = mazraa.3bot

### Alerts / Errors /  Tracebacks

```
NAME         STATUS   ROLES    AGE   VERSION
k3os-20078   Ready    <none>   37m   v1.19.4+k3s1
k3os-28569   Ready    <none>   48m   v1.19.4+k3s1
k3os-24486   Ready    master   49m   v1.19.4+k3s1
```

![image](https://user-images.githubusercontent.com/25789764/116599266-eb8bc300-a938-11eb-913f-760d8e6e3b9d.png)

![image](https://user-images.githubusercontent.com/25789764/116599992-d499a080-a939-11eb-9998-2b0f8509a455.png)

**Comment by waleedhammam** [comment]
After some investigation

```
JS-NG> j.tools.vdc.reporting.report_vdc_status("vdc_rudy8_mazraa")                                                                                                                                            

Getting VDC information ...

Creation time: 29/04/2021, 17:28:55
Expiration time: 15/05/2021, 12:39:46
Flavor: silver
Grace Period:  No
Master IP:  185.206.122.16  --> State: Up
Threebot IP: 10.200.2.3
Threebot Domain: mazraa-rudy8.vdctest.grid.tf  --> State Down

+Wallets--------------------------------------------+----------------------------------------------------------+---------------+
| Name                                              | Address                                                  | Balance       |
+---------------------------------------------------+----------------------------------------------------------+---------------+
| prepaid_wallet_263a7b04fdc24d158423647e5dcd0dd3   | GCQATPN7STXK4QOGQM7IIRKS5AFCPBNIGINWS5V7TND565BSCXGBEXKG | 0.0406140 TFT |
| provision_wallet_263a7b04fdc24d158423647e5dcd0dd3 | GAU2NJVW6EASZ2XZ2UGJYDRDTSJBGU7WJHN7QWVFD4JIJGE4LEFMODDM | 3.4046570 TFT |
+---------------------------------------------------+----------------------------------------------------------+---------------+


+Workloads--------------+---------+-----------+--------+-----------+----------------------------------------------+---------+---------+
| Wid   | Type          | State   | Farm      | PoolID | IPv4Units | NodeID                                       | NState  | Message |
+-------+---------------+---------+-----------+--------+-----------+----------------------------------------------+---------+---------+
| 36138 | Zdb           | DEPLOY  | freefarm  | 21314  | 0.0       | 26ZATmd3K1fjeQKQsi8Dr7bm9iSRa3ePsV8ubMcbZEuY | Up      |         |
| 36139 | Zdb           | DEPLOY  | freefarm  | 21314  | 0.0       | DJoL9ZV53K5YQurmxor2BLWTPf3WA9dT3RsFWeDeAx1z | Up      |         |
| 36140 | Zdb           | DEPLOY  | freefarm  | 21314  | 0.0       | 85J3zEvcqDoPaN7qQHRQ2QgPVcYdCvp8JmRY5qAwzxfm | Up      |         |
| 36141 | Zdb           | DEPLOY  | freefarm  | 21314  | 0.0       | 3ksZcDF1yNH5S4ndEDXH3Jnp5cowh4ko8888jKepAD4a | Up      |         |
| 36142 | Zdb           | DEPLOY  | freefarm  | 21314  | 0.0       | APxTCEYX2YjF9dgDGwRrGsi6gNmQ1a1rzgXaHrAAdbST | Up      |         |
| 36143 | Zdb           | DEPLOY  | freefarm  | 21314  | 0.0       | EMg1z3up8UcYNK5Rbfya7kKkKsuyqhNWrv15JKHERbuW | Up      |         |
| 36144 | Zdb           | DEPLOY  | freefarm  | 21314  | 0.0       | DHjz97zzNY1BxpVZ1mmv3gwwmPRN9oB91pSjeRVDZe6A | Up      |         |
| 36146 | Zdb           | DEPLOY  | freefarm  | 21314  | 0.0       | 3pRRo2s6h1XPSiNY5W98nPUUmWYN5NzrvyUCkpFugfL7 | Up      |         |
| 36148 | Zdb           | DEPLOY  | freefarm  | 21314  | 0.0       | BhAgw6PMUUETKQmZCCGqfNF2Pt4n6FKW4D8p7yY7hWpQ | Up      |         |
| 36149 | Zdb           | DEPLOY  | freefarm  | 21314  | 0.0       | 7e8iFD2inToLQzqTp855SpYf8LfVt9K3MUzrTWoqtvov | Up      |         |
| 36153 | Kubernetes    | DEPLOY  | freefarm2 | 21315  | 808313.0  | FbMBh3gGX5WLkcVgvxtTZ32ZiQwoAUUfcDvdMp8fLP8H | Up      |         |
| 36160 | Kubernetes    | DELETED | freefarm2 | 21315  | 808312.0  | A54PL8EPQHC1SefcFcnLKaqurw8nBNTSFsFriYowYP1a | Up      |         |
| 36162 | Subdomain     | DEPLOY  | Gateway   | 21317  | 0.0       | 9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2 | Gateway |         |
| 36163 | Reverse_proxy | DEPLOY  | Gateway   | 21317  | 0.0       | 9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2 | Gateway |         |
| 36164 | Container     | DEPLOY  | freefarm2 | 21315  | 808312.0  | FbMBh3gGX5WLkcVgvxtTZ32ZiQwoAUUfcDvdMp8fLP8H | Up      |         |
| 36173 | Kubernetes    | DEPLOY  | freefarm  | 21314  | 0.0       | 3VBKrSTVieFzJ9Bv9MSzvQBQcTwnxgPhC9tMNsUsv5BH | Up      |         |
| 36669 | Kubernetes    | DELETED | freefarm  | 21314  | 0.0       | BhAgw6PMUUETKQmZCCGqfNF2Pt4n6FKW4D8p7yY7hWpQ | Up      |         |
+-------+---------------+---------+-----------+--------+-----------+----------------------------------------------+---------+---------+
```

The workers were deleted but it's marked as not ready

```
k3os-24486 [~]$ kubectl get nodes
NAME         STATUS     ROLES    AGE     VERSION
k3os-28569   NotReady   <none>   4d15h   v1.19.4+k3s1
k3os-13379   NotReady   <none>   2d2h    v1.19.4+k3s1
k3os-24486   Ready      master   4d15h   v1.19.4+k3s1
k3os-20078   Ready      <none>   4d15h   v1.19.4+k3s1
```

I think that's because there were some deployed workloads on it and tried to delete
```
k3os-24486 [~]$ kubectl get pod -A
NAMESPACE     NAME                                         READY   STATUS        RESTARTS   AGE
k3os-system   system-upgrade-controller-6c9f84cb79-gtpgq   1/1     Running       0          4d15h
kube-system   local-path-provisioner-7ff9579c6-v82sl       1/1     Running       0          4d15h
kube-system   metrics-server-7b4f8b595-dfrmp               1/1     Running       0          4d15h
kube-system   coredns-66c464876b-vkhsz                     1/1     Running       0          4d15h
kube-system   helm-install-traefik-74ng5                   0/1     Completed     0          4d15h
velero        restic-k8gp5                                 1/1     Running       0          4d15h
velero        restic-8g8l7                                 1/1     Running       0          4d15h
velero        restic-rrnth                                 1/1     Running       0          4d15h
kube-system   traefik-7f854fd4ff-92dbl                     1/1     Terminating   0          4d15h
kube-system   svclb-traefik-qhck4                          2/2     Terminating   0          4d15h
kube-system   svclb-traefik-tzqst                          4/4     Running       0          2d2h
kube-system   svclb-traefik-l5k2t                          4/4     Running       0          2d2h
kube-system   traefik-69cbf575c7-927p5                     1/1     Running       0          2d2h
velero        velero-c644f66b7-k9vch                       1/1     Terminating   0          4d15h
velero        velero-c644f66b7-wpr2w                       1/1     Running       0          2d1h
velero        restic-xv6lp                                 1/1     Running       0          2d2h
kube-system   svclb-traefik-5f6l8                          4/4     Running       0          2d2h
```

```
k3os-24486 [~]$ kubectl get pv -A
NAME               CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                   STORAGECLASS   REASON   AGE
dgb-volume-dgb99   60Gi       RWO            Retain           Released   digibyte-dgb99/dgb-volume-claim-dgb99   local-path              2d2h
```

I suggest to run 

```
kubectl drain <node-name> --delete-exit-data --force --ignore-daemonsets  --delete-local-data
kubectl delete node <node-name>
```

**Comment by abdulgig** [comment]
@waleedhammam , So I tried with a fresh VDC with the following details, yet I am unable to deploy. 

Steps to reproduce,

1. Deploy a new silver VDC
2. Add a BIG worker node
3. Deploy the Digibyte solution

### VDC Info

VDC Name = rudy10
3bot = mazraa.3bot

![image](https://user-images.githubusercontent.com/25789764/116991160-331da080-ace5-11eb-81ba-afe9b8ecc2e8.png)

![image](https://user-images.githubusercontent.com/25789764/116991047-0a95a680-ace5-11eb-833b-3567c021a49a.png)

**Comment by abdulgig** [comment]
@waleedhammam , just wanted to update that I tested again, the node error seems to be fixed with https://github.com/threefoldtech/js-sdk/pull/3046. 

However, the issue of less resources despite having enough resources is still there. Details are herein,

VDC Name = rudy10
3bot = mazraa.3bot

```
root@nodes:~/vdc-tests# kubectl get nodes
NAME         STATUS   ROLES    AGE     VERSION
k3os-9640    Ready    master   6h45m   v1.19.4+k3s1
k3os-32684   Ready    <none>   6h31m   v1.19.4+k3s1
k3os-16542   Ready    <none>   6h43m   v1.19.4+k3s1
```

![image](https://user-images.githubusercontent.com/25789764/117041840-50219600-ad1c-11eb-8276-180523835aca.png)

![image](https://user-images.githubusercontent.com/25789764/117041200-c5409b80-ad1b-11eb-8402-02dcb0f29a7b.png)

```
Traceback (most recent call last):
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 148, in wrapper
    getattr(self, step_name)()
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 676, in wrapper
    return func(*args, **kwargs)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py", line 396, in choose_flavor
    self._validate_resource_limits(cpu, memory, no_nodes)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py", line 108, in _validate_resource_limits
    raise StopChatFlow(f"There are not enough resources to deploy cpu: {cpu}, memory: {memory}.")
jumpscale.sals.chatflows.chatflows.StopChatFlow: (StopChatFlow(...), 'There are not enough resources to deploy cpu: 4000, memory: 12000.')
```

**Comment by abdulgig** [comment]
@waleedhammam , Thank you ! https://github.com/threefoldtech/js-sdk/pull/3053 seems to have fixed this issue

**Comment by sasha-astiadi** [comment]
amazing! thanks everyone @waleedhammam @abdulgig @rkhamis
