### ISSUE TITLE
VDC: Error in reporting EXPIRED VDC

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#3056]
when I try to report `EXPIRED` VDC I got a stellar error:

```
JS-NG> j.tools.vdc.reporting.report_vdc_status("vdc_secondsilvernode_geertincubaid")                                                                                         

Getting VDC information ...

Creation time: 07/04/2021, 14:34:53
Expiration time: EXPIRED
Flavor: silver
Grace Period:  No
Master IP:    --> State: Down
Threebot IP: 
Threebot Domain:   --> State Down

2021-05-06 08:31:04.308 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:93 - stellar_sdk.exceptions.NotFoundError: {
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/bin/jsng", line 8, in <module>
    sys.exit(run())
    │   │    └ <Command run>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f3a13eb3b80>
           └ <Command run>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f3a1438f1c0>
         │    └ <function Command.invoke at 0x7f3a13eb4550>
         └ <Command run>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'command': None}
           │   │      │    │           └ <click.core.Context object at 0x7f3a1438f1c0>
           │   │      │    └ <function run at 0x7f3a136f0820>
           │   │      └ <Command run>
           │   └ <function Context.invoke at 0x7f3a13eb3670>
           └ <click.core.Context object at 0x7f3a1438f1c0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'command': None}
           │         └ ()
           └ <function run at 0x7f3a136f0820>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/jumpscale/entry_points/jsng.py", line 34, in run
    sys.exit(embed(globals(), locals(), configure=ptconfig, history_filename=HISTORY_FILENAME))
    │   │    │                                    │                          └ '/root/.jsng/history.txt'
    │   │    │                                    └ <function ptconfig at 0x7f3a133de5e0>
    │   │    └ <function embed at 0x7f3a13218b80>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 350, in embed
    repl.run()
    │    └ <function PythonRepl.run at 0x7f3a13218700>
    └ <ptpython.repl.PythonRepl object at 0x7f3a133d5a30>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 74, in run
    self._process_text(text)
    │    │             └ 'j.tools.vdc.reporting.report_vdc_status("vdc_secondsilvernode_geertincubaid")'
    │    └ <function PythonRepl._process_text at 0x7f3a13218790>
    └ <ptpython.repl.PythonRepl object at 0x7f3a133d5a30>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 88, in _process_text
    self._handle_exception(e)
    │    │                 └ NotFoundError(<stellar_sdk.client.response.Response object at 0x7f3a0b4b4130>)
    │    └ functools.partial(<function patched_handle_exception at 0x7f3a136ea4c0>, <ptpython.repl.PythonRepl object at 0x7f3a133d5a30>)
    └ <ptpython.repl.PythonRepl object at 0x7f3a133d5a30>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 163, in _execute
    six.exec_(code, self.get_globals(), self.get_locals())
    │   │     │     │    │              │    └ <function embed.<locals>.get_locals at 0x7f3a13218c10>
    │   │     │     │    │              └ <ptpython.repl.PythonRepl object at 0x7f3a133d5a30>
    │   │     │     │    └ <function embed.<locals>.get_globals at 0x7f3a136f0af0>
    │   │     │     └ <ptpython.repl.PythonRepl object at 0x7f3a133d5a30>
    │   │     └ <code object <module> at 0x7f3a0c3d8500, file "<stdin>", line 1>
    │   └ <built-in function exec>
    └ <module 'six' from '/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/six.py'>
> File "<stdin>", line 1, in <module>

  File "/root/js-sdk/jumpscale/tools/vdc/reporting/__init__.py", line 86, in report_vdc_status
    f"{vdc.prepaid_wallet.get_balance().balances[0].balance} TFT",

  File "/root/js-sdk/jumpscale/clients/stellar/stellar.py", line 157, in get_balance
    all_balances = self._get_free_balances(address)
                   │    │                  └ 'GAZIG4BGGGOQTMJFBWHHGINKQ7QXPLYB7NMVJQRWOJHIJF4GWBHYXTVU'
                   │    └ <function Stellar._get_free_balances at 0x7f3a0f9f1a60>
                   └ Stellar(
                       instance_name='prepaid_wallet_c750406e9a664ed1b9b7720371b19ece',
                       network=<Network.STD: 'STD'>,
                       address='GAZIG4...

  File "/root/js-sdk/jumpscale/clients/stellar/stellar.py", line 92, in _get_free_balances
    response = self._get_horizon_server().accounts().account_id(address).call()
               │    │                                           └ 'GAZIG4BGGGOQTMJFBWHHGINKQ7QXPLYB7NMVJQRWOJHIJF4GWBHYXTVU'
               │    └ <function Stellar._get_horizon_server at 0x7f3a0f9f19d0>
               └ Stellar(
                   instance_name='prepaid_wallet_c750406e9a664ed1b9b7720371b19ece',
                   network=<Network.STD: 'STD'>,
                   address='GAZIG4...

  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 58, in call
    return self.__call(url, self.params)
           │           │    │    └ {}
           │           │    └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7f3a0b4e6be0>
           │           └ 'https://horizon.stellar.org/accounts/GAZIG4BGGGOQTMJFBWHHGINKQ7QXPLYB7NMVJQRWOJHIJF4GWBHYXTVU'
           └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7f3a0b4e6be0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 64, in __call
    return self.__call_sync(url, params)
           │                │    └ {}
           │                └ 'https://horizon.stellar.org/accounts/GAZIG4BGGGOQTMJFBWHHGINKQ7QXPLYB7NMVJQRWOJHIJF4GWBHYXTVU'
           └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7f3a0b4e6be0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 68, in __call_sync
    raise_request_exception(raw_resp)
    │                       └ <stellar_sdk.client.response.Response object at 0x7f3a0b4b4130>
    └ <function raise_request_exception at 0x7f3a10407550>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/stellar_sdk/exceptions.py", line 207, in raise_request_exception
    raise NotFoundError(response)
          │             └ <stellar_sdk.client.response.Response object at 0x7f3a0b4b4130>
          └ <class 'stellar_sdk.exceptions.NotFoundError'>

stellar_sdk.exceptions.NotFoundError: {
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/js-sdk/jumpscale/tools/vdc/reporting/__init__.py", line 86, in report_vdc_status
    f"{vdc.prepaid_wallet.get_balance().balances[0].balance} TFT",
       └ UserVDC(
  instance_name='vdc_secondsilvernode_geertincubaid',
  vdc_name='secondsilvernode',
  owner_tname='geertincubaid',
  s...
  File "/root/js-sdk/jumpscale/clients/stellar/stellar.py", line 157, in get_balance
    all_balances = self._get_free_balances(address)
                   │                       └ 'GAZIG4BGGGOQTMJFBWHHGINKQ7QXPLYB7NMVJQRWOJHIJF4GWBHYXTVU'
                   └ Stellar(
  instance_name='prepaid_wallet_c750406e9a664ed1b9b7720371b19ece',
  network=<Network.STD: 'STD'>,
  address='GAZIG4BGG...
  File "/root/js-sdk/jumpscale/clients/stellar/stellar.py", line 92, in _get_free_balances
    response = self._get_horizon_server().accounts().account_id(address).call()
               │                                                └ 'GAZIG4BGGGOQTMJFBWHHGINKQ7QXPLYB7NMVJQRWOJHIJF4GWBHYXTVU'
               └ Stellar(
  instance_name='prepaid_wallet_c750406e9a664ed1b9b7720371b19ece',
  network=<Network.STD: 'STD'>,
  address='GAZIG4BGG...
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 58, in call
    return self.__call(url, self.params)
           │           │    └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7f3a0b4e6be0>
           │           └ 'https://horizon.stellar.org/accounts/GAZIG4BGGGOQTMJFBWHHGINKQ7QXPLYB7NMVJQRWOJHIJF4GWBHYXTVU'
           └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7f3a0b4e6be0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 64, in __call
    return self.__call_sync(url, params)
           │                │    └ {}
           │                └ 'https://horizon.stellar.org/accounts/GAZIG4BGGGOQTMJFBWHHGINKQ7QXPLYB7NMVJQRWOJHIJF4GWBHYXTVU'
           └ <stellar_sdk.call_builder.accounts_call_builder.AccountsCallBuilder object at 0x7f3a0b4e6be0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 68, in __call_sync
    raise_request_exception(raw_resp)
    │                       └ <stellar_sdk.client.response.Response object at 0x7f3a0b4b4130>
    └ <function raise_request_exception at 0x7f3a10407550>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/stellar_sdk/exceptions.py", line 207, in raise_request_exception
    raise NotFoundError(response)
          │             └ <stellar_sdk.client.response.Response object at 0x7f3a0b4b4130>
          └ <class 'stellar_sdk.exceptions.NotFoundError'>
stellar_sdk.exceptions.NotFoundError: {
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}

{
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}
JS-NG>  

```

**Comment by AhmedHanafy725** [comment]
**Verified** 
**Branch:** development
**commit:** 72795defd8c1a0dfdf71f90ac6a312229b0db450

![image](https://user-images.githubusercontent.com/41957921/117575947-31d4e500-b0e4-11eb-9657-cc6bdc66e302.png)
