### ISSUE TITLE
Failed to deploy VDC. failed to deploy kubernetes cluster

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#3064]
### Description
While deploying a new VDC, I got this error 
![image](https://user-images.githubusercontent.com/46320202/117284249-ed88e100-ae66-11eb-8932-c4fe8ac5c3e0.png)

Traceback
```python
2021-05-06 10:19:05.334 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:151 - chatflow stopped in step deploy. exception: (StopChatFlow(...), 'Failed to deploy VDC. failed to deploy kubernetes cluster. VDC uuid: 7047c60c46da4424afa
af4027cedf4cc')
Traceback (most recent call last):

  File "/root/js-sdk/jumpscale/packages/vdc/chats/new_vdc.py", line 401, in deploy
    minio_ak=None, minio_sk=None, s3_backup_config=self.backup_config, zdb_farms=self.zdb_farms,
                                                   │    │                        │    └ None
                                                   │    │                        └ <vdc.chats.new_vdc.VDCDeploy object at 0x7fda03802d30>
                                                   │    └ {'ak': 'rafybenjamin.3bot-testsoldelete', 'sk': '25f9e794323b453885f5181f1b624d0b', 'region': 'minio', 'url': 'https://bckp-s...
                                                   └ <vdc.chats.new_vdc.VDCDeploy object at 0x7fda03802d30>

  File "/root/js-sdk/jumpscale/sals/vdc/deployer.py", line 601, in deploy_vdc
    raise j.exceptions.Runtime("Failed to deploy VDC. failed to deploy kubernetes cluster")
          │ └ <property object at 0x7fda1d2b8228>
          └ <jumpscale.loader.J object at 0x7fda1d288b70>

jumpscale.core.exceptions.exceptions.Runtime: Failed to deploy VDC. failed to deploy kubernetes cluster


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 210, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7fda0dbcad90>
    └ <vdc.chats.new_vdc.VDCDeploy object at 0x7fda03802d30>

  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 218, in _execute_current_step
    wrapper(step_name)
    │       └ 'storage_farms_selection'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7fda0b9c81e0>

  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 210, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7fda0dbcad90>
    └ <vdc.chats.new_vdc.VDCDeploy object at 0x7fda03802d30>

  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 218, in _execute_current_step
    wrapper(step_name)
    │       └ 'network_farm_selection'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7fda0b9c3840>

  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 210, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7fda0dbcad90>
    └ <vdc.chats.new_vdc.VDCDeploy object at 0x7fda03802d30>

  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 218, in _execute_current_step
    wrapper(step_name)
    │       └ 'compute_farm_selection'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7fda1c1949d8>

  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 210, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7fda0dbcad90>
    └ <vdc.chats.new_vdc.VDCDeploy object at 0x7fda03802d30>

  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 218, in _execute_current_step
    wrapper(step_name)
File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 148, in wrapper
    getattr(self, step_name)()
            │     └ 'deploy'
            └ <vdc.chats.new_vdc.VDCDeploy object at 0x7fda03802d30>

  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 676, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<vdc.chats.new_vdc.VDCDeploy object at 0x7fda03802d30>,)
           └ <function VDCDeploy.deploy at 0x7fda0d219950>

  File "/root/js-sdk/jumpscale/packages/vdc/chats/new_vdc.py", line 413, in deploy
    self.stop(f"{str(err)}. VDC uuid: {self.vdc.solution_uuid}")
    │    └ <function GedisChatBot.stop at 0x7fda0dbcd730>
    └ <vdc.chats.new_vdc.VDCDeploy object at 0x7fda03802d30>

  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 665, in stop
    raise StopChatFlow(msg=msg, **kwargs)
          │            │   │      └ {}
          │            │   └ 'Failed to deploy VDC. failed to deploy kubernetes cluster. VDC uuid: 7047c60c46da4424afaaf4027cedf4cc'
          │            └ 'Failed to deploy VDC. failed to deploy kubernetes cluster. VDC uuid: 7047c60c46da4424afaaf4027cedf4cc'
          └ <class 'jumpscale.sals.chatflows.chatflows.StopChatFlow'>

jumpscale.sals.chatflows.chatflows.StopChatFlow: (StopChatFlow(...), 'Failed to deploy VDC. failed to deploy kubernetes cluster. VDC uuid: 7047c60c46da4424afaaf4027cedf4cc')
```

More tracepack
```python
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:18:46.479 | INFO     | jumpscale.sals.vdc.deployer:_log:824 - VDC UUID: 7047c60c46da4424afaaf4027cedf4cc, NAME: testsoldelete, OWNER: rafybenjamin attempting to reserve public ip: 185.69.167.57/24 on farm: lochristi_dev_lab pool: 11064 node: 2anfZwrzskXiUHPLTqH1veJAia8G6rW2eFLy5YFMa1MP
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:18:46.601 | DEBUG    | jumpscale.clients.explorer.explorer:log_request:27 - Request https://explorer.devnet.grid.tf/api/v1/reservations/workloads method: POST body: b'{"id": 0, "ipaddress": "185.69.167.57/24", "workload_id": 1, "node_id": "2anfZwrzskXiUHPLTqH1veJAia8G6rW2eFLy5YFMa1MP", "pool_id": 11064, "description": "{\\"vdc_uuid\\": \\"7047c60c46da4424afaaf4027cedf4cc\\"}", "reference": "", "customer_tid": 3659, "customer_signature": "2f92f997fb80b67dfbcbcd2fcbc8d945cf80d6a7284ee2877f678865ffc5fa5a8ae8c39be24338b7b0917f3474e4be10225643dc443f25ebbd20c0c80a1e0401", "next_action": 3, "signatures_provision": [], "signing_request_provision": {"signers": [], "quorum_min": 0}, "signing_request_delete": {"signers": [3659], "quorum_min": 1}, "signatures_farmer": [], "signatures_delete": [], "epoch": 1620296326, "metadata": "1NVRdX_1=LPSjtE?7dX+LeZ7=k#q0*3?_Ui2FXMGKz_mZR%y^TAZiF|-uDgMxXzPh=Zy?*C#Np~l;?>go(8CC=cDgV5Gp%~(0SPFYNXL8COm1dXZ$}WO8", "workload_type": 11}' headers: {'user-agent': 'python-requests/2.24.0', 'accept-encoding': 'gzip, deflate', 'accept': '*/*', 'connection': 'keep-alive', 'threebot-id': '3659', 'Content-Length': '799', 'content-type': 'application/json', 'date': 'Thu, 06 May 2021 10:18:46 GMT', 'authorization': 'Signature keyId="3659",algorithm="ed25519",signature="f1r1RQFdJbc6tcVHNT1oz9A+4bV9WI6UxqeOY/oCK1b2owREpyKrcRprxyMMnTAGLRWDTw2T1gAfOiXXa77cCA==",created="1620296326",expires="1620296386",headers="(created) date threebot-id"'}
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:18:56.973 | INFO     | jumpscale.sals.vdc.deployer:_log:824 - VDC UUID: 7047c60c46da4424afaaf4027cedf4cc, NAME: testsoldelete, OWNER: rafybenjamin Kubernetes master ip: 10.200.2.2
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:18:57.241 | DEBUG    | jumpscale.clients.explorer.explorer:log_request:27 - Request https://explorer.devnet.grid.tf/api/v1/reservations/workloads method: POST body: b'{"id": 0, "size": 15, "network_id": "testsoldelete", "ipaddress": "10.200.2.2", "cluster_secret": "3e55bd10db3446ea0b79cdd97ac3eeed267933f43d5b705abbea8e044afb92603bd0b5d607903c1b8edf79b1334ec453c59f02969e84a566690a91adf194b94be01e2dda84d2e7d2", "master_ips": [], "ssh_keys": ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDM9LK66gBMqSbDyKajBUzpnTx75FQYBX8y5zwdNvHfxSVeXkoxl9yZDaI78MNFwJVGgBQALU1iE0j/x3uD0ApqRSZnOvRyAkNoPJVb9WWpe65r1oxwH2xqlAoj/yHiq4ONo945jKlkml2gX0CioHYbllLF6QAwfMlf34295lS20VmEluVW+k96O7O5Dn0ua3Zm/78tiSxLHY5OA+IZTalLsVFMK1HuI/ZDo8CMb1Cjj7WLbZktuUZqZcNAEPlgj0WrBuTcON8S09qC4LTvXmvnB7sVV7mjvFVaIikpPnMOwh29rUEtQK/iGJtX5lUZ+pqUxNQA1SkMhD63nBVGSEtL root@waleed-ng"], "public_ip": 49135, "stats_aggregator": [], "datastore_endpoint": "", "disable_default_ingress": false, "workload_id": 1, "node_id": "2anfZwrzskXiUHPLTqH1veJAia8G6rW2eFLy5YFMa1MP", "pool_id": 11064, "description": "{\\"vdc_uuid\\": \\"7047c60c46da4424afaaf4027cedf4cc\\"}", "reference": "", "customer_tid": 3659, "customer_signature": "aa33fc9a627c7d7fe32973b61e244c820a4b7eb7143dbe6c5eb5e29ee6723c19c7f6b82d07f25a7e8b5c40027b7367e8a099a1778aa86850f3e3a82dc3d91404", "next_action": 3, "signatures_provision": [], "signing_request_provision": {"signers": [], "quorum_min": 0}, "signing_request_delete": {"signers": [3659], "quorum_min": 1}, "signatures_farmer": [], "signatures_delete": [], "epoch": 1620296337, "metadata": "P4TNycb5RxllEG^nVY)dDhCVL&JC=E;$piLy0E`I6Jeh6H*+T6D=|S;$RkT^(D?-QDGE#mZF?dsSxj-a%BUyCV7mFEEY!oQgpGOH;Aal^*-OKhc3EK(1DxA%Mqf*%E9+?U<GW=vwWJu^lZNy_%xIfV;`g?4oUr5)@Xa}!8cklIa;G@", "workload_type": 4}' headers: {'user-agent': 'python-requests/2.24.0', 'accept-encoding': 'gzip, deflate', 'accept': '*/*', 'connection': 'keep-alive', 'threebot-id': '3659', 'Content-Length': '1593', 'content-type': 'application/json', 'date': 'Thu, 06 May 2021 10:18:57 GMT', 'authorization': 'Signature keyId="3659",algorithm="ed25519",signature="FYbOlIKYrl0Pu4EDLx2ON1Puys/Xjw9v/nzZLADMWYvLSML48o6zYAXwGUlPiY9xXRERAigIlTiRMK3YMHnOAw==",created="1620296337",expires="1620296397",headers="(created) date threebot-id"'}
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:18:57.256 | ERROR    | jumpscale.sals.vdc.deployer:_log:824 - VDC UUID: 7047c60c46da4424afaaf4027cedf4cc, NAME: testsoldelete, OWNER: rafybenjamin Failed to deploy VDC. cancelling workloads
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:18:57.270 | ERROR    | jumpscale.sals.vdc.deployer:_log:824 - VDC UUID: 7047c60c46da4424afaaf4027cedf4cc, NAME: testsoldelete, OWNER: rafybenjamin raised an exception: 409 Client Error: public ip is in use for url: https://explorer.devnet.grid.tf/api/v1/reservations/workloads
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:19:02.459 | ERROR    | jumpscale.sals.vdc.deployer:_log:824 - VDC UUID: 7047c60c46da4424afaaf4027cedf4cc, NAME: testsoldelete, OWNER: rafybenjamin new_vdc_context: deployment failed due to exception: Failed to deploy VDC. failed to deploy kubernetes cluster
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:19:05.334 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:151 - chatflow stopped in step deploy. exception: (StopChatFlow(...), 'Failed to deploy VDC. failed to deploy kubernetes cluster. VDC uuid: 7047c60c46da4424afaaf4027cedf4cc')
fs/log.2021-05-06_09-16-49_351175.txt:          │            │   └ 'Failed to deploy VDC. failed to deploy kubernetes cluster. VDC uuid: 7047c60c46da4424afaaf4027cedf4cc'
fs/log.2021-05-06_09-16-49_351175.txt:          │            └ 'Failed to deploy VDC. failed to deploy kubernetes cluster. VDC uuid: 7047c60c46da4424afaaf4027cedf4cc'
fs/log.2021-05-06_09-16-49_351175.txt:jumpscale.sals.chatflows.chatflows.StopChatFlow: (StopChatFlow(...), 'Failed to deploy VDC. failed to deploy kubernetes cluster. VDC uuid: 7047c60c46da4424afaaf4027cedf4cc')
Binary file redis/init/194000.msgpack matches
```

Information
```python
NAME: testsoldelete, OWNER: rafybenjamin found existing pool 11064 on farm: lochristi_dev_lab. pool: Pool(
  pool_id=11064,
  cus=2700.0,
  sus=586.0,
  ipv4us=3600.0,
  node_ids=['Gr8NxBLHe7yjSsnSTgTqGr7BHbyAUVPJqs8fnudEE4Sf', 'qzuTJJVd5boi6Uyoco1WWnSgzTb7q8uN79AjBT9x9N3', 'BpTAry1Na2s1J8RAHNyDsbvaBSM3FjR4gMXEKga3UPbs', '2anfZwrzskXiUHPLTqH1veJAia8G6rW2eFLy5YFMa1MP', 'BBmMHCw392RLiByVEUT2ac6y6qJpbW9xj8T
Rdgk5rMGN', 'FTothsg9ZuJubAEzZByEgQQUmkWM637x93YH1QSJM242', '3NAkUYqm5iPRmNAnmLfjwdreqDssvsebj4uPUt9BxFPm', 'HtKZ3SwHcGM7nTsm8ykRGttfodFfLkghrmD5FGypgobK', '5f4QEXpTcKt9Tbngn4hvraXd2G4QVFkagabUeKpn55oc', '48YmkyvfoXnXqEojpJieMfFPnCv2enEuqE
JcmhvkcdAk', '3kcJhRkTDuL51HmikzWFMndWwJbJGg8dZeqG9e72c6LV', 'DJHD5cMjRkuVh4enQ6dqCAuPNUPfH2a45gLv7JDDswbT'],
  last_updated=datetime.datetime(2021, 5, 6, 10, 18, 26, tzinfo=tzutc()),
  active_cu=0.0,
  active_su=0.0,
  active_ipv4=0.0,
  empty_at=9223372036854775807,
  customer_tid=3659,
  active_workload_ids=[49112]

```

**Comment by sameh-farouk** [comment]
+1 can't deploy VDC on devnet

![Screenshot from 2021-05-06 12-46-20](https://user-images.githubusercontent.com/42457449/117286173-21fd9c80-ae69-11eb-8a70-28928c7203dc.png)

```python
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:19:06.278 | INFO     | jumpscale.sals.vdc.deployer:_log:824 - VDC UUID: 92f1719c8e204972a2040ba8072da276, NAME: test0605, OWNER: samehabouelsaad attempting to reserve public ip: 185.69.167.123/24 on farm: lochristi_dev_lab pool: 11065 node: 2anfZwrzskXiUHPLTqH1veJAia8G6rW2eFLy5YFMa1MP
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:19:06.407 | DEBUG    | jumpscale.clients.explorer.explorer:log_request:27 - Request https://explorer.devnet.grid.tf/api/v1/reservations/workloads method: POST body: b'{"id": 0, "ipaddress": "185.69.167.123/24", "workload_id": 1, "node_id": "2anfZwrzskXiUHPLTqH1veJAia8G6rW2eFLy5YFMa1MP", "pool_id": 11065, "description": "{\\"vdc_uuid\\": \\"92f1719c8e204972a2040ba8072da276\\"}", "reference": "", "customer_tid": 3658, "customer_signature": "6dd107122a8f2527a20c7ecb8d54adde1f86f8ecefb412a2eb95261b8f22cc300a477cad36ff4f93d94909ae934b06349a4b98c4524caba4ea10b3b929d3de00", "next_action": 3, "signatures_provision": [], "signing_request_provision": {"signers": [], "quorum_min": 0}, "signing_request_delete": {"signers": [3658], "quorum_min": 1}, "signatures_farmer": [], "signatures_delete": [], "epoch": 1620296346, "metadata": "Dg7i~xsa+Qo$DFWKG&aVNEbu%#2k+vG2EH!0g|=9^NYk8p4b5JQO1fSpa)IceLemk7YVQfO48Ex<gB$pifkVfe3g(ixus?Y-o^d;Ui4%)QV`)(?}2HIga", "workload_type": 11}' headers: {'user-agent': 'python-requests/2.24.0', 'accept-encoding': 'gzip, deflate', 'accept': '*/*', 'connection': 'keep-alive', 'threebot-id': '3658', 'Content-Length': '800', 'content-type': 'application/json', 'date': 'Thu, 06 May 2021 10:19:06 GMT', 'authorization': 'Signature keyId="3658",algorithm="ed25519",signature="07L3lYsrH/BKXNespnHfjwZs9GffXpkEgVMiG32QG2IsQtMiactKMCqdfy6//cHqnwq1Hk6IIWLxSVXlS8YbAg==",created="1620296346",expires="1620296406",headers="(created) date threebot-id"'}
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:19:16.774 | INFO     | jumpscale.sals.vdc.deployer:_log:824 - VDC UUID: 92f1719c8e204972a2040ba8072da276, NAME: test0605, OWNER: samehabouelsaad Kubernetes master ip: 10.200.2.2
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:19:17.010 | DEBUG    | jumpscale.clients.explorer.explorer:log_request:27 - Request https://explorer.devnet.grid.tf/api/v1/reservations/workloads method: POST body: b'{"id": 0, "size": 15, "network_id": "test0605", "ipaddress": "10.200.2.2", "cluster_secret": "f9ce553824dcbfc6701d97cb0c4a8885609fb18cbf27c4eec728c512ca90270a9d3728bf6cd5b504707b24ccabf47a2d03d712bcdedc7a99b986c782c9cb7d2caa2f0fa8cbddc8bb", "master_ips": [], "ssh_keys": ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC52DriWnhf1Dqs7SZXO+4oxQE0edcp8ipdzNwWYGzAvtZq1P/8KHrI9Wjwrj00gScXRPKMkrMYqOsjJ0ouKBU08449Q652p/edSnQ8QMtMgEwspWOu45mVjXBMmSaNYJ+lHrbvjq6oZb/pDZoLCuUgbUO8DwcI4NgDO1lzdZcblNxicjl7+9lrX6cIZE9qGVOV0WkZPLsEUCMQm3M4JC076vPNK7Tw51BUTZn6aSOaRY3zxSpBBBnl8xB2tjxt2r9QfdiMKOiMaw0DUAT0w8PF7eSX7QpSF/G0TP/nMtaTl3XHS2kJti2aoy0gQ5m519fUIfcNnj0iLieU1DjZL5dF root@waleed-ng"], "public_ip": 49144, "stats_aggregator": [], "datastore_endpoint": "", "disable_default_ingress": false, "workload_id": 1, "node_id": "2anfZwrzskXiUHPLTqH1veJAia8G6rW2eFLy5YFMa1MP", "pool_id": 11065, "description": "{\\"vdc_uuid\\": \\"92f1719c8e204972a2040ba8072da276\\"}", "reference": "", "customer_tid": 3658, "customer_signature": "50b9e97cb0cde201278f0e88e7a7897a98c49628e344760bd3258bb5f1608d22e8065c355d1beb9f04335305d3c4531989513456ee5847088cf1cca9b3620809", "next_action": 3, "signatures_provision": [], "signing_request_provision": {"signers": [], "quorum_min": 0}, "signing_request_delete": {"signers": [3658], "quorum_min": 1}, "signatures_farmer": [], "signatures_delete": [], "epoch": 1620296356, "metadata": "04FMP3i#M!|33$)v7scyK)-%0P>q1S(tyX|q1a~?vPLrLd#%P}PbCM=jumL#_F#eZcctPU=ugT?KKHwXeT@3?w3r)0k}|sW<G-lw50ks)zt`DE`#ZFrD9(62;_LLt2mgcC)a$A(OuhFxT(-+7tLsk>_rz~kSVC#&d2J88T>ANo?Xq0", "workload_type": 4}' headers: {'user-agent': 'python-requests/2.24.0', 'accept-encoding': 'gzip, deflate', 'accept': '*/*', 'connection': 'keep-alive', 'threebot-id': '3658', 'Content-Length': '1588', 'content-type': 'application/json', 'date': 'Thu, 06 May 2021 10:19:16 GMT', 'authorization': 'Signature keyId="3658",algorithm="ed25519",signature="ArIGN7l40A2a6lyhStLixTQT+5ODcHQZfmCxL3bmL4OmWIJulwGf+epC4CL1iZd68q3BZXSNmpjjXfAd9euEBg==",created="1620296356",expires="1620296416",headers="(created) date threebot-id"'}
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:19:17.018 | ERROR    | jumpscale.sals.vdc.deployer:_log:824 - VDC UUID: 92f1719c8e204972a2040ba8072da276, NAME: test0605, OWNER: samehabouelsaad Failed to deploy VDC. cancelling workloads
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:19:17.025 | ERROR    | jumpscale.sals.vdc.deployer:_log:824 - VDC UUID: 92f1719c8e204972a2040ba8072da276, NAME: test0605, OWNER: samehabouelsaad raised an exception: 409 Client Error: public ip is in use for url: https://explorer.devnet.grid.tf/api/v1/reservations/workloads
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:19:21.906 | ERROR    | jumpscale.sals.vdc.deployer:_log:824 - VDC UUID: 92f1719c8e204972a2040ba8072da276, NAME: test0605, OWNER: samehabouelsaad new_vdc_context: deployment failed due to exception: Failed to deploy VDC. failed to deploy kubernetes cluster
fs/log.2021-05-06_09-16-49_351175.txt:2021-05-06 10:19:24.581 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:151 - chatflow stopped in step deploy. exception: (StopChatFlow(...), 'Failed to deploy VDC. failed to deploy kubernetes cluster. VDC uuid: 92f1719c8e204972a2040ba8072da276')
fs/log.2021-05-06_09-16-49_351175.txt:          │            │   └ 'Failed to deploy VDC. failed to deploy kubernetes cluster. VDC uuid: 92f1719c8e204972a2040ba8072da276'
fs/log.2021-05-06_09-16-49_351175.txt:          │            └ 'Failed to deploy VDC. failed to deploy kubernetes cluster. VDC uuid: 92f1719c8e204972a2040ba8072da276'
fs/log.2021-05-06_09-16-49_351175.txt:jumpscale.sals.chatflows.chatflows.StopChatFlow: (StopChatFlow(...), 'Failed to deploy VDC. failed to deploy kubernetes cluster. VDC uuid: 92f1719c8e204972a2040ba8072da276')
```

**Comment by xmonader** [comment]
please reopen if you can't deploy anymore.
