### ISSUE TITLE
we are installing poetry on the server in way that Poetry's dependencies cause conflicts with other packages.

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#3081]
while working on an issue related to update vdc dashboard, I found that the way we install poetry on the server is causing some troubles.
-  When you specify a package in the dev-dependencies that is either a dependency of the poetry itself or it depends on one of the poetry dependencies, and you've installed poetry inside an environment that poetry is supposed to manage, poetry will uninstall this mentioned dependency after invoking poetry install --no-dev, making itself unusable in the future.

currently, we install poetry on the server with `pip install poetry` this will install Poetry's dependencies in a way that causes conflicts with other packages.

the recommended way of installing poetry is
```bash
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
```
this runs a custom installer that will install poetry isolated from the rest of our server system by vendorizing its dependencies.

### Steps to reproduce

try to run one of these commands on the server (or locally but you need to make sure you have installed poetry using pip and that you disabled the env creation)
`poetry install --no-dev` --> will remove some of the poetry dependencies make it unusable.
`poetry install --remove-untracked` --> will remove poetry itself.
### Traceback/Logs/Alerts

Traceback/Logs/Alerts if available
```bash
root@zosv2-04:/sandbox/code/github/threefoldtech/js-sdk# poetry show
Traceback (most recent call last):
  File "/usr/local/bin/poetry", line 5, in <module>
    from poetry.console import main
  File "/usr/local/lib/python3.8/dist-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/usr/local/lib/python3.8/dist-packages/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/usr/local/lib/python3.8/dist-packages/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/usr/local/lib/python3.8/dist-packages/poetry/console/commands/check.py", line 2, in <module>
    from poetry.factory import Factory
  File "/usr/local/lib/python3.8/dist-packages/poetry/factory.py", line 18, in <module>
    from .repositories.pypi_repository import PyPiRepository
  File "/usr/local/lib/python3.8/dist-packages/poetry/repositories/pypi_repository.py", line 33, in <module>
    from ..inspection.info import PackageInfo
  File "/usr/local/lib/python3.8/dist-packages/poetry/inspection/info.py", line 25, in <module>
    from poetry.utils.env import EnvCommandError
  File "/usr/local/lib/python3.8/dist-packages/poetry/utils/env.py", line 23, in <module>
    import virtualenv
  File "/usr/local/lib/python3.8/dist-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/usr/local/lib/python3.8/dist-packages/virtualenv/run/__init__.py", line 7, in <module>
    from ..app_data import make_app_data
  File "/usr/local/lib/python3.8/dist-packages/virtualenv/app_data/__init__.py", line 9, in <module>
    from appdirs import user_data_dir
ModuleNotFoundError: No module named 'appdirs'
```

**Comment by sameh-farouk** [comment]
verifying this...

**Comment by sameh-farouk** [comment]
@OmarElawady unfortunately, this issue hasn't resolved and I wasn't able to verify the desired fix.

running form the terminal I got:
```sh
/root/.poetry/bin/poetry: Permission denied
```

and running the update script, now throw:

```sh
poetry: command not found
```

**Comment by sameh-farouk** [comment]
**trying verify this after commit db41f4c64f6e4a8bb2e20aa4577e44d79a89f7ba**

this didn't fix the issue too.
**poetry still broken** since 8d6b956acb528da0a28af10a772544bcdadb9718

updating the VDC to another branch with different poetry.lock file will fail because of `poetry: command not found`
visiting: https://samehabouelsaad-testdeployer3105.vdcdev.grid.tf/vdc_dashboard/api/update?branch=development_chatbot

gives back
```json
// 20210531215949
// https://samehabouelsaad-testdeployer3105.vdcdev.grid.tf/vdc_dashboard/api/update?branch=development_chatbot

{
  "error": "failed to pull upstream",
  "stderr": "Switched to a new branch 'development_chatbot'\njumpscale/packages/vdc_dashboard/scripts/update.sh: line 63: poetry: command not found\njumpscale/packages/vdc_dashboard/scripts/update.sh: line 63: poetry: command not found\njumpscale/packages/vdc_dashboard/scripts/update.sh: line 63: poetry: command not found\njumpscale/packages/vdc_dashboard/scripts/update.sh: line 63: poetry: command not found\nError: Failed to install the defined dependencies!\nSwitched to branch 'development'\n",
  "stdout": "Fetching origin\nwe will use origin/development_chatbot branch to update the code\nwe will revert to development db41f4c64f6e4a8bb2e20aa4577e44d79a89f7ba in case of failure\npoetry.lock has changed\nSaved working directory and index state WIP on development: db41f4c6 Fix poetry permissions and path (#3124)\nBranch 'development_chatbot' set up to track remote branch 'development_chatbot' from 'origin'.\nHEAD is now at ce068b52 Test the flow\nYour branch is up to date with 'origin/development'.\nHEAD is now at db41f4c6 Fix poetry permissions and path (#3124)\nOn branch development\nYour branch is up to date with 'origin/development'.\n\nChanges not staged for commit:\n  (use \"git add <file>...\" to update what will be committed)\n  (use \"git restore <file>...\" to discard changes in working directory)\n\tmodified:   jumpscale/packages/vdc_dashboard/package.toml\n\nUntracked files:\n  (use \"git add <file>...\" to include in what will be committed)\n\tvelero-v1.5.3-linux-amd64.tar.gz\n\nno changes added to commit (use \"git add\" and/or \"git commit -a\")\nDropped refs/stash@{0} (0339f2e09e57e35d42754b78c11f8fe64f932324)\n",
  "code": 64,
  "cmd": "bash jumpscale/packages/vdc_dashboard/scripts/update.sh development_chatbot"
}
```

**Comment by sameh-farouk** [comment]
verifying this after 73616bac6fad9857c0f915ecba2e6a7f54307412

**Comment by sameh-farouk** [comment]
**verified**
on db41f4c64f6e4a8bb2e20aa4577e44d79a89f7ba
poetry dependencies no longer cause conflict with other dependencies as it now got installed isolated from the rest of the project dependices.
