### ISSUE TITLE
VDC: Create a service to deploy threebot incase it goes down

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/js-sdk#3099]
### Description

We need to create a service to deploy a new threebot in case it goes down

### Implementation

Delete the old one and deploy a new one with the same config.

**Comment by RafyAmgadBenjamin** [comment]
Verifying this

**Comment by RafyAmgadBenjamin** [comment]
i got this while testing the service
```
Request https://explorer.devnet.grid.tf/api/v1/reservations/workloads?customer_tid=3263&page=1 method: GET body: None headers: {'user-agent': 'python-requests/2.25.1', 'accept-encoding': 'gzip, deflate', 'accept': '*/*', 'connection': 'keep-alive', 'threebot-id': '3263', 'date': 'Wed, 02 Jun 2021 11:31:06 GMT', 'authorization': 'Signature keyId="3263",algorithm="ed25519",signature="f0RJ5xR7eb3sSwCcEKoMCc/IyicVRxUGHcs6fSpvgkIj3R/mnh8c60oRfH1ZxsYBb5RlVuDrCZugFbY3v8SJCw==",created="1622633466",expires="1622633526",headers="(created) date threebot-id"'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/js-sdk/jumpscale/packages/vdc/services/check_threebot.py", line 60, in job
    zdb_farms = workload.environment[?[31m'S3_AUTO_TOPUP_FARMS'?[m]
    ?[36m            └ Container(
  id=33954,
  flist='https://hub.grid.tf/ahmed_hanafy_1/ahmedhanafy725-etcd-latest.flist',
  hub_url='',
  storage_ur...?[m
KeyError: 'S3_AUTO_TOPUP_FARMS'

'S3_AUTO_TOPUP_FARMS'
```

**Comment by MElborolossy** [comment]
Well working on it, once finished speedup payment as it has a higher priority.
