### ISSUE TITLE
provisioning of VM results in status "DELETED"

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#3164]
NET: testnet
Capacity pool :  FreeFarm and GEC-Vienna
Error message at the bottom of the deployed workloads: `could not mount k3os flist: fail to fetch hash, response: 404` 

need / want to deploy vm on testnet for customer "experience".  Tried different farms / different pools but always end up with a  "DELETED" VM.

![image](https://user-images.githubusercontent.com/13766992/120961969-e3ad1300-c76f-11eb-8388-05d73d6faa3d.png)

Evert reservation has resulted to the error `could not mount k3os flist: fail to fetch hash, response: 404`

My deployment script is the following:

```
#!/usr/bin/env python3
# pylint: disable=no-value-for-parameter

# import click
from jumpscale.loader import j
# import stellar_sdk
import os

def main():

	# load the SAL to make/break reservation
	zos=j.sals.zos.get()

 	# select the pool with the most cus / sus available for deployment
	my_pools=zos.pools.list()
	print(my_pools[0])
	print('---')
	print(my_pools[1])
	print('---')
	print(my_pools[2])

	vm_pool=my_pools[0]
        pool_id=vm_pool.pool_id
	#node_id=vm_pool.node_ids[1]
	node_id='89HWyx6iurJKk7BXEa4tL7ziWFHwycRwidMtPWsepgZo'
	network_name='management'
	ip_address='10.100.10.2'
	ssh_keys=['ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAOP0h6VImNcxnIBRMoMfbMfb0xwGHDlaPxZ+nu0CL8ATJekVDHDLMGEPdvACfHBe0sqIw/l6jqoEMR4Dzhjgm4bVEUBVEnG1FvkeNB59sT2DOxDCZuqJvjx2M1bJlH8AR/JQXxUQ+zvfTbavc4/zfCuJm4PYNUsmEt/IQmRwLznGOkoJb
wYLhKCC3ykZd0EGpmCWgUUYn0ihaaYkyrliQi5Ny00x0s6jOIJg0CG2Xh5xcrkhOfCZMxZAB+/LGQpZ3tu+Cy5jRf8V/JZ8XQmtYM2GmBUZ1KGcMcsGzrtuudn13JeYLtWJBw6A7Q3Fb7dQSCMLC9UA0uMSZk67M6DFV john@RescuedMac']
	name='testvm'
	size=1

	vm=zos.vm.create(node_id=node_id, \
		network_name=network_name, \
		ip_address=ip_address, \
		ssh_keys=ssh_keys, \
		pool_id=pool_id, \
		name=name, \
		size=size)

	print("-----vm------")
	print(vm)
	print("-----vm------")

	workload_id=zos.workloads.deploy(vm)
	result = zos.workloads.get(workload_id)
	print("-----result------")
	print(result)



if __name__ == '__main__':
    main()
```

**Comment by muhamadazmy** [comment]
This sounds like a temporary hub failure. Is this reproducible ?

**Comment by weynandkuijpers** [comment]
I did it a few times > 3.  Will try again.

**Comment by weynandkuijpers** [comment]
Wotked now.  although looking at the "deployed solutions" there are a number of failures.  Some done by 'CLI' in the SDK / 3bot and some through the GUI.

![image](https://user-images.githubusercontent.com/13766992/121149904-1a5c5980-c854-11eb-9ac0-dffc69edc5d6.png)

**Comment by weynandkuijpers** [comment]
Testnet deployment works.

Mainnet deployment now fails
I guess we have to update / upgrade 3bot / zero-OS for this to work.

```
Traceback (most recent call last):
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 655, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/tfgrid_solutions/chats/vmachine.py", line 130, in reservation
    self.reservation, self.public_ip = deployer.deploy_vmachine(
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 1277, in deploy_vmachine
    return j.sals.zos.get(identity_name).workloads.deploy(vmachine), public_ip
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/zos/workloads.py", line 191, in deploy
    return self._workloads.create(workload)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/workloads.py", line 98, in create
    resp = self._session.post(url, json=data)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 662, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/clients/explorer/errors.py", line 23, in raise_for_status
    raise HTTPError(http_error_msg, response=resp)
requests.exceptions.HTTPError: 400 Client Error: unrecognized workload type for url: https://explorer.grid.tf/api/v1/reservations/workloads
```
