### ISSUE TITLE
VDC testnet : payment service is down when creating new vdc 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/js-sdk#3277]
on https://vdc.testnet.grid.tf/  when creating new vdc got this  error 

![Screenshot from 2021-08-04 15-52-26](https://user-images.githubusercontent.com/26298009/128196681-0a498ead-5dd8-4515-9a0f-352fc271cadd.png)

**Comment by sameh-farouk** [comment]
the token service for the test net is currently not responding.
```
JS-NG> j.tools.http.options("https://testnet.threefold.io/threefoldfoundation/tr
     1 ansactionfunding_service/fund_transaction")
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
          └ TimeoutError(110, 'Connection timed out')
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
    │            └ ('109.135.19.64', 443)
    └ None
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/gevent/_socketcommon.py", line 607, in connect
    raise _SocketError(err, strerror(err))
          │            │    │        └ 110
          │            │    └ <built-in function strerror>
          │            └ 110
          └ <class 'OSError'>
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │                   └ <urllib3.connection.HTTPSConnection object at 0x7f6aa14a1f70>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f6aa4729610>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    └ <urllib3.connection.HTTPSConnection object at 0x7f6aa14a1f70>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
           └ <urllib3.connection.HTTPSConnection object at 0x7f6aa14a1f70>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f6aa14a1f70>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6aa14a1f70>: Failed to establish a new connection: [Errno ...
          │             │      └ '/threefoldfoundation/transactionfunding_service/fund_transaction'
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f6aa4729610>
          └ <class 'urllib3.exceptions.MaxRetryError'>
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='testnet.threefold.io', port=443): Max retries exceeded with url: /threefoldfoundation/transactionfunding_service/fund_transaction (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6aa14a1f70>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/api.py", line 89, in options
    return request('options', url, **kwargs)
           │                  │      └ {'allow_redirects': True}
           │                  └ 'https://testnet.threefold.io/threefoldfoundation/transactionfunding_service/fund_transaction'
           └ <function request at 0x7f6aa68505e0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │                      │           │      └ {'allow_redirects': True}
           │                      │           └ 'https://testnet.threefold.io/threefoldfoundation/transactionfunding_service/fund_transaction'
           │                      └ 'options'
           └ <requests.sessions.Session object at 0x7f6aa13255b0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │         │       └ {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │         └ <PreparedRequest [OPTIONS]>
           └ <requests.sessions.Session object at 0x7f6aa13255b0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │            │          └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
        │            └ <PreparedRequest [OPTIONS]>
        └ <requests.adapters.HTTPAdapter object at 0x7f6aa14c9850>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
          │                          └ <PreparedRequest [OPTIONS]>
          └ <class 'requests.exceptions.ConnectionError'>
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='testnet.threefold.io', port=443): Max retries exceeded with url: /threefoldfoundation/transactionfunding_service/fund_transaction (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6aa14a1f70>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
          └ TimeoutError(110, 'Connection timed out')
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
    │            └ ('109.135.19.64', 443)
    └ None
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/gevent/_socketcommon.py", line 607, in connect
    raise _SocketError(err, strerror(err))
          │            │    │        └ 110
          │            │    └ <built-in function strerror>
          │            └ 110
          └ <class 'OSError'>
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │                   └ <urllib3.connection.HTTPSConnection object at 0x7f6aa14a1f70>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f6aa4729610>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    └ <urllib3.connection.HTTPSConnection object at 0x7f6aa14a1f70>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
           └ <urllib3.connection.HTTPSConnection object at 0x7f6aa14a1f70>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f6aa14a1f70>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6aa14a1f70>: Failed to establish a new connection: [Errno ...
          │             │      └ '/threefoldfoundation/transactionfunding_service/fund_transaction'
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f6aa4729610>
          └ <class 'urllib3.exceptions.MaxRetryError'>
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='testnet.threefold.io', port=443): Max retries exceeded with url: /threefoldfoundation/transactionfunding_service/fund_transaction (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6aa14a1f70>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/api.py", line 89, in options
    return request('options', url, **kwargs)
           │                  │      └ {'allow_redirects': True}
           │                  └ 'https://testnet.threefold.io/threefoldfoundation/transactionfunding_service/fund_transaction'
           └ <function request at 0x7f6aa68505e0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │                      │           │      └ {'allow_redirects': True}
           │                      │           └ 'https://testnet.threefold.io/threefoldfoundation/transactionfunding_service/fund_transaction'
           │                      └ 'options'
           └ <requests.sessions.Session object at 0x7f6aa13255b0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │         │       └ {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │         └ <PreparedRequest [OPTIONS]>
           └ <requests.sessions.Session object at 0x7f6aa13255b0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │            │          └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
        │            └ <PreparedRequest [OPTIONS]>
        └ <requests.adapters.HTTPAdapter object at 0x7f6aa14c9850>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
          │                          └ <PreparedRequest [OPTIONS]>
          └ <class 'requests.exceptions.ConnectionError'>
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='testnet.threefold.io', port=443): Max retries exceeded with url: /threefoldfoundation/transactionfunding_service/fund_transaction (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6aa14a1f70>: Failed to establish a new connection: [Errno 110] Connection timed out'))

HTTPSConnectionPool(host='testnet.threefold.io', port=443): Max retries exceeded with url: /threefoldfoundation/transactionfunding_service/fund_transaction (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6aa14a1f70>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Comment by waleedhammam** [comment]
Was fixed after stellar node deployment
