### ISSUE TITLE
Extend the cluster neither succeeded nor timed out

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#3279]
### Description
Adding a node to my VDC, neither succeeded nor timed out.  The cahflow is kept going for more than 4 hours (no UI indicator for any failure) and I eventually had to restart it manually.

after basic debugging,  there was an AttributeError exception that happened but it didn't propagate to the running chatflow (ignored somewhere?).
the exception happened in the below line because `result` was `None` and we do not handle such a case:

https://github.com/threefoldtech/js-sdk/blob/1e9c5e8f9f90502abdb25a540a502f3ed44dcc71/jumpscale/packages/chatflows/actors/chatbot.py#L40

![Screenshot from 2021-08-05 14-05-20](https://user-images.githubusercontent.com/42457449/128347037-bcd371eb-4768-496e-b953-94e0ea1fc267.png)

### Version information
* Project commit/version: e.g. js-sdk 1e9c5e8f9f90502abdb25a540a502f3ed44dcc71

### Installation method

VDC deployed via Devnet VDC deployer, VDC name is vdc_dev18072021_samehabouelsaad

### Traceback/Logs/Alerts

```
2021-08-05 08:37:55.143 | INFO     | jumpscale.sals.billing.billing:submit_payment:34 - payment 86d28bd3d03440a0852c5ce9c1755dd2 submitted for wallet: prepaid_wallet_6796809a07224f0fbfa2af5cc328729a amount: 1.72897820181973, description: {"type": "VDC_K8S_EXTEND", "owner": "samehabouelsaad", "solution_uuid": "6796809a07224f0fbfa2af5cc328729a"}, expiry: 5, memo_text: zUfy63ii7nbtL8hYy7LYg4qRSWQP
2021-08-05 08:37:55.146 | INFO     | jumpscale.sals.billing.billing:wait_payment:50 - waiting payment: 86d28bd3d03440a0852c5ce9c1755dd2
2021-08-05 08:37:56.049 | INFO     | jumpscale.sals.billing.billing:process_payments:138 - updating active payment: 86d28bd3d03440a0852c5ce9c1755dd2
2021-08-05 08:37:56.053 | INFO     | jumpscale.sals.billing.models:update_status:121 - updating payment: 86d28bd3d03440a0852c5ce9c1755dd2 status
2021-08-05 08:38:10.010 | INFO     | jumpscale.sals.billing.models:update_status:121 - updating payment: 86d28bd3d03440a0852c5ce9c1755dd2 status
2021-08-05 08:38:28.069 | INFO     | jumpscale.sals.billing.billing:process_payments:138 - updating active payment: 86d28bd3d03440a0852c5ce9c1755dd2
2021-08-05 08:38:28.073 | INFO     | jumpscale.sals.billing.models:update_status:121 - updating payment: 86d28bd3d03440a0852c5ce9c1755dd2 status
2021-08-05 08:38:40.792 | INFO     | jumpscale.sals.billing.models:update_status:135 - adding transaction 609e4491bb58c30ccdde0847a9277c10b8d690e7544dae16d6f569c6593ca03c to payment: 86d28bd3d03440a0852c5ce9c1755dd2
2021-08-05 08:38:41.392 | INFO     | jumpscale.sals.billing.models:update_status:144 - adding transaction 609e4491bb58c30ccdde0847a9277c10b8d690e7544dae16d6f569c6593ca03c to payment: 86d28bd3d03440a0852c5ce9c1755dd2 with amount: 1.7289780
2021-08-05 08:38:41.396 | INFO     | jumpscale.sals.billing.models:update_status:153 - payment: 86d28bd3d03440a0852c5ce9c1755dd2 fulfilled by transaction: 609e4491bb58c30ccdde0847a9277c10b8d690e7544dae16d6f569c6593ca03c with amount: 1.7289780
2021-08-05 08:38:41.398 | INFO     | jumpscale.sals.billing.models:update_status:159 - payment: 86d28bd3d03440a0852c5ce9c1755dd2 is marked as extra paid
2021-08-05 08:38:43.459 | INFO     | jumpscale.sals.billing.billing:wait_payment:58 - payment: 86d28bd3d03440a0852c5ce9c1755dd2 result True
2021-08-05 08:38:43.628 | INFO     | jumpscale.sals.vdc.deployer:_log:959 - VDC UUID: 6796809a07224f0fbfa2af5cc328729a, NAME: dev18072021, OWNER: samehabouelsaad using wallet: prepaid_wallet_6796809a07224f0fbfa2af5cc328729a instead of provision_wallet_6796809a07224f0fbfa2af5cc328729a
2021-08-05 08:38:43.786 | INFO     | jumpscale.sals.vdc.deployer:_log:959 - VDC UUID: 6796809a07224f0fbfa2af5cc328729a, NAME: dev18072021, OWNER: samehabouelsaad Extending kubernetes cluster on farm: lochristi_dev_lab, public_ip: False, no_nodes: 1
2021-08-05 08:38:43.918 | INFO     | jumpscale.sals.vdc.deployer:_log:959 - VDC UUID: 6796809a07224f0fbfa2af5cc328729a, NAME: dev18072021, OWNER: samehabouelsaad Preperaring pool for kubernetes cluster extension on farm lochristi_dev_lab, flavor: K8SNodeFlavor.MEDIUM, no_nodes: 1, duration: 3600.0, public_ip: False,vdc uuid: 6796809a07224f0fbfa2af5cc328729a
2021-08-05 08:38:43.956 | INFO     | jumpscale.sals.vdc.deployer:_log:959 - VDC UUID: 6796809a07224f0fbfa2af5cc328729a, NAME: dev18072021, OWNER: samehabouelsaad kubernetes cluster extension: searching for existing pool on farm lochristi_dev_lab
2021-08-05 08:38:43.987 | INFO     | jumpscale.sals.vdc.deployer:_log:959 - VDC UUID: 6796809a07224f0fbfa2af5cc328729a, NAME: dev18072021, OWNER: samehabouelsaad Kubernetes cluster extension: found pool 13456
2021-08-05 08:38:44.058 | INFO     | jumpscale.sals.vdc.deployer:_log:959 - VDC UUID: 6796809a07224f0fbfa2af5cc328729a, NAME: dev18072021, OWNER: samehabouelsaad executing function: extend
2021-08-05 08:41:49.029 | INFO     | upgrade_traefik:job:20 - Upgrade Traefik Service:: Traefik using latest version 9.20.1
2021-08-05 08:41:53.028 | INFO     | jumpscale.sals.vdc.kubernetes_auto_extend:update_stats:99 - Kubernetes stats: {'k3os-25407': {'cpu': {'total': 2000, 'used': 1900}, 'memory': {'total': 3935.55859375, 'used': 1664}, 'wid': 58641}, 'k3os-31149': {'cpu': {'total': 1000, 'used': 850}, 'memory': {'total': 1987.11328125, 'used': 838}, 'wid': 58640}}
2021-08-05 08:41:57.653 | INFO     | jumpscale.sals.vdc.kubernetes_auto_extend:update_stats:99 - Kubernetes stats: {'k3os-25407': {'cpu': {'total': 2000, 'used': 1900}, 'memory': {'total': 3935.55859375, 'used': 1664}, 'wid': 58641}, 'k3os-31149': {'cpu': {'total': 1000, 'used': 850}, 'memory': {'total': 1987.11328125, 'used': 838}, 'wid': 58640}}
2021-08-05 08:41:57.657 | INFO     | k8s_auto_extend:job:15 - K8S_AUTO_EXTEND: extension triggered
2021-08-05 08:41:58.267 | INFO     | domain:job:25 - restoring domain for deployment: {'Release': 'traefik', 'Version': None, 'Creation': '2021-08-03 15:01:23+00:00', 'Status': 'Running', 'Status Details': [{'lastTransitionTime': '2021-08-03T15:01:23Z', 'lastUpdateTime': '2021-08-03T15:01:23Z', 'message': 'Deployment has minimum availability.', 'reason': 'MinimumReplicasAvailable', 'status': 'True', 'type': 'Available'}, {'lastTransitionTime': '2021-08-03T15:01:23Z', 'lastUpdateTime': '2021-08-03T15:01:37Z', 'message': 'ReplicaSet "traefik-785fd47c46" has successfully progressed.', 'reason': 'NewReplicaSetAvailable', 'status': 'True', 'type': 'Progressing'}], 'User Supplied Values': {}, 'VDC Name': 'dev18072021', 'Domain': '', 'Chart': 'traefik', 'Namespace': 'kube-system'}
2021-08-05 08:41:58.283 | INFO     | domain:job:25 - restoring domain for deployment: {'Release': 'khaled', 'Version': 'production-stretch', 'Creation': '2021-08-03 12:56:43+00:00', 'Status': 'Running', 'Status Details': [{'lastTransitionTime': '2021-08-03T12:57:10Z', 'lastUpdateTime': '2021-08-03T12:57:10Z', 'message': 'Deployment has minimum availability.', 'reason': 'MinimumReplicasAvailable', 'status': 'True', 'type': 'Available'}, {'lastTransitionTime': '2021-08-03T12:56:43Z', 'lastUpdateTime': '2021-08-03T12:57:10Z', 'message': 'ReplicaSet "khaled-peertube-84fc885c66" has successfully progressed.', 'reason': 'NewReplicaSetAvailable', 'status': 'True', 'type': 'Progressing'}], 'User Supplied Values': {}, 'VDC Name': 'dev18072021', 'Domain': 'omar0-peertube-khaled2.webg2dev.grid.tf', 'Chart': 'peertube', 'Namespace': 'peertube-khaled'}
2021-08-05 08:41:58.285 | INFO     | domain:job:25 - restoring domain for deployment: {'Release': 'khaled', 'Version': None, 'Creation': '2021-08-03 12:56:43+00:00', 'Status': 'Running', 'Status Details': [], 'User Supplied Values': {}, 'VDC Name': 'dev18072021', 'Domain': 'omar0-peertube-khaled2.webg2dev.grid.tf', 'Chart': 'postgresql', 'Namespace': 'peertube-khaled'}
2021-08-05 08:41:58.292 | WARNING  | k8s_auto_extend:job:18 - K8S_AUTO_EXTEND: failed to extend k8s cluster.
2021-08-05 08:46:48.915 | INFO     | upgrade_traefik:job:20 - Upgrade Traefik Service:: Traefik using latest version 9.20.1
2021-08-05 08:46:52.440 | INFO     | jumpscale.sals.vdc.kubernetes_auto_extend:update_stats:99 - Kubernetes stats: {'k3os-25407': {'cpu': {'total': 2000, 'used': 1900}, 'memory': {'total': 3935.55859375, 'used': 1664}, 'wid': 58641}, 'k3os-31149': {'cpu': {'total': 1000, 'used': 850}, 'memory': {'total': 1987.11328125, 'used': 838}, 'wid': 58640}}
2021-08-05 08:46:54.541 | INFO     | jumpscale.sals.vdc.kubernetes_auto_extend:update_stats:99 - Kubernetes stats: {'k3os-25407': {'cpu': {'total': 2000, 'used': 1900}, 'memory': {'total': 3935.55859375, 'used': 1664}, 'wid': 58641}, 'k3os-31149': {'cpu': {'total': 1000, 'used': 850}, 'memory': {'total': 1987.11328125, 'used': 838}, 'wid': 58640}}
2021-08-05 08:46:54.545 | INFO     | k8s_auto_extend:job:15 - K8S_AUTO_EXTEND: extension triggered
2021-08-05 08:46:54.722 | WARNING  | k8s_auto_extend:job:18 - K8S_AUTO_EXTEND: failed to extend k8s cluster.
2021-08-05 08:51:11.800 | WARNING  | /sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/auth/bottle/auth:get_user_info:235 - Error in validating user: samehabouelsaad.3bot with email: farouks@incubaid.com in explorer: https://explorer.devnet.grid.tf/api/v1
 from ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2021-08-05 08:51:11.810 | ERROR    | jumpscale.servers.gedis.server:_execute:227 - error while executing <bound method ChatFlows.fetch of <chatbot.ChatFlows object at 0x7fcb19943c70>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
           │       └ (<gevent._socket3.socket at 0x7fcb190849a0 object, fd=75, family=2, type=1, proto=0>, ('127.0.0.1', 53478))
           └ <bound method GedisServer._on_connection of GedisServer(
               instance_name='threebot',
               host='127.0.0.1',
               port=16000,
               enab...

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/servers/gedis/server.py", line 275, in _on_connection
    result = self._execute(method, args, kwargs)
    │        │    │        │       │     └ {'session_id': '3bf39db7-7acd-439e-a4a3-17ee66282637'}
    │        │    │        │       └ []
    │        │    │        └ <bound method ChatFlows.fetch of <chatbot.ChatFlows object at 0x7fcb19943c70>>
    │        │    └ <function GedisServer._execute at 0x7fcb1ad95e50>
    │        └ GedisServer(
    │            instance_name='threebot',
    │            host='127.0.0.1',
    │            port=16000,
    │            enable_system_actor=True,
    │            run_async=True,
    │            _a...
    └ {'result': {'info': {'step': 4, 'steps': 5, 'title': 'Adding node', 'previous': True, 'last_step': False, 'first_step': False...

> File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/servers/gedis/server.py", line 224, in _execute
    response["result"] = method(*args, **kwargs)
    │                    │       │       └ {'session_id': '3bf39db7-7acd-439e-a4a3-17ee66282637'}
    │                    │       └ []
    │                    └ <bound method ChatFlows.fetch of <chatbot.ChatFlows object at 0x7fcb19943c70>>
    └ {}

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/servers/gedis/baseactor.py", line 25, in wrapper
    result = func(*bound.args, **bound.kwargs)
             │     │     │       │     └ <property object at 0x7fcb1f3cfbd0>
             │     │     │       └ <BoundArguments (self=<chatbot.ChatFlows object at 0x7fcb19943c70>, session_id='3bf39db7-7acd-439e-a4a3-17ee66282637')>
             │     │     └ <property object at 0x7fcb1f3cfb80>
             │     └ <BoundArguments (self=<chatbot.ChatFlows object at 0x7fcb19943c70>, session_id='3bf39db7-7acd-439e-a4a3-17ee66282637')>
             └ <function ChatFlows.fetch at 0x7fcb19940820>

  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/chatflows/actors/chatbot.py", line 40, in fetch
    if result.get("category") == "end":
       └ None

AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by waleedhammam** [comment]
Was because the pools endpoint stuck because of stellar

works ok now
