### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID - cert-bot have issue communicating with ca1.grid.tf:443 

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#3346]
### Description

when deploy a new vdc, threebot initialise will fail, also restarting the server (or updating wich restarts also the server) will cause errors as certbot can't get a valid certificate
it tries to pull a certificate for some time till it eventually gives up, and start work without valid cert.

![Screenshot from 2021-11-14 18-05-52](https://user-images.githubusercontent.com/42457449/141688894-cb6f1718-d1a5-4a11-b2b5-374331c069a0.png)

### Installation method

VDC deployed by VDC Devnet deployer

### Traceback/Logs/Alerts

here is the certbot logs

```sh
2021-11-14 15:48:04,847:DEBUG:certbot._internal.main:certbot version: 1.11.0
2021-11-14 15:48:04,848:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2021-11-14 15:48:04,848:DEBUG:certbot._internal.main:Arguments: ['--email', 'motaweam@incubaid.com', '--server', 'https://ca1.grid.tf', '--nginx-server-root', '/root/sandbox/cfg/nginx/main', '--nginx', '--domain', 'samehabouelsaad-dev14112021.vdcdev.grid.tf', '--non-interactive', '--agree-tos', '--logs-dir', '/root/sandbox/var/log/certbot', '--config-dir', '/root/sandbox/cfg/certbot', '--work-dir', '/root/sandbox/var/certbot']
2021-11-14 15:48:04,848:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-11-14 15:48:04,887:DEBUG:certbot._internal.log:Root logging level set at 20
2021-11-14 15:48:04,888:INFO:certbot._internal.log:Saving debug log to /root/sandbox/var/log/certbot/letsencrypt.log
2021-11-14 15:48:04,889:DEBUG:certbot._internal.plugins.selection:Requested authenticator nginx and installer nginx
2021-11-14 15:48:06,046:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * nginx
Description: Nginx Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: nginx = certbot_nginx._internal.configurator:NginxConfigurator
Initialized: <certbot_nginx._internal.configurator.NginxConfigurator object at 0x7f6c655b82b0>
Prep: True
2021-11-14 15:48:06,048:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_nginx._internal.configurator.NginxConfigurator object at 0x7f6c655b82b0> and installer <certbot_nginx._internal.configurator.NginxConfigurator object at 0x7f6c655b82b0>
2021-11-14 15:48:06,048:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator nginx, Installer nginx
2021-11-14 15:48:06,092:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://ca1.grid.tf/acme/acct/KGpvVnTEDCvU', new_authzr_uri=None, terms_of_service=None), 72e508559c5435b16eea3a7f867a73e7, Meta(creation_dt=datetime.datetime(2021, 11, 14, 14, 46, 14, tzinfo=<UTC>), creation_host='localhost', register_to_eff=None))>
2021-11-14 15:48:06,094:DEBUG:acme.client:Sending GET request to https://ca1.grid.tf.
2021-11-14 15:48:06,101:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ca1.grid.tf:443
2021-11-14 15:48:51,188:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='ca1.grid.tf', port=443): Read timed out. (read timeout=45)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python3.8/dist-packages/certbot/_internal/main.py", line 1421, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python3.8/dist-packages/certbot/_internal/main.py", line 1148, in run
    le_client = _init_le_client(config, authenticator, installer)
  File "/usr/local/lib/python3.8/dist-packages/certbot/_internal/main.py", line 659, in _init_le_client
    return client.Client(config, acc, authenticator, installer, acme=acme)
  File "/usr/local/lib/python3.8/dist-packages/certbot/_internal/client.py", line 255, in __init__
    acme = acme_from_config_key(config, self.account.key, self.account.regr)
  File "/usr/local/lib/python3.8/dist-packages/certbot/_internal/client.py", line 43, in acme_from_config_key
    return acme_client.BackwardsCompatibleClientV2(net, key, config.server)
  File "/usr/local/lib/python3.8/dist-packages/acme/client.py", line 821, in __init__
    directory = messages.Directory.from_json(net.get(server).json())
  File "/usr/local/lib/python3.8/dist-packages/acme/client.py", line 1165, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/local/lib/python3.8/dist-packages/acme/client.py", line 1114, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='ca1.grid.tf', port=443): Read timed out. (read timeout=45)
2021-11-14 15:48:51,218:ERROR:certbot._internal.log:An unexpected error occurred:
2021-11-14 15:48:51,222:ERROR:certbot._internal.log:requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='ca1.grid.tf', port=443): Read timed out. (read timeout=45)
```

**Comment by xmonader** [comment]
@abom please check
