### ISSUE TITLE
AttributeError: module 'jumpscale.tools.git' has no attribute 'get_latest_remote_tag'        

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#3357]
```
Traceback (most recent call last):                                                                              
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run                             
  File "/root/js-sdk/jumpscale/packages/threebot_deployer/bottle/utils.py", line 118, in get_threebot_info      
    solution_info = build_solution_info(workloads, threebot)                                                    
  File "/root/js-sdk/jumpscale/packages/threebot_deployer/bottle/utils.py", line 63, in build_solution_info     
    release = j.tools.git.get_latest_remote_tag(sdk_path)                                                       
AttributeError: module 'jumpscale.tools.git' has no attribute 'get_latest_remote_tag'                           
2021-12-19T09:55:43Z <Greenlet at 0x7f8c92c82ae0: get_threebot_info(UserThreebot(                               
  instance_name='threebot_f2a90c0da6)> failed with AttributeError                                               
                                                                                                                
Traceback (most recent call last):                                                                              
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run                             
  File "/root/js-sdk/jumpscale/packages/threebot_deployer/bottle/utils.py", line 118, in get_threebot_info          solution_info = build_solution_info(workloads, threebot)                           
  File "/root/js-sdk/jumpscale/packages/threebot_deployer/bottle/utils.py", line 63, in build_solution_info         release = j.tools.git.get_latest_remote_tag(sdk_path)                                                       AttributeError: module 'jumpscale.tools.git' has no attribute 'get_latest_remote_tag'                           2021-12-19T09:55:43Z <Greenlet at 0x7f8c912b66a0: get_threebot_info(UserThreebot(                                 instance_name='threebot_e4c670dc4d)> failed with AttributeError                                                                                                                                                               Traceback (most recent call last):                                                                                File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Gre...
 ```

happening on deploy3bot.grid.tf

**Comment by sameh-farouk** [comment]
fixed, seems the server wasn't updated and restarted properly.
