### ISSUE TITLE
generating docs is broken in js-sdk

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#367]
first, multiple patch_all calls because oof keeping entrypoint for 3bot in the jumpscale/packages/tfgrid_solutions

```
➜  jumpscale git:(development) ✗ grep -iR patch_all
Binary file entry_points/__pycache__/threebot.cpython-38.pyc matches
entry_points/threebot.py:monkey.patch_all(subprocess=False)  # noqa: E402
packages/tfgrid_solutions/scripts/threebot/entrypoint.py:monkey.patch_all(subprocess=False)  # noqa: E402
➜  jumpscale git:(development) ✗ vim packages/tfgrid_solutions/scripts/threebot/entrypoint.py                 
➜  jumpscale git:(development) ✗ ls packages/tfgrid_solutions/scripts 
threebot
```

and after removing the one in tfgrid_solutions

```
  js-sdk git:(development) ✗ poetry run make docs
pdoc3 jumpscale --html --output-dir docs/api --overwrite
/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/pdoc/cli.py:371: DeprecationWarning: Program option `--overwrite` is deprecated. Use `--force`.
  _warn_deprecated('--overwrite', '--force')
/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/invoke/loader.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/libtmux/common.py:233: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  class TmuxMappingObject(collections.MutableMapping):
/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/aiohttp/helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
<unknown>:338: DeprecationWarning: invalid escape sequence \s
/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/entry_points/jsng.py:2: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util (/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/urllib3/util/__init__.py)', 'aiohttp.connector (/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/aiohttp/connector.py)', 'aiohttp.client (/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/aiohttp/client.py)', 'urllib3.util.ssl_ (/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/urllib3/util/ssl_.py)', 'aiohttp.client_exceptions (/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/aiohttp/client_exceptions.py)', 'aiohttp.client_reqrep (/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py)']. 
  monkey.patch_all(subprocess=False)  # noqa: E402
Traceback (most recent call last):
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/pdoc/__init__.py", line 183, in import_module
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/marketplace/__init__.py", line 1, in <module>
    from .deployer import Network, deployer
  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/marketplace/deployer.py", line 434, in <module>
    deployer = MarketPlaceDeployer()
  File "/home/xmonader/wspace/js/js-sdk/jumpscale/sals/marketplace/deployer.py", line 85, in __init__
    self._explorer = j.core.identity.me.explorer
  File "/home/xmonader/wspace/js/js-sdk/jumpscale/core/identity/__init__.py", line 164, in me
    self.__class__._me = self.get(identity)
  File "/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/core/base/factory.py", line 206, in get
    instance = self.find(name)
  File "/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/core/base/factory.py", line 439, in find
    instance = super().find(name)
  File "/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/core/base/factory.py", line 129, in find
    instance = getattr(self, name, None)
  File "/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/core/base/factory.py", line 492, in getter
    instance = self._get_object_from_config(name, factory.store.get(name))
  File "/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/core/base/factory.py", line 404, in _get_object_from_config
    instance = self._create_instance(name, **data)
  File "/home/xmonader/wspace/js/js-sdk/.venv/src/js-ng/jumpscale/core/base/factory.py", line 161, in _create_instance
    instance = self.type(*args, **kwargs)
  File "/home/xmonader/wspace/js/js-sdk/jumpscale/core/identity/__init__.py", line 49, in __init__
    self.verify_configuration()
  File "/home/xmonader/wspace/js/js-sdk/jumpscale/core/identity/__init__.py", line 68, in verify_configuration
    user = self.explorer.users.get(tid=self._tid)
  File "/home/xmonader/wspace/js/js-sdk/jumpscale/clients/explorer/users.py", line 54, in get
    resp = self._session.get(f"{self._url}/{tid}")
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 342, in connect
    self.ssl_context = create_urllib3_context(
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 276, in create_urllib3_context
    context.options |= options
  File "/usr/lib/python3.8/ssl.py", line 602, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/lib/python3.8/ssl.py", line 602, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/lib/python3.8/ssl.py", line 602, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 474 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xmonader/wspace/js/js-sdk/.venv/bin/pdoc3", line 11, in <module>
    load_entry_point('pdoc3==0.6.4', 'console_scripts', 'pdoc3')()
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/pdoc/cli.py", line 448, in main
    modules = [pdoc.Module(module, docfilter=docfilter)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/pdoc/cli.py", line 448, in <listcomp>
    modules = [pdoc.Module(module, docfilter=docfilter)
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/pdoc/__init__.py", line 602, in __init__
    self.doc[root] = m = Module(import_module(fullname),
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/pdoc/__init__.py", line 602, in __init__
    self.doc[root] = m = Module(import_module(fullname),
  File "/home/xmonader/wspace/js/js-sdk/.venv/lib/python3.8/site-packages/pdoc/__init__.py", line 185, in import_module
    raise ImportError('Error importing {!r}: {}'.format(module, e))
ImportError: Error importing 'jumpscale.sals.marketplace': maximum recursion depth exceeded while calling a Python object

```

you can see code execution in the marketplace package and recursion

**Comment by xmonader** [comment]
fixed by https://github.com/threefoldtech/js-sdk/pull/369
