### ISSUE TITLE
Bug: cannot start threebot on fresh install of js-sdk

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#379]
Stacktrace:

```
(js-sdk-GbuXkjbe-py3.8) ➜  js-sdk git:(development) threebot start --local                            
2020-08-03 12:59:40.565 | INFO     | jumpscale.entry_points.threebot:check_for_bins:34 - ✅ binaries nginx,redis-server,tmux,git required are installed.
2020-08-03 12:59:40.592 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: the configuration file /tmp/tmp4e751r4c syntax is ok
2020-08-03 12:59:40.592 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - 2020/08/03 12:59:40 [emerg] 80369#80369: mkdir() "/var/lib/nginx/client-body" failed (13: Permission denied)
2020-08-03 12:59:40.593 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: configuration file /tmp/tmp4e751r4c test failed
2020-08-03 12:59:52.095 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - jumpscale.core.exceptions.exceptions.Timeout: Wait operation exceeded timeout: 10
Traceback (most recent call last):
> File "/home/dylan/.cache/pypoetry/virtualenvs/js-sdk-GbuXkjbe-py3.8/bin/threebot", line 11, in <module>
    load_entry_point('js-sdk', 'console_scripts', 'threebot')()
    └ <function load_entry_point at 0x7f322ceb95e0>
  File "/home/dylan/.cache/pypoetry/virtualenvs/js-sdk-GbuXkjbe-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f322c028670>
           └ <Group cli>
  File "/home/dylan/.cache/pypoetry/virtualenvs/js-sdk-GbuXkjbe-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f322cc626d0>
         │    └ <function MultiCommand.invoke at 0x7f322c029430>
         └ <Group cli>
  File "/home/dylan/.cache/pypoetry/virtualenvs/js-sdk-GbuXkjbe-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f322cc73280>
           │               │       │       └ <function Command.invoke at 0x7f322c029040>
           │               │       └ <Command start>
           │               └ <click.core.Context object at 0x7f322cc73280>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f322d59f280>
  File "/home/dylan/.cache/pypoetry/virtualenvs/js-sdk-GbuXkjbe-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'local': True, 'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False}
           │   │      │    │           └ <click.core.Context object at 0x7f322cc73280>
           │   │      │    └ <function start at 0x7f3229918670>
           │   │      └ <Command start>
           │   └ <function Context.invoke at 0x7f322c028160>
           └ <click.core.Context object at 0x7f322cc73280>
  File "/home/dylan/.cache/pypoetry/virtualenvs/js-sdk-GbuXkjbe-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'local': True, 'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False}
           │         └ ()
           └ <function start at 0x7f3229918670>

  File "/home/dylan/Projects/js-sdk/jumpscale/entry_points/threebot.py", line 152, in start
    j.servers.threebot.start_default(wait=True, local=local, domain=domain, email=email)
    │ │                                         │     │      │      │       │     └ None
    │ │                                         │     │      │      │       └ None
    │ │                                         │     │      │      └ None
    │ │                                         │     │      └ None
    │ │                                         │     └ True
    │ │                                         └ True
    │ └ <property object at 0x7f322c027f40>
    └ <jumpscale.loader.J object at 0x7f322c5c5ee0>

  File "/home/dylan/Projects/js-sdk/jumpscale/servers/threebot/__init__.py", line 31, in start_default
    server.start(wait=wait)
    │      │     │    └ True
    │      │     └ True
    │      └ <function ThreebotServer.start at 0x7f3228c1e160>
    └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/home/dylan/Projects/js-sdk/jumpscale/servers/threebot/threebot.py", line 628, in start
    self.nginx.start()
    │    └ <property object at 0x7f3228c75770>
    └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/home/dylan/Projects/js-sdk/jumpscale/tools/nginx/nginxserver.py", line 41, in start
    cmd.start()
    │   └ <function StartupCmd.start at 0x7f3228bc5ca0>
    └ StartupCmd(_Base__instance_name='nginx_main', _Base__parent=None, _StartupCmd__tmux_window=Window(@5 2:nginx_main, Session($0...

  File "/home/dylan/.cache/pypoetry/virtualenvs/js-sdk-GbuXkjbe-py3.8/src/js-ng/jumpscale/tools/startupcmd/startupcmd.py", line 314, in start
    self.wait_for_running(die=True, timeout=self.timeout)
    │    │                                  │    └ <property object at 0x7f3228b5aef0>
    │    │                                  └ StartupCmd(_Base__instance_name='nginx_main', _Base__parent=None, _StartupCmd__tmux_window=Window(@5 2:nginx_main, Session($0...
    │    └ <function StartupCmd.wait_for_running at 0x7f3228bc5d30>
    └ StartupCmd(_Base__instance_name='nginx_main', _Base__parent=None, _StartupCmd__tmux_window=Window(@5 2:nginx_main, Session($0...

  File "/home/dylan/.cache/pypoetry/virtualenvs/js-sdk-GbuXkjbe-py3.8/src/js-ng/jumpscale/tools/startupcmd/startupcmd.py", line 272, in wait_for_running
    self._wait(True, die, timeout)
    │    │           │    └ 10
    │    │           └ True
    │    └ <function StartupCmd._wait at 0x7f3228bc5e50>
    └ StartupCmd(_Base__instance_name='nginx_main', _Base__parent=None, _StartupCmd__tmux_window=Window(@5 2:nginx_main, Session($0...

  File "/home/dylan/.cache/pypoetry/virtualenvs/js-sdk-GbuXkjbe-py3.8/src/js-ng/jumpscale/tools/startupcmd/startupcmd.py", line 248, in _wait
    raise j.exceptions.Timeout(f"Wait operation exceeded timeout: {timeout}")
          │ └ <property object at 0x7f322c027e50>
          └ <jumpscale.loader.J object at 0x7f322c5c5ee0>

jumpscale.core.exceptions.exceptions.Timeout: Wait operation exceeded timeout: 10
```

It tries to create a dir in `/var/lib/nginx`, but only root can do this.
Solved by adding `sudo` to the start command. Only once, the next time you start it can be without sudo.

**Comment by xmonader** [comment]
the directory it was trying to create was /var/lib/nginx/client-body

working against `nginx version: nginx/1.14.0 (Ubuntu)` without problems, for dylan it was on 1.18 (Arch)

**Comment by scottyeager** [comment]
Seeing the same here, also with nginx 1.18 on Arch.
