### ISSUE TITLE
Can't start local 3Bot: Session requires a `session_id`

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/js-sdk#496]
When attempting to start a local 3Bot instance, I get a traceback with a final `ValueError: Session requires a 'session_id'`.

I've tried installing both via pip and inside a poetry environment, according to the instructions here: https://manual.threefold.io/#/getting_started_3bot

In both cases, running `threebot start --local` gives the result below.

```
2020-08-16 01:48:34.563 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:38 - nginx: the configuration file /tmp/tmptmikps8p syntax is ok
2020-08-16 01:48:34.563 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:38 - 2020/08/16 01:48:34 [emerg] 1416007#1416007: open() "/tmp/nginxtest.pid" failed (13: Permission denied)
2020-08-16 01:48:34.563 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:38 - nginx: configuration file /tmp/tmptmikps8p test failed
Traceback (most recent call last):
  File "/usr/bin/threebot", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jumpscale/entry_points/threebot.py", line 124, in start
    j.servers.threebot.start_default(wait=True, local=local)
  File "/usr/lib/python3.8/site-packages/jumpscale/servers/threebot/__init__.py", line 29, in start_default
    server.start(wait=wait)
  File "/usr/lib/python3.8/site-packages/jumpscale/servers/threebot/threebot.py", line 611, in start
    self.redis.start()
  File "/usr/lib/python3.8/site-packages/jumpscale/tools/redis/redis.py", line 35, in start
    self.cmd.start()
  File "/usr/lib/python3.8/site-packages/jumpscale/tools/startupcmd/startupcmd.py", line 312, in start
    self._tmux_window.attached_pane.send_keys(command)
  File "/usr/lib/python3.8/site-packages/jumpscale/tools/startupcmd/startupcmd.py", line 103, in _tmux_window
    self.__tmux_window = j.core.executors.tmux.get_js_window(self.instance_name)
  File "/usr/lib/python3.8/site-packages/jumpscale/core/executors/tmux.py", line 34, in get_js_window
    s = get_js_session()
  File "/usr/lib/python3.8/site-packages/jumpscale/core/executors/tmux.py", line 25, in get_js_session
    s = server.find_where({"session_name": JS_SESSION_NAME})
  File "/usr/lib/python3.8/site-packages/libtmux/common.py", line 320, in find_where
    return self.where(attrs)[0]
  File "/usr/lib/python3.8/site-packages/libtmux/common.py", line 351, in where
    return list(filter(by, self.children))
  File "/usr/lib/python3.8/site-packages/libtmux/server.py", line 188, in sessions
    return self.list_sessions()
  File "/usr/lib/python3.8/site-packages/libtmux/server.py", line 183, in list_sessions
    return [Session(server=self, **s) for s in self._sessions]
  File "/usr/lib/python3.8/site-packages/libtmux/server.py", line 183, in <listcomp>
    return [Session(server=self, **s) for s in self._sessions]
  File "/usr/lib/python3.8/site-packages/libtmux/session.py", line 61, in __init__
    raise ValueError('Session requires a `session_id`')
ValueError: Session requires a `session_id`
```

**Comment by waleedhammam** [comment]
Can you please add how did you install and the steps lead to this error ?

**Comment by scottyeager** [comment]
I've tried installing both via pip and inside a poetry environment, according to the instructions here: https://manual.threefold.io/#/getting_started_3bot

In both cases, running `threebot start --local` gives the result above.

**Comment by waleedhammam** [comment]
in docs:
![image](https://user-images.githubusercontent.com/10658229/90331907-954c3f00-dfb8-11ea-8956-fab977d27ba3.png)

Installation using pip will be working after we have an official release
can you try using normal poetry for now

Clone the repository git clone https://github.com/threefoldtech/js-sdk

```
cd js-sdk
poetry update
poetry install
poetry shell
threebot start --local
```

**Comment by scottyeager** [comment]
As I said, I've tried both pip and poetry with the same result. The stacktrace I posted is from trying to run the pip install, because it's cleaner than what's output within the poetry environment. Here's what it looks like from within the poetry environment:

```
threebot start --local
2020-08-16 02:28:11.063 | INFO     | jumpscale.entry_points.threebot:check_for_bins:34 - ✅ binaries nginx,redis-server,tmux,git required are installed.
2020-08-16 02:28:11.092 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: the configuration file /tmp/tmplkkye5zf syntax is ok
2020-08-16 02:28:11.092 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - 2020/08/16 02:28:11 [emerg] 1441507#1441507: bind() to 0.0.0.0:80 failed (13: Permission denied)
2020-08-16 02:28:11.093 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: configuration file /tmp/tmplkkye5zf test failed
2020-08-16 02:28:13.852 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - ValueError: Session requires a `session_id`
Traceback (most recent call last):
> File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/bin/threebot", line 11, in <module>
    load_entry_point('js-sdk', 'console_scripts', 'threebot')()
    └ <function load_entry_point at 0x7f50c6158550>
  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f50c533d430>
           └ <Group cli>
  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f50c5f8e820>
         │    └ <function MultiCommand.invoke at 0x7f50c533e1f0>
         └ <Group cli>
  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f50c670a310>
           │               │       │       └ <function Command.invoke at 0x7f50c533ddc0>
           │               │       └ <Command start>
           │               └ <click.core.Context object at 0x7f50c670a310>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f50c68421f0>
  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'local': True, 'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False}
           │   │      │    │           └ <click.core.Context object at 0x7f50c670a310>
           │   │      │    └ <function start at 0x7f50c2b93ca0>
           │   │      └ <Command start>
           │   └ <function Context.invoke at 0x7f50c533cee0>
           └ <click.core.Context object at 0x7f50c670a310>
  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'local': True, 'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False}
           │         └ ()
           └ <function start at 0x7f50c2b93ca0>

  File "/media/superboot/builds/js-sdk/jumpscale/entry_points/threebot.py", line 152, in start
    j.servers.threebot.start_default(wait=True, local=local, domain=domain, email=email)
    │ │                                         │     │      │      │       │     └ None
    │ │                                         │     │      │      │       └ None
    │ │                                         │     │      │      └ None
    │ │                                         │     │      └ None
    │ │                                         │     └ True
    │ │                                         └ True
    │ └ <property object at 0x7f50c533bf40>
    └ <jumpscale.loader.J object at 0x7f50c5335760>

  File "/media/superboot/builds/js-sdk/jumpscale/servers/threebot/__init__.py", line 31, in start_default
    server.start(wait=wait)
    │      │     │    └ True
    │      │     └ True
    │      └ <function ThreebotServer.start at 0x7f50c1e91790>
    └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/media/superboot/builds/js-sdk/jumpscale/servers/threebot/threebot.py", line 636, in start
    self.redis.start()
    │    └ <property object at 0x7f50c1e90310>
    └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/media/superboot/builds/js-sdk/jumpscale/tools/redis/redis.py", line 35, in start
    self.cmd.start()
    │    └ <property object at 0x7f50c1d47270>
    └ RedisServer(_Base__instance_name='default', _Base__parent=None, __host='127.0.0.1', __port=6379, _cmd=StartupCmd(_Base__insta...

  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/src/js-ng/jumpscale/tools/startupcmd/startupcmd.py", line 312, in start
    self._tmux_window.attached_pane.send_keys(command)
    │    │                                    └ 'sh /home/scott/sandbox/var/cmds/redis_default.sh'
    │    └ <property object at 0x7f50c1dcd860>
    └ StartupCmd(_Base__instance_name='redis_default', _Base__parent=None, _StartupCmd__tmux_window=None, __check_cmd=None, __env={...

  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/src/js-ng/jumpscale/tools/startupcmd/startupcmd.py", line 103, in _tmux_window
    self.__tmux_window = j.core.executors.tmux.get_js_window(self.instance_name)
    │                    │ │                                 │    └ <property object at 0x7f50c383f590>
    │                    │ │                                 └ StartupCmd(_Base__instance_name='redis_default', _Base__parent=None, _StartupCmd__tmux_window=None, __check_cmd=None, __env={...
    │                    │ └ <property object at 0x7f50c533bf90>
    │                    └ <jumpscale.loader.J object at 0x7f50c5335760>
    └ StartupCmd(_Base__instance_name='redis_default', _Base__parent=None, _StartupCmd__tmux_window=None, __check_cmd=None, __env={...

  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/src/js-ng/jumpscale/core/executors/tmux.py", line 38, in get_js_window
    return get_window(session_name=JS_SESSION_NAME, window_name=window_name)
           │                       │                │           └ 'redis_default'
           │                       │                └ 'redis_default'
           │                       └ 'js-ng'
           └ <function get_window at 0x7f50c3174160>

  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/src/js-ng/jumpscale/core/executors/tmux.py", line 42, in get_window
    session = get_session(session_name)
              │           └ 'js-ng'
              └ <function get_session at 0x7f50c3172f70>

  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/src/js-ng/jumpscale/core/executors/tmux.py", line 25, in get_session
    session = server.find_where({"session_name": session_name})
              │      │                           └ 'js-ng'
              │      └ <function TmuxRelationalObject.find_where at 0x7f50c31dbe50>
              └ <libtmux.server.Server object at 0x7f50c31da490>

  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/lib/python3.8/site-packages/libtmux/common.py", line 320, in find_where
    return self.where(attrs)[0]
           │    │     └ {'session_name': 'js-ng'}
           │    └ <function TmuxRelationalObject.where at 0x7f50c31dbee0>
           └ <libtmux.server.Server object at 0x7f50c31da490>
  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/lib/python3.8/site-packages/libtmux/common.py", line 351, in where
    return list(filter(by, self.children))
                       │   │    └ <property object at 0x7f50c316df40>
                       │   └ <libtmux.server.Server object at 0x7f50c31da490>
                       └ <function TmuxRelationalObject.where.<locals>.by at 0x7f50c1dd14c0>
  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/lib/python3.8/site-packages/libtmux/server.py", line 188, in sessions
    return self.list_sessions()
           │    └ <function Server.list_sessions at 0x7f50c3172820>
           └ <libtmux.server.Server object at 0x7f50c31da490>
  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/lib/python3.8/site-packages/libtmux/server.py", line 183, in list_sessions
    return [Session(server=self, **s) for s in self._sessions]
            │              │                   │    └ <property object at 0x7f50c31dd7c0>
            │              │                   └ <libtmux.server.Server object at 0x7f50c31da490>
            │              └ <libtmux.server.Server object at 0x7f50c31da490>
            └ <class 'libtmux.session.Session'>
  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/lib/python3.8/site-packages/libtmux/server.py", line 183, in <listcomp>
    return [Session(server=self, **s) for s in self._sessions]
            │              │       │      │    │    └ <property object at 0x7f50c31dd7c0>
            │              │       │      │    └ <libtmux.server.Server object at 0x7f50c31da490>
            │              │       │      └ {'session_name': 'js-ng_1___$0_1597561812__0_0_'}
            │              │       └ {'session_name': 'js-ng_1___$0_1597561812__0_0_'}
            │              └ <libtmux.server.Server object at 0x7f50c31da490>
            └ <class 'libtmux.session.Session'>
  File "/home/scott/.cache/pypoetry/virtualenvs/js-sdk-jN_J825u-py3.8/lib/python3.8/site-packages/libtmux/session.py", line 61, in __init__
    raise ValueError('Session requires a `session_id`')

ValueError: Session requires a `session_id`

```

**Comment by waleedhammam** [comment]
@scottyeager 
Can you provide us with operating system do you use, version and python and tmux version ?

**Comment by scottyeager** [comment]
Yes, I'm running Arch Linux with Python 3.8.3 and and tmux 3.1b. Js-sdk: commit dc219706deeec2b1d5e77c903b6eab2355604107.

**Comment by scottyeager** [comment]
I've tried downgrading tmux to 3.0a. The session error no longer appears, but threebot hangs after printing:

`2020-08-17 20:23:07.968 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: configuration file /tmp/tmp50_0lrp3 test failed`

**Comment by xmonader** [comment]
@scottyeager thanks for trying out and sorry for the rough experience. I just applied a fix on development branch (details here https://github.com/threefoldtech/js-sdk/pull/519), you can either create the needed dirs manually `sudo mkdir -p /var/lib/nginx/{body,client-body,fastcgi,proxy,scgi,uwsgi} ` then start your 3bot or pull development branch and start your 3bot, I tested on ubuntu and archlinux, please if any blockers let us know. Thank you.

**Comment by scottyeager** [comment]
@xmonader, thanks again for the help, and no worries—this is what beta testing is for, right? ;)

I tried creating those directories and also pulling down the latest changes, but still seeing the session id error. There's something going on with tmux, I think, because changing my tmux version eliminates the error but then causes threebot to hang.

It's confusing that you've had success running in an Arch container. I'm going to try that myself to see if I can figure out what's different versus my system.

**Comment by scottyeager** [comment]
I finally got to the bottom of this, and wow, do I feel silly :rofl:

The issue turned out to be with my locale configuration, where I'd made a typo some years ago when I setup my system (the hazards of manual configuration in distros like Arch, I suppose). It surprises me that I didn't run into a problem with this sooner, and I think my fish shell was actually masking the issue by filling in the missing `$LANG` variable on its own. 

Here's the one reference I could find to the error I was getting, along with the solution: https://github.com/tmux-python/tmuxp/issues/405

It turns out that running a simple search earlier would have saved me a lot of trouble here. On the bright side, this did lead me to uncover the issue with the hosts file on Grid deployments of Ubuntu :)

Thanks once again to @waleedhammam and especially to @xmonader for taking the time to test in an Arch container. All of your support is very much appreciated.
