### ISSUE TITLE
Starting Threebot fails during getting or installing auth package

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/js-sdk#511]
Trying to start a Threebot on Ubuntu 20.04 container running on the Grid. Cloned current js-sdk repo (32c5f7a65279dc677151a0e987e9e8a376b7fb5b) and followed poetry install instructions. Upon running `threebot start`, fails with error:

`jumpscale.core.exceptions.exceptions.Runtime: Error happened during getting or installing auth package, the detailed error is an integer is required (got type bytes)`

Full stack trace: https://pastebin.com/39uadVmc

**Comment by xmonader** [comment]
@scottyeager can you please `rm -rf ~/.config/jumpscale/secureconfig/jumpscale/servers/threebot` I doubt it's an old configurations from previous setup (when you installed using pip at that point)

**Comment by scottyeager** [comment]
Thanks @xmonader. I removed everything, including the full jumpscale config directory, the pip install, and the virtual environment created by poetry, but am still seeing this error even with a fresh start.

**Comment by xmonader** [comment]
@scottyeager I raised the priority to critical 

my suspicion is because of your previous install can we please check the value of `which threebot` out of the poetry shell? if any results comes up this means your removal of the `pip installed version` wasn't successful 

It should only be visible within the shell

- example within the shell (where threebot bin is found)
```
[xmon@arch js-sdk]$ poetry shell
Spawning shell within /home/xmon/.cache/pypoetry/virtualenvs/js-sdk-NQNSzBV5-py3.8
[xmon@arch js-sdk]$ . /home/xmon/.cache/pypoetry/virtualenvs/js-sdk-NQNSzBV5-py3.8/bin/activate
(js-sdk-NQNSzBV5-py3.8) [xmon@arch js-sdk]$ which threebot
/home/xmon/.cache/pypoetry/virtualenvs/js-sdk-NQNSzBV5-py3.8/bin/threebot

```
if that's the case please make sure to remove your js config `rm -rf ~/.config/jumpscale/secureconfig/jumpscale/servers/threebot` and go to js-sdk dir, pull development branch, `poetry update && poetry install` and then `threebot start --local`

- example outside of the shell (where threebot bin not found)
```
[xmon@arch js-sdk]$ which threebot
which: no threebot in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
```

if the problem stands, would you be so kind and attach the following
- `which threebot`
- `tree ~/.config/jumpscale` (tree might no be installed by default on your system)
- `tree ~/.sandbox/config`
- `tmux at` and paste logs from threebot window 


if the problem still stands, I also reached out on telegram to investigate more. please send me your availability.

Thank you for your patience.

**Comment by scottyeager** [comment]
Thanks for your attention to this @xmonader. The outputs you requested are below. Just to make sure there's no confusion, this is separate from my other open issue (Arch running on my laptop). This case is an Ubuntu 20.04 container running on the Grid, which I thought I'd try as Ubuntu appears to be better tested/supported.

* `which threebot` outside poetry: no results
* `which threebot` within poetry: `/root/.cache/pypoetry/virtualenvs/js-sdk-t4Q6A7eq-py3.8/bin/threebot`
* `tree ~/.config/jumpscale`:
```
/root/.config/jumpscale/
|-- config.toml
|-- logs
|   |-- fs
|   |   `-- log.txt
|   `-- redis
|-- privatekey.priv
|-- privatekey.pub
`-- secureconfig
    `-- jumpscale
        |-- core
        |   `-- identity
        |       `-- Identity
        |           `-- default
        |               `-- data
        |-- sals
        |   `-- nginx
        |       `-- nginx
        |           `-- NginxConfig
        |               `-- main
        |                   `-- data
        |-- servers
        |   `-- threebot
        |       `-- threebot
        |           `-- ThreebotServer
        |               `-- default
        |                   `-- data
        `-- tools
            `-- startupcmd
                `-- startupcmd
                    `-- StartupCmd
                        `-- nginx_main
                            `-- data
```
* I don't have a `~/.sandbox` directory
* I don't see a tmux window for threebot

**Comment by waleedhammam** [comment]
I could reproduce using the following

- Create ubuntu solution with the chatflows version 20.04
- Install on system using development branch as the following: https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/quick_start.md#ubuntu
- Start threebot server, `threebot start`

- you will get that error

```
js-sdk-vpmH-Z_5-py3.8) root@zosv2tst-4:~/js-sdk# threebot start
2020-08-19 11:23:15.736 | INFO     | jumpscale.entry_points.threebot:check_for_bins:34 - ✅ binaries nginx,redis-server,tmux,git required are installed.
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(microseconds=5408), 'exception': None, 'extra': {'appname': 'init', 'category': '', 'data': None}, 'file': 'threebot.py', 'function': 'check_for_bins', 'level': 'INFO', 'line': 34, 'message': '✅ binaries nginx,redis-server,tmux,git required are installed.', 'module': 'threebot', 'name': 'jumpscale.entry_points.threebot', 'process': '21764', 'thread': '139921472061504', 'time': datetime(2020, 8, 19, 11, 23, 15, 736534, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200), 'EET'))}
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/loguru/_handler.py", line 144, in emit
    self._writer(str_record)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/src/js-ng/jumpscale/core/logging/logging.py", line 166, in _handle
    if not self._db.is_running():
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/src/js-ng/jumpscale/clients/redis/redis.py", line 51, in is_running
    return self.redis_client.ping()
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/redis/client.py", line 1378, in ping
    return self.execute_command('PING')
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/redis/connection.py", line 584, in _connect
    for res in socket.getaddrinfo(self.host, self.port, self.socket_type,
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/gevent/_socketcommon.py", line 212, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/gevent/resolver/thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception
  File "src/gevent/event.py", line 211, in gevent._event.AsyncResult.exc_info.__get__
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/gevent/_tblib.py", line 371, in g
    return f(a)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/gevent/_tblib.py", line 432, in load_traceback
    return loads(s)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/gevent/_tblib.py", line 337, in unpickle_traceback
    return ret.as_traceback()
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/gevent/_tblib.py", line 202, in as_traceback
    code = CodeType(
TypeError: an integer is required (got type bytes)
--- End of logging error ---
2020-08-19 11:23:15.787 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: the configuration file /tmp/tmp2acyawsg syntax is ok
2020-08-19 11:23:15.788 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: configuration file /tmp/tmp2acyawsg test is successful
2020-08-19 11:23:17.991 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - TypeError: an integer is required (got type bytes)
Traceback (most recent call last):
> File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/bin/threebot", line 11, in <module>
    load_entry_point('js-sdk', 'console_scripts', 'threebot')()
    └ <function load_entry_point at 0x7f4201ff9670>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f42012094c0>
           └ <Group cli>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f4201dff370>
         │    └ <function MultiCommand.invoke at 0x7f420121e280>
         └ <Group cli>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f42024ea580>
           │               │       │       └ <function Command.invoke at 0x7f4201209e50>
           │               │       └ <Command start>
           │               └ <click.core.Context object at 0x7f42024ea580>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f42026231f0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False, 'local': False}
           │   │      │    │           └ <click.core.Context object at 0x7f42024ea580>
           │   │      │    └ <function start at 0x7f41febfc040>
           │   │      └ <Command start>
           │   └ <function Context.invoke at 0x7f420121df70>
           └ <click.core.Context object at 0x7f42024ea580>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False, 'local': False}
           │         └ ()
           └ <function start at 0x7f41febfc040>

  File "/root/js-sdk/jumpscale/entry_points/threebot.py", line 152, in start
    j.servers.threebot.start_default(wait=True, local=local, domain=domain, email=email)
    │ │                                         │     │      │      │       │     └ None
    │ │                                         │     │      │      │       └ None
    │ │                                         │     │      │      └ None
    │ │                                         │     │      └ None
    │ │                                         │     └ False
    │ │                                         └ False
    │ └ <property object at 0x7f4201224310>
    └ <jumpscale.loader.J object at 0x7f420121c520>

  File "/root/js-sdk/jumpscale/servers/threebot/__init__.py", line 31, in start_default
    server.start(wait=wait)
    │      │     │    └ True
    │      │     └ True
    │      └ <function ThreebotServer.start at 0x7f41fdf08040>
    └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/root/js-sdk/jumpscale/servers/threebot/threebot.py", line 638, in start
    self.rack.start()
    │    └ <property object at 0x7f41fdf058b0>
    └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/src/js-ng/jumpscale/servers/rack/rack.py", line 60, in start
    self._start(server_name)
    │    │      └ 'gedis'
    │    └ <function ServerRack._start at 0x7f41fdf08ee0>
    └ ServerRack(_Base__instance_name=None, _Base__parent=None, _factories={}, _running_event=<gevent._event.Event object at 0x7f41...

  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/src/js-ng/jumpscale/servers/rack/rack.py", line 15, in _start
    self._servers[server_name].start()
    │    │        └ 'gedis'
    │    └ {'gedis': GedisServer(_Base__instance_name='threebot', _Base__parent=None, _core_actor=<jumpscale.servers.gedis.systemactor.C...
    └ ServerRack(_Base__instance_name=None, _Base__parent=None, _factories={}, _running_event=<gevent._event.Event object at 0x7f41...

  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/src/js-ng/jumpscale/servers/gedis/server.py", line 192, in start
    j.application.start("gedis")
    │ └ <property object at 0x7f4201224040>
    └ <jumpscale.loader.J object at 0x7f420121c520>

  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/src/js-ng/jumpscale/core/application/application.py", line 20, in start
    if j.core.db.is_running():
       │ └ <property object at 0x7f4201224180>
       └ <jumpscale.loader.J object at 0x7f420121c520>

  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/src/js-ng/jumpscale/clients/redis/redis.py", line 51, in is_running
    return self.redis_client.ping()
           │    └ <property object at 0x7f41feafe720>
           └ RedisClient(_Base__instance_name='main', _Base__parent=None, _RedisClient__client=Redis<ConnectionPool<Connection<host=localh...

```

it's caused from this ping request: https://github.com/threefoldtech/js-ng/blob/b33c525ee59072521999e9bc3b86e63bc4ee5e8b/jumpscale/clients/redis/redis.py#L51


best guess a problem with the flist

**Comment by xmonader** [comment]
@scottyeager @waleedhammam  did some checking, apparently, the problem is caused by the /etc/hosts file doesn't have the appropriate data. Can you please fill it with the 
```
127.0.0.1 localhost
127.0.0.1 YOUR_CONTAINER_HOST_NAME
```

**Comment by scottyeager** [comment]
I updated the hosts file, and it works! Thanks @xmonader and @waleedhammam :+1:

**Comment by xmonader** [comment]
Good to know :) thanks!
