### ISSUE TITLE
on a fresh ubuntu 20.4  (nginx Timedout)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#516]
Following the quickstart document I reached `threebot start --local` part

```
1. mainnet
2. testnet
3. devnet
4. none
Which network would you like to register to? 1
what is your threebot name (identity)? 3BOT_NAME
What is the email address associated with your identity? 3BOT_EMAIL
Configured email for this identity is ahmed.t@incubaid.com
Copy the phrase from your 3bot Connect app here: WORDS
2020-08-18 07:52:40.203 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2020-08-18 07:52:40.203 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: the configuration file /tmp/tmp1jd09uhl syntax is ok
2020-08-18 07:52:40.203 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - 2020/08/18 07:52:40 [emerg] 24050#24050: mkdir() "/var/lib/nginx/body" failed (13: Permission denied)
2020-08-18 07:52:40.203 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:58 - nginx: configuration file /tmp/tmp1jd09uhl test failed
2020-08-18 07:52:52.096 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - jumpscale.core.exceptions.exceptions.Timeout: Wait operation exceeded timeout: 10
Traceback (most recent call last):
> File "/home/xmon/.cache/pypoetry/virtualenvs/js-sdk-NQNSzBV5-py3.8/bin/threebot", line 11, in <module>
    load_entry_point('js-sdk', 'console_scripts', 'threebot')()
    └ <function load_entry_point at 0x7fb0240eb670>
  File "/home/xmon/.cache/pypoetry/virtualenvs/js-sdk-NQNSzBV5-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fb023312430>
           └ <Group cli>
  File "/home/xmon/.cache/pypoetry/virtualenvs/js-sdk-NQNSzBV5-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fb0245d9370>
         │    └ <function MultiCommand.invoke at 0x7fb0233131f0>
         └ <Group cli>
  File "/home/xmon/.cache/pypoetry/virtualenvs/js-sdk-NQNSzBV5-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fb0245d9310>
           │               │       │       └ <function Command.invoke at 0x7fb023312dc0>
           │               │       └ <Command start>
           │               └ <click.core.Context object at 0x7fb0245d9310>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fb02470e1f0>
  File "/home/xmon/.cache/pypoetry/virtualenvs/js-sdk-NQNSzBV5-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'local': True, 'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False}
           │   │      │    │           └ <click.core.Context object at 0x7fb0245d9310>
           │   │      │    └ <function start at 0x7fb020cd1af0>
           │   │      └ <Command start>
           │   └ <function Context.invoke at 0x7fb02330dee0>
           └ <click.core.Context object at 0x7fb0245d9310>
  File "/home/xmon/.cache/pypoetry/virtualenvs/js-sdk-NQNSzBV5-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke(js-sdk-NQNSzBV5-py3.8) ubuntu% nginx -v  
nginx version: nginx/1.18.0 (Ubuntu)
(js-sdk-NQNSzBV5-py3.8) ubuntu% python -V
Python 3.8.2

    return callback(*args, **kwargs)
           │         │       └ {'local': True, 'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False}
           │         └ ()
           └ <function start at 0x7fb020cd1af0>

  File "/opt/js-sdk/jumpscale/entry_points/threebot.py", line 152, in start
    j.servers.threebot.start_default(wait=True, local=local, domain=domain, email=email)
    │ │                                         │     │      │      │       │     └ None
    │ │                                         │     │      │      │       └ None
    │ │                                         │     │      │      └ None
    │ │                                         │     │      └ None
    │ │                                         │     └ True
    │ │                                         └ True
    │ └ <property object at 0x7fb0232a0040>
    └ <jumpscale.loader.J object at 0x7fb02337c940>

  File "/opt/js-sdk/jumpscale/servers/threebot/__init__.py", line 31, in start_default
    server.start(wait=wait)
    │      │     │    └ True
    │      │     └ True
    │      └ <function ThreebotServer.start at 0x7fb020062700>
    └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/opt/js-sdk/jumpscale/servers/threebot/threebot.py", line 637, in start
    self.nginx.start()
    │    └ <property object at 0x7fb01beff860>
    └ ThreebotServer(_Base__instance_name='default', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.jumpscales...

  File "/opt/js-sdk/jumpscale/tools/nginx/nginxserver.py", line 41, in start
    cmd.start()
    │   └ <function StartupCmd.start at 0x7fb01b810820>
    └ StartupCmd(_Base__instance_name='nginx_main', _Base__parent=None, _StartupCmd__tmux_window=Window(@2 2:nginx_main, Session($0...

  File "/home/xmon/.cache/pypoetry/virtualenvs/js-sdk-NQNSzBV5-py3.8/src/js-ng/jumpscale/tools/startupcmd/startupcmd.py", line 314, in start
    self.wait_for_running(die=True, timeout=self.timeout)
    │    │                                  │    └ <property object at 0x7fb01b8206d0>
    │    │                                  └ StartupCmd(_Base__instance_name='nginx_main', _Base__parent=None, _StartupCmd__tmux_window=Window(@2 2:nginx_main, Session($0...
    │    └ <function StartupCmd.wait_for_running at 0x7fb01b810790>
    └ StartupCmd(_Base__instance_name='nginx_main', _Base__parent=None, _StartupCmd__tmux_window=Window(@2 2:nginx_main, Session($0...

  File "/home/xmon/.cache/pypoetry/virtualenvs/js-sdk-NQNSzBV5-py3.8/src/js-ng/jumpscale/tools/startupcmd/startupcmd.py", line 272, in wait_for_running
    self._wait(True, die, timeout)
    │    │           │    └ 10
    │    │           └ True
    │    └ <function StartupCmd._wait at 0x7fb01b810670>
    └ StartupCmd(_Base__instance_name='nginx_main', _Base__parent=None, _StartupCmd__tmux_window=Window(@2 2:nginx_main, Session($0...

  File "/home/xmon/.cache/pypoetry/virtualenvs/js-sdk-NQNSzBV5-py3.8/src/js-ng/jumpscale/tools/startupcmd/startupcmd.py", line 248, in _wait
    raise j.exceptions.Timeout(f"Wait operation exceeded timeout: {timeout}")
          │ └ <property object at 0x7fb023316db0>
          └ <jumpscale.loader.J object at 0x7fb02337c940>

jumpscale.core.exceptions.exceptions.Timeout: Wait operation exceeded timeout: 10

```

and on nginx tmux window

![image](https://user-images.githubusercontent.com/64129/90510129-b2b90e80-e15a-11ea-9e26-ff4365908696.png)

# versions

```
(js-sdk-NQNSzBV5-py3.8) ubuntu% nginx -v  
nginx version: nginx/1.18.0 (Ubuntu)
(js-sdk-NQNSzBV5-py3.8) ubuntu% python -V
Python 3.8.2

```

**Comment by xmonader** [comment]
it's resolved using `sudo mkdir -p /var/lib/nginx/{body,client-body,fastcgi,proxy,scgi,uwsgi}`

**Comment by AhmedHanafy725** [comment]
**Verified**

I could reproduce it using new user on commit df76b16479a60ca7afa8fe48adeb6b5380f4cf42
![image](https://user-images.githubusercontent.com/41957921/90531988-fe79b100-e176-11ea-943c-78557e95b291.png)

After pulling the latest commit and applying the fix
commit: e3ec9421d17960f3b1d6fe48c2ecf14d50b5d17a
![image](https://user-images.githubusercontent.com/41957921/90532295-5d3f2a80-e177-11ea-92bf-c80d0553f092.png)
