### ISSUE TITLE
Network Add access in marketplace issue

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/js-sdk#655]
### Description

When trying to add access to an existing network in market place a key error is thrown due to invalid identifier

### Version information

* OS: docker container: Ubuntu 18
* project commit/version: latest development
* Browser: chrome 84

### Steps to reproduce
- Create a network on local marketplace
- Add access to this network in marketplace network

### Traceback/Logs/Alerts
```
2020-08-26 11:33:25.165 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:152 - error
Traceback (most recent call last):

  File "/root/js-ng/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 171, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f882038ea60>
    └ <marketplace.chats.network.NetworkDeploy object at 0x7f881d5b6a58>

  File "/root/js-ng/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 179, in _execute_current_step
    wrapper(step_name)
    │       └ 'start'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f881e020268>

> File "/root/js-ng/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 143, in wrapper
    getattr(self, step_name)()
            │     └ 'start'
            └ <marketplace.chats.network.NetworkDeploy object at 0x7f881d5b6a58>

  File "/root/js-ng/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 637, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<marketplace.chats.network.NetworkDeploy object at 0x7f881d5b6a58>,)
           └ <function NetworkDeploy.start at 0x7f881fcf8ea0>

  File "/root/js-ng/js-sdk/jumpscale/packages/marketplace/chats/network.py", line 39, in start
    self.network_view = deployer.select_network(self.user_info()["username"], self)
    │                   │        │              │    │                        └ <marketplace.chats.network.NetworkDeploy object at 0x7f881d5b6a58>
    │                   │        │              │    └ <function GedisChatBot.user_info at 0x7f882038ef28>
    │                   │        │              └ <marketplace.chats.network.NetworkDeploy object at 0x7f881d5b6a58>
    │                   │        └ <function MarketPlaceDeployer.select_network at 0x7f881fd351e0>
    │                   └ <jumpscale.sals.marketplace.deployer.MarketPlaceDeployer object at 0x7f881fd372e8>
    └ <marketplace.chats.network.NetworkDeploy object at 0x7f881d5b6a58>

  File "/root/js-ng/js-sdk/jumpscale/sals/marketplace/deployer.py", line 117, in select_network
    return network_views[f"{username}_{network_name}"]
           └ {'ranatarek.3bot_apps': <jumpscale.sals.reservation_chatflow.deployer.NetworkView object at 0x7f881f6ab8d0>}

KeyError: 'ranatarek.3bot_Add Access'

```

**Comment by waleedhammam** [comment]
well, that's a bug in the chatflow engine..
at any step press 2 continuous enter  it'll take the current input to the next step 

suggested solution from @abom 
- disable transitional input (make the button disabled or disable key events once it's clicked or enter is pressed, then disable the button, so it does not accept any more events

**Comment by waleedhammam** [comment]
Proper loading happens now
