### ISSUE TITLE
Error when starting 3sdk

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/js-sdk#69]
I'm trying to install the 3sdk from js-ng but I'm hitting a weird problem.
I've build the 3sdk binary following https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/3sdk.md#building-the-3sdk

but when I try to start it I get:
```
▶️ ./3sdk 
Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth__tkinter.py", line 30, in <module>
FileNotFoundError: Tcl data directory "/tmp/_MEILOo7X4/tcl" not found.
[286859] Failed to execute script pyi_rth__tkinter
(js-ng-1E86Bdzo-py3.8)
```

**Comment by zaibon** [comment]
```
▶ rm -rf dist/ build 
zaibon:github/threefoldtech/js-ng  devlopment_missing_deps ✔                                2h48m  
▶ poetry shell
Spawning shell within /home/zaibon/.cache/pypoetry/virtualenvs/js-ng-1E86Bdzo-py3.8

zaibon:github/threefoldtech/js-ng  devlopment_missing_deps ✔                                2h48m  
▶ . /home/zaibon/.cache/pypoetry/virtualenvs/js-ng-1E86Bdzo-py3.8/bin/activate
(js-ng-1E86Bdzo-py3.8) 
zaibon:github/threefoldtech/js-ng  devlopment_missing_deps ✔                                2h48m  
▶ pyinstaller threesdk.spec 
28 INFO: PyInstaller: 3.6
28 INFO: Python: 3.8.3
29 INFO: Platform: Linux-5.7.2-arch1-1-x86_64-with-glibc2.2.5
33 INFO: An exception occured when testing for UPX:
33 INFO:   ValueError("invalid literal for int() with base 10: '96-git-d7ba31cab8ce+'")
34 INFO: UPX is not available.
35 INFO: Extending PYTHONPATH with paths
['/home/zaibon/dev/gig/code/github/threefoldtech/js-ng/jumpscale', '/tmp']
35 INFO: checking Analysis
35 INFO: Building Analysis because Analysis-00.toc is non existent
35 INFO: Initializing module dependency graph...
36 INFO: Caching module graph hooks...
39 INFO: Analyzing base_library.zip ...
1827 INFO: Processing pre-find module path hook   distutils
1827 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.8'
3134 INFO: Caching module dependency graph...
3219 INFO: running Analysis Analysis-00.toc
3241 INFO: Analyzing jumpscale/entry_points/usershell.py
3405 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
4623 INFO: Processing pre-safe import module hook   six.moves
9824 INFO: Processing pre-find module path hook   site
9824 INFO: site: retargeting to fake-dir '/home/zaibon/.cache/pypoetry/virtualenvs/js-ng-1E86Bdzo-py3.8/lib/python3.8/site-packages/PyInstaller/fake-modules'
9932 INFO: Analyzing hidden import 'packaging.requirements'
10121 INFO: Analyzing hidden import 'pkg_resources.py2_warn'
10121 ERROR: Hidden import 'pkg_resources.py2_warn' not found
10122 INFO: Analyzing hidden import '_cffi_backend'
10122 INFO: Processing module hooks...
10122 INFO: Loading module hook "hook-xml.py"...
10123 INFO: Loading module hook "hook-xml.dom.domreg.py"...
10123 INFO: Loading module hook "hook-sysconfig.py"...
10128 INFO: Loading module hook "hook-sqlite3.py"...
10162 INFO: Loading module hook "hook-shelve.py"...
10169 INFO: Loading module hook "hook-pygments.py"...
11025 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
12908 INFO: Loading module hook "hook-pydoc.py"...
12909 INFO: Loading module hook "hook-pycparser.py"...
12909 INFO: Loading module hook "hook-pkg_resources.py"...
13098 INFO: Processing pre-safe import module hook   win32com
13236 INFO: Excluding import '__main__'
13237 INFO:   Removing import of __main__ from module pkg_resources
13237 INFO: Loading module hook "hook-nacl.py"...
13239 INFO: Loading module hook "hook-lib2to3.py"...
13240 INFO: Loading module hook "hook-encodings.py"...
13276 INFO: Loading module hook "hook-distutils.py"...
13277 INFO: Loading module hook "hook-cryptography.py"...
13403 INFO: Loading module hook "hook-certifi.py"...
13404 INFO: Loading module hook "hook-PIL.py"...
13407 INFO: Import to be excluded not found: 'tkinter'
13407 INFO: Import to be excluded not found: 'FixTk'
13407 INFO: Excluding import 'PySide'
13409 INFO:   Removing import of PySide from module PIL.ImageQt
13409 INFO: Excluding import 'PyQt4'
13410 INFO:   Removing import of PyQt4 from module PIL.ImageQt
13410 INFO: Excluding import 'PyQt5'
13411 INFO:   Removing import of PyQt5 from module PIL.ImageQt
13411 INFO: Loading module hook "hook-PIL.Image.py"...
13704 INFO: Loading module hook "hook-setuptools.py"...
14062 INFO: Loading module hook "hook-_tkinter.py"...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
14127 ERROR: Tcl/Tk improperly installed on this system.
14127 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
14130 INFO: Import to be excluded not found: 'FixTk'
14130 INFO: Excluding import 'tkinter'
14163 INFO: Looking for ctypes DLLs
14322 WARNING: library user32 required via ctypes not found
14422 INFO: Analyzing run-time hooks ...
14434 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
14437 INFO: Including run-time hook 'pyi_rth_certifi.py'
14438 INFO: Including run-time hook 'pyi_rth_pkgres.py'
14439 INFO: Including run-time hook 'pyi_rth__tkinter.py'
14461 INFO: Looking for dynamic libraries
15275 INFO: Looking for eggs
15275 INFO: Using Python library /usr/lib/libpython3.8.so.1.0
15288 INFO: Warnings written to /home/zaibon/dev/gig/code/github/threefoldtech/js-ng/build/threesdk/warn-threesdk.txt
15357 INFO: Graph cross-reference written to /home/zaibon/dev/gig/code/github/threefoldtech/js-ng/build/threesdk/xref-threesdk.html
15377 INFO: Appending 'datas' from .spec
15386 INFO: checking PYZ
15386 INFO: Building PYZ because PYZ-00.toc is non existent
15386 INFO: Building PYZ (ZlibArchive) /home/zaibon/dev/gig/code/github/threefoldtech/js-ng/build/threesdk/PYZ-00.pyz
16435 INFO: Building PYZ (ZlibArchive) /home/zaibon/dev/gig/code/github/threefoldtech/js-ng/build/threesdk/PYZ-00.pyz completed successfully.
16458 INFO: checking PKG
16458 INFO: Building PKG because PKG-00.toc is non existent
16458 INFO: Building PKG (CArchive) PKG-00.pkg
21323 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
21325 INFO: Bootloader /home/zaibon/.cache/pypoetry/virtualenvs/js-ng-1E86Bdzo-py3.8/lib/python3.8/site-packages/PyInstaller/bootloader/Linux-64bit/run
21325 INFO: checking EXE
21325 INFO: Building EXE because EXE-00.toc is non existent
21325 INFO: Building EXE from EXE-00.toc
21326 INFO: Appending archive to ELF section in EXE /home/zaibon/dev/gig/code/github/threefoldtech/js-ng/dist/3sdk
21347 INFO: Building EXE from EXE-00.toc completed successfully.
(js-ng-1E86Bdzo-py3.8) 
zaibon:github/threefoldtech/js-ng  devlopment_missing_deps ✔                                2h48m  
▶                 
(js-ng-1E86Bdzo-py3.8) 
zaibon:github/threefoldtech/js-ng  devlopment_missing_deps ✔                                2h49m  
▶ ./dist/3sdk 
Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth__tkinter.py", line 30, in <module>
FileNotFoundError: Tcl data directory "/tmp/_MEI07m1gD/tcl" not found.
[310737] Failed to execute script pyi_rth__tkinter
(js-ng-1E86Bdzo-py3.8) 
```
