### ISSUE TITLE
Clean up deprecated methods and code in explorer client and ZOS, reservation_chatflow sals (weight=1)

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#697]
### Description

unhandled endpoint for testnet/devnet in explorer client, https://github.com/threefoldtech/js-sdk/blob/66e8b17c79da0ed0934f0c369a1d322255fef00b/jumpscale/clients/explorer/reservations.py#L40

The legacy api doesn't work anymore so we should add the new one 

### Version information

* OS: ubuntu 20.04
* project commit/version: Latest development
* Browser: chrome 84

### Steps to reproduce

> `jsng`
> `j.sals.zos.reservation_get("463386")`

### Traceback/Logs/Alerts

```bash
JS-NG> j.sals.zos.reservation_get("470661")                                                                                                                                                                   
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/waleed/js-sdk/jumpscale/sals/zos/zos.py", line 130, in reservation_get
    return self._explorer.reservations.get(reservation_id)
           │                               └ '470661'
           └ <jumpscale.sals.zos.zos.Zosv2 object at 0x7fb1f8c1b400>
  File "/home/waleed/js-sdk/jumpscale/clients/explorer/reservations.py", line 85, in get
    resp = self._session.get(url)
           │                 └ 'https://explorer.testnet.grid.tf/explorer/reservations/470661'
           └ <jumpscale.clients.explorer.reservations.Reservations object at 0x7fb1f5c045b0>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
           │                   │      └ {'allow_redirects': True}
           │                   └ 'https://explorer.testnet.grid.tf/explorer/reservations/470661'
           └ <requests.sessions.Session object at 0x7fb1f8c1b610>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
           │         │       └ {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │         └ <PreparedRequest [GET]>
           └ <requests.sessions.Session object at 0x7fb1f8c1b610>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
    │   │                         │      │    └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
    │   │                         │      └ <Response [404]>
    │   │                         └ {'response': [<function raise_for_status at 0x7fb1f6796700>]}
    │   └ <function dispatch_hook at 0x7fb1f778d160>
    └ <Response [404]>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
                 │    │            └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
                 │    └ <Response [404]>
                 └ <function raise_for_status at 0x7fb1f6796700>
  File "/home/waleed/js-sdk/jumpscale/clients/explorer/errors.py", line 23, in raise_for_status
    raise HTTPError(http_error_msg, response=resp)
          │         │                        └ <Response [404]>
          │         └ '404 Client Error: mongo: no documents in result for url: https://explorer.testnet.grid.tf/explorer/reservations/470661'
          └ <class 'requests.exceptions.HTTPError'>
requests.exceptions.HTTPError: 404 Client Error: mongo: no documents in result for url: https://explorer.testnet.grid.tf/explorer/reservations/470661
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/waleed/js-sdk/jumpscale/sals/zos/zos.py", line 130, in reservation_get
    return self._explorer.reservations.get(reservation_id)
           │                               └ '470661'
           └ <jumpscale.sals.zos.zos.Zosv2 object at 0x7fb1f8c1b400>
  File "/home/waleed/js-sdk/jumpscale/clients/explorer/reservations.py", line 85, in get
    resp = self._session.get(url)
           │                 └ 'https://explorer.testnet.grid.tf/explorer/reservations/470661'
           └ <jumpscale.clients.explorer.reservations.Reservations object at 0x7fb1f5c045b0>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
           │                   │      └ {'allow_redirects': True}
           │                   └ 'https://explorer.testnet.grid.tf/explorer/reservations/470661'
           └ <requests.sessions.Session object at 0x7fb1f8c1b610>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
           │         │       └ {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │         └ <PreparedRequest [GET]>
           └ <requests.sessions.Session object at 0x7fb1f8c1b610>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
    │   │                         │      │    └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
    │   │                         │      └ <Response [404]>
    │   │                         └ {'response': [<function raise_for_status at 0x7fb1f6796700>]}
    │   └ <function dispatch_hook at 0x7fb1f778d160>
    └ <Response [404]>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
                 │    │            └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
                 │    └ <Response [404]>
                 └ <function raise_for_status at 0x7fb1f6796700>
  File "/home/waleed/js-sdk/jumpscale/clients/explorer/errors.py", line 23, in raise_for_status
    raise HTTPError(http_error_msg, response=resp)
          │         │                        └ <Response [404]>
          │         └ '404 Client Error: mongo: no documents in result for url: https://explorer.testnet.grid.tf/explorer/reservations/470661'
          └ <class 'requests.exceptions.HTTPError'>
requests.exceptions.HTTPError: 404 Client Error: mongo: no documents in result for url: https://explorer.testnet.grid.tf/explorer/reservations/470661

404 Client Error: mongo: no documents in result for url: https://explorer.testnet.grid.tf/explorer/reservations/470661
```

**Comment by m-motawea** [comment]
the above call is deprecated on testnet. we should use `j.sals.workloads.get(WORKLOAD_ID)`
