### ISSUE TITLE
Can't create new wallet from admin panel

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/js-sdk#96]
- Creating a new wallet from admin panel

   When creating a new wallet from the admin panel (wallet manager) notification of wallet created successfully appears but the actual wallet is not created nor saved. When trying to do the same action using the wallet manager actor the following error is shown:
   ```
   JS-NG> gedis_server = j.servers.threebot.default                                                                                                                                                           
   JS-NG> gedis_server.gedis_http.client.actors.admin_wallet.create_wallet("test_Wallet_1")                                                                                                                   
   {'success': False, 'result': None, 'error': 'Traceback (most recent call last):\n  File "/root/.cache/pypoetry/virtualenvs/js-sdk-8MwJjzMr-py3.6/src/js-ng/jumpscale/servers/gedis/server.py", line 221, in _execute\n    response[\x1b[31m\'result\'\x1b[m] = method(*args, **kwargs)\n    \x1b[36m│                    │       │       └ {}\x1b[m\n    \x1b[36m│                    │       └ [\'test_Wallet_1\']\x1b[m\n    \x1b[36m│                    └ <bound method Wallet.create_wallet of <wallet.Wallet object at 0x7f05e193b5c0>>\x1b[m\n    \x1b[36m└ {}\x1b[m\n  File "/root/.cache/pypoetry/virtualenvs/js-sdk-8MwJjzMr-py3.6/src/js-ng/jumpscale/servers/gedis/baseactor.py", line 20, in wrapper\n    result = func(*bound.args, **bound.kwargs)\n    \x1b[36m         │     │             └ <BoundArguments (self=<wallet.Wallet object at 0x7f05e193b5c0>, name=\'test_Wallet_1\')>\x1b[m\n    \x1b[36m         │     └ <BoundArguments (self=<wallet.Wallet object at 0x7f05e193b5c0>, name=\'test_Wallet_1\')>\x1b[m\n    \x1b[36m         └ <function Wallet.create_wallet at 0x7f05e19558c8>\x1b[m\n  File "/root/js-ng/js-sdk/jumpscale/packages/admin/actors/wallet.py", line 9, in create_wallet\n    \x1b[33;1mimport\x1b[m pdb\nAttributeError: module \'jumpscale.clients.explorer\' has no attribute \'get_default\'\n', 'error_type': <GedisErrorTypes.ACTOR_ERROR: 3>, 'is_async': False, 'task_id': None}
   ```
   Although the error appears to be related to `jumpscale.clients.explorer.get_default()`, when trying in the shell `j.clients.explorer.get_default()` the default instance is returned

![Screenshot from 2020-06-24 16-50-34](https://user-images.githubusercontent.com/17128393/85579513-3c58ce00-b63b-11ea-835e-71d35a860bbc.png)

**Comment by ranatrk** [comment]
The new namespace loader caused this issue, which it's use is temporarily reverted to use the old one. The issue will not be reproducible/fixed until the new namespace loader is used again. 
blocked on : https://github.com/threefoldtech/js-ng/issues/362

**Comment by xmonader** [comment]
I restored the old loader, things should be working fine now already?

**Comment by BolaNasr** [comment]
It works fine now
